/* XPM */
static xpm_row_t const b[] = {
/* columns rows colors chars-per-pixel */
"175 175 256 2 ",
"   c #010204",
".  c #030906",
"X  c #03050A",
"o  c #040A0B",
"O  c #0B0909",
"+  c #160C07",
"@  c #070B13",
"#  c #0A1518",
"$  c #171718",
"%  c #14120D",
"&  c #3A140B",
"*  c #271917",
"=  c #391714",
"-  c #2B130A",
";  c #2B2519",
":  c #382719",
">  c #312E15",
",  c #151B25",
"<  c #091826",
"1  c #2C1B26",
"2  c #182529",
"3  c #132B34",
"4  c #272627",
"5  c #382826",
"6  c #2F3233",
"7  c #152419",
"8  c #48160A",
"9  c #57180A",
"0  c #471914",
"q  c #571B13",
"w  c #4C0E05",
"e  c #671B06",
"r  c #761C04",
"t  c #691C13",
"y  c #4F2917",
"u  c #782307",
"i  c #6D2311",
"p  c #472927",
"a  c #572726",
"s  c #483826",
"d  c #513632",
"f  c #673739",
"g  c #6D3331",
"h  c #4F1C28",
"j  c #354637",
"k  c #4B4428",
"l  c #56462C",
"z  c #594935",
"x  c #5B5537",
"c  c #494A36",
"v  c #66583A",
"b  c #674F37",
"n  c #69633D",
"m  c #75643C",
"M  c #524D27",
"N  c #11334A",
"B  c #293745",
"V  c #363A46",
"C  c #2C3650",
"Z  c #2B2F5E",
"A  c #503A4A",
"S  c #6F3C45",
"D  c #4F3466",
"F  c #3A4857",
"G  c #34474D",
"H  c #305170",
"J  c #184862",
"K  c #595648",
"L  c #4E4F50",
"P  c #75454A",
"I  c #695A45",
"U  c #774B55",
"Y  c #7A545A",
"T  c #6B514D",
"R  c #586456",
"E  c #6A6446",
"W  c #766748",
"Q  c #7A734B",
"!  c #696857",
"~  c #776A56",
"^  c #7A7557",
"/  c #697357",
"(  c #485566",
")  c #565968",
"_  c #4E5572",
"`  c #715768",
"'  c #576777",
"]  c #55686C",
"[  c #666966",
"{  c #797768",
"}  c #767976",
"|  c #6C6F70",
" . c #862506",
".. c #8C2A0E",
"X. c #84220E",
"o. c #885055",
"O. c #857957",
"+. c #87734F",
"@. c #865B66",
"#. c #8F586A",
"$. c #867968",
"%. c #887A75",
"&. c #8E6A71",
"*. c #AA7666",
"=. c #8D334E",
"-. c #7B847A",
";. c #74846D",
":. c #788258",
">. c #8A8459",
",. c #93875B",
"<. c #8A8568",
"1. c #958969",
"2. c #898677",
"3. c #968A77",
"4. c #9A9478",
"5. c #96936E",
"6. c #A49879",
"7. c #AC9470",
"8. c #ACA17B",
"9. c #A48F68",
"0. c #C5A378",
"q. c #325885",
"w. c #2A6598",
"e. c #506F91",
"r. c #6F768C",
"t. c #5277A6",
"y. c #5D679A",
"u. c #276DC3",
"i. c #8F778B",
"p. c #A37394",
"a. c #BE679F",
"s. c #768691",
"d. c #738EAF",
"f. c #5785AD",
"g. c #7698C9",
"h. c #3A87A3",
"j. c #888A85",
"k. c #978B86",
"l. c #8A9389",
"z. c #989789",
"x. c #989A96",
"c. c #8D8B97",
"v. c #A59B88",
"b. c #A69A95",
"n. c #AC8E92",
"m. c #9BA39A",
"M. c #99A48B",
"N. c #A9A489",
"B. c #B4A88B",
"V. c #A8A699",
"C. c #B4AB98",
"Z. c #B7B39A",
"A. c #ACB29A",
"S. c #869BB9",
"D. c #9093AA",
"F. c #AB98AC",
"G. c #99A5B0",
"H. c #ABACA4",
"J. c #A7A9A6",
"K. c #B4ACA7",
"L. c #ADB2AB",
"P. c #A9B2A6",
"I. c #B3B4AD",
"U. c #B9B6A8",
"Y. c #A8A8B8",
"T. c #B6A9B7",
"R. c #B4B5B3",
"E. c #BBBBB4",
"W. c #BCBDBA",
"Q. c #B7B8B5",
"!. c #ADB5B2",
"~. c #C9B393",
"^. c #C4BBAA",
"/. c #C3BCB4",
"(. c #C3BDBA",
"). c #C7B9B8",
"_. c #CFB1AF",
"`. c #EBB3B0",
"'. c #D4989B",
"]. c #BDC2BB",
"[. c #BAC3B7",
"{. c #B7C5B0",
"}. c #C4C3BC",
"|. c #CAC4BC",
" X c #C8C6B9",
".X c #D3CBBD",
"XX c #D7C8B7",
"oX c #D2CBB2",
"OX c #EACDB9",
"+X c #D3D6B1",
"@X c #98AAC7",
"#X c #8FAACA",
"$X c #A8B4C9",
"%X c #B8B9C7",
"&X c #B7BCD3",
"*X c #AAB0CC",
"=X c #979FCF",
"-X c #C6BBC6",
";X c #CAB8D1",
":X c #DBB9D5",
">X c #BCC5C5",
",X c #BAC5D8",
"<X c #ADC2D3",
"1X c #BCCAE3",
"2X c #C4C5C2",
"3X c #CBC5C2",
"4X c #C5CAC4",
"5X c #CBCBC4",
"6X c #CCCDCA",
"7X c #C6C7CB",
"8X c #D3CCC4",
"9X c #D2CECA",
"0X c #D8CBC7",
"qX c #CDD2CC",
"wX c #CBD2C6",
"eX c #D4D2C5",
"rX c #DAD3C4",
"tX c #D3D3CD",
"yX c #DBD4CC",
"uX c #DCD9CC",
"iX c #D7DAC9",
"pX c #C3CCDC",
"aX c #C7C8D7",
"sX c #D4CBD5",
"dX c #CAD2D8",
"fX c #D4D5D2",
"gX c #DAD6D2",
"hX c #D5D9D3",
"jX c #DBDAD4",
"kX c #DCDCDA",
"lX c #D6D7DB",
"zX c #E3DBCC",
"xX c #E5D7C7",
"cX c #E3DCD3",
"vX c #E2DDDA",
"bX c #E7DBD6",
"nX c #ECCCCC",
"mX c #DDE1DA",
"MX c #D9E2CC",
"NX c #E3E2DC",
"BX c #EBE4DB",
"VX c #E9E3D6",
"CX c #EEE6D5",
"ZX c #C7CDE3",
"AX c #CBD3E3",
"SX c #C9D5E5",
"DX c #D5DAE7",
"FX c #D4D3EC",
"GX c #E8DCE6",
"HX c #DBE3EA",
"JX c #DCE3F2",
"KX c #E4E4E2",
"LX c #EAE9E5",
"PX c #F3EBE5",
"IX c #FBFAFB",
"UX c #EBEDF0",
/* pixels */
"hXBXKXBXmXfXfX4XgXvXsX(.E.E.R. X6X7X>X>X>XQ.aXmX6XfX4X5XfX0X7X2XqXqXhX[.m.I.wXwXlXJXDXHXdXW.Q.Q.W.7XV.2.{ { 2.3.k.b.V.b.;.{ -.j.l.J.wX2XfXgXjX9XL.J.W.P.x.>X{.{.6XR.J.6X4X[.L.wXcXGX9X6XfX2X5X}. XwXyXtXtXkXwXQ.R.qXmXhXvXsX-XDXeXhX6X[.tXR.[.fX6X6XW.}.fXfX7X5XlXjXgXjXKXjX>XkXUXkXjXjX}.4XlXkXKXkX9X5XsXmXqXJ.>X9XLXiXP.U.4XP.}.E.wX.X(.tXNXjXKXfXfXlXqX[.I.",
"3XmXvXkXKXLXDXW.kXDXsXR.J.R.}.vXfX7XQ.E.>XJ.!.UX2X-.x.}.3X).}.2XhXmXwX4XkX].L.jXKX5Xl.j.l.{ -.V.J.z.{ { 2.$.%.%.j.} { 2.l.z.V.J.L.R.tXjXkX5XfXvXx.[ R x.W.jXfX6X4XL.J.R.qX7X6XMX6XR.W.-XW.4X5X|.eXNXcXgXNXBXeX X2X2XKXkXfX7XL.6XhXE.5X4XqXR.R.tXmX4X4XqXfX6X2X(.W.fXvXvXvXtXW.>XKX4X4XiX6XtXlXfXKXkXkXsXtXjXdX[.6XfXKXjX4XeXuX}. XMXNXeXjXvXgXNXKXfXgXgX4X}.wX",
"(.GXGXGXvXDX-Xc.l.l.m.P.%XfXaX6XlXsX7XE.!.m.l.MX6Xx.L.]./.(.I.2XtXBXkXgXjX4X}.kXiXqXx.3.z.4.2.v.U.C.4.N.C.v.v.V.} ! / 3.K.}.5XfXfXkXhX].6XmXKXqX[.m.m.jXbXsXyXyX5XW.].W.qX].4XdXhX{.!.l.l.5X3XtXmXNXbXbXvXtX6XmXfX].fXfXW.[.!.!.R.l.E.5XfXtXW.4XqXL.}.qX6XlXhXkX%X6XgX5X6XfX6XkXfX-X(.4X9XvXvX9XlXfXkXvXfXtXtXtXgXjXiXjXmXuXrX5XI.iXmXiXhXVXjXLXvXvXVXvXgXgXtX",
"9XfXfXdXaX%Xr.6 j ;.m.P.I.hXmXlXNXvXKX4X[.{.M.P.E.E.L.J.|.U.j.I.|.cXLXcX5X8XyXtXyXNXeX[.{. XoX~.8XrX5X X X X5X8XA.m.V.[.eX6XtXgXjXgXtX4XqXhXfX].[.[.].5X).9X0X-XqX5XqXtXlX>X[.>X>XtX>XR L c.R.mXjXtXgX3XK.x.P.fXhXaXfXfXfX[.m.} l.l.Q.6XhXhX(.I.}.H.(.E.R.5X6XfXQ.2X7X2XfXNXfXdXkX6X2X(.(.yXjX-X6X5XgXvXgX8XiXNXgXiX|..XeX X/.}.V.P.5X].E.iXNXNXLXiX5X5X2X4XfX",
"s.M.l.[ c j j # . ;.MX{.m.I.4X}.-XE.3XI.I.[.M.l.m.l.R l.NX}.j.U.}.5X5X2X5X8X5XqXjXgXjXtX4XyX8XoX4X9X9X5XfXmXfXsXwXeXhXhXqX6XfXkX9XvXqX!.m.!.4XfX5X}.|.x.-.m.P.>X4XR.J.>XfXhX>X7X}.MX5Xl.[ j.m.s.m.m.J.l.R [ m.!.HXUX[.4XUXmX>Xj.J.E.P.[.dX4XE.J.|.6XtXI.E.6X2X6X>XW.>X4XfXlX7X7XdX%XR.R.}.gXvXcXlX6X6XgX9X8XcXbXuXiX.X|.9X(.U.5X4X|.tX5XE.wXhXwXM.-.l.J.W.7X6X",
"-.P.{.l.R ] l.l.R M.MX{.4.P.5X}.6XI.H.P.>XMXwXwX].M.R s.hX6XW.qX4X2X2XE.J.7XLXKXLXvXlXW.W.cXjX).7X-X7XdXlX7XR.W.}.3X}.E.W.W.7XhX9XNX>Xm.s.{.qXfXyXtXhXL.| | ;.{.fXW.m.].7XdX>XkXLXNXkXgXM.s.l.j G R | L G { P.P.fXmXz.l.qXmXNX2X9XE.| x.fXhX4X}.E.mXjX].4XfX4X-X>X2XfXfXfXhX6XdX6XR.J.R.6X6XfXDXfX5X6XwX5XuXBXBXPXLXkXyXgXtXeXNXqXhXwXI.L.V.l.M.;.[ -.[.tX6X7X",
";.;.m.].}.wXMXP.P.P.5X4X}.hXtXI.6XI.} | m.{.[.HXmX[.m.l.J.4XqX4X7XR.-XW.c.x.qXdXkXNX9XJ.R.vXkX9X5X7XqX>X!.m.m.].5X}.Q.!.Q.J.P.].gXE.J.[.[.>X].6XkXiXkXmX>X[.!.HXKXlXaXqXdXwX>XqXDXKXjX5Xz.} m.s.[ M.P.m.m.[.MXMXmXjXW.[.MXKXkX2X9XJ.[ j.[.HXmXmX4XNXfX7X6X5X2Xb.l.G.fXkXfXhXdX>X7X>X2XqX7XQ.!.W.6XfXdXwX4XiXVXzXkXcXfX6XlXkXkXKXmXNXNX5X XI.V.{.wX[.5XmXvX9X4X",
"] R -.4X XE.eXiX6XR.sXvX9X7X%XW.(.R.R 6 | -.s.>XqXdXdXP.P.qXW.Q.Y.x.c.G.x.R G | j.I.E.R.lXfXK.5X).Q.R.x.j.2.m..X6X6X7XfXdXQ.L.}.jXW.m.>XwXMXhXVXfXKXhXkXhXMXhXhXdX6X6X7XhX>XL.m.m.aXR.K.eX5X].hXP.dXNXNXiXU.A.iXeX[.5X5X4XtX(.E.).Q.L.P.J.4XmXBXmXKXqXkXhXhXKXJ.' l.Y.J.H.%X>X!.x.2XNXhX4XQ.!.<XsXDXUXMX[.}. XU.L.I.J.R.5XDXKXjXhX5XNXmXwX4XMXmXNXmXKXPXvXgXgX",
"A.m. X{.m.L.|.mXtXfXY.J.D.x.F.b.L.[.J.2.2.M.I.hXdX7X6XlXgXlXhX4X[.m.m.!.x.L j R } P.].>XsX7XJ.G.7X7Xj./ -.z. XrXhXmXhXNXjXqXjX7XgXPXtX7XfXdXqXHXhX|.5XfXjX9X-XvXgX6XR.L.4XqX4XE.L.tX5X8XyX3XgXlX>X!.mX5X3Xm./.5X5XH.2.R R m.].I.4XE.L.H.H.hXkXkXKXDXDX-XT.sXGXgXR.x.z.J.x.P.m.R } ].5XNXhXqXhXhXeXtXKX6X].qX7X>XW.J.Q.J.R.qXlX6XlXHXlX6X2X6XtXtXmXKXfXfXNX}.8X",
"mX{.{.hXhX6XR.J.hXLXQ.| L ) | | l.[.iXwXMXmXqXqXfX[.(.9X9X6XhXhXhXhXfXwX>XP.P.P.}.MX6X7XlX%XG.j.J.R.L.H. XMX.X.XiXBXvX8X3XfXNX6XgXgXtXjXqX>XqX7XhX6XtX6X6X5XR.W.fXmXvXlXlXhX7X>XW.jXhXjXbXyXyX5Xm.j.E.].R.l.I.4XE.A.m.} { J.qXfXKXtX}.}.E.mXkXkXlXLXsXj.[ l.J.Q.qXW.].jX[.l.l.m.E.tX}.5XwXwXBXUX}.tXLXfXW.].J.x.].2XMXHXhXHXlXaX3XfXNX7X(.9X6X4X6XmXtX}.hXjXVX",
"DX2XR.aXKXDX>XG.[.fX6Xx.L j j c A.8XuXiXmXhX7XsXtX|.4XtXgXfXhXfX4XhXtX7XwXhXwX>X}.mX6XdX7XR.2XL.l.H.jXqX5XjXeXgXbXvXNXcXtXjXmXmX6X4X].qXdXqXhXdXlXlXfX].J.J.J.fXlX4X>XhXHXMX>X[.L.].E.E.9XvXLXNXR.m.qX6XP.x.A.L.R ;.m.J.J.[.4X4X6X6XtXhX5XhXsXlXsXGX).| R | | -.E.4XW.[.P.l.s.>X4X}.W.qXtX4XNXNXKXtX5XR.R.2XR.x.E.4XqXmX>X6XsX6XI.E.tX5XW.6XqXhX7XhX6X}.6X6XgX",
"LXKX5X5X[.x.m.P.L.L.tX7Xx.| [ s.}.tX|.E.6XtX9XvXyXtX8X9XjXKXkX5X6XtXtXfXmXmXfX4X4XlXhXfX2X>XHXkX(.[.tXtX4XfXjXkXvXyXvX5X}.dXqXhXW.5Xx.x.4XhXfXKXlXW.J.Y.L.c.-.l.c.l.m.dXHXwX>XqXmXmX6X4XgXKXvXyX].].KXmXQ.[.qX}.J.P.wXqXqX6XW.E.x.J.].5X5XDXkXDXGXQ.c.2.l.l.;.-.}.qXJ.x.J.[.[.wXhX|.4XjXjX}.hXhXtXfXjXtX4XfXhXfX].7X6XmX4XW.4X}.Q.I.%XhX5XR.E.>XE.4X6X4XW.I.E.",
"bXjX}.4XJ.R [ m.l.V.kXKXhXqXP.G.J.!.x.c.Q.bXzXyXuXeX X5XgXvXvXvXGXvXjXfXjXjXhXlXlX2X6X7X5XmXNXhXkX5X9XKXfX4XNXkXmXmXqXl.-.P.P.l.R.[.l.l.W.6X}.(.lX>XJ.W.>XJ.l.j.Q.x.x.J.!.{.!.{.>XqXhXhXhXKXHXgXR.].NXkX].jXKXNXP.!.].6XqXhXqXhX2XW.>XL.!.qXfXaXm.[ [ m.[.wX}. XNXhXW.W.4XlXmXKXmX6XkXBXLXhXKXNXR.!.[.5X7X].tXiXvXfXfXhXtXW.tX(.aX7XW.mX4Xm.L.V.R.qXkXfX2XaXtX",
"NXjX2X9XeXL.I.eX>X4XfX5X|.qX[.x.) L L | W.gXrXxXvXvXgXjXjXfXfXLXvXgX(.K.I.2XtXkXhX!.2X}.iXUXNXkXjXgXkXUX6X!.fXNXNXmXfXm.l.m.G.m.qX>X>XfXNXvXyXR.P.Q.Q.[.4X4XqXtXqX].[.7X7X>Xm.] L -.[.HXkXKXtX4X6X4XlXgX5XqXtXVXwXqXvXkXkXtX].4XhX6XW.2.[ } l.m.R G ;.J.{.4X X/.7XfXhXKXqXfXfXkXmX6X].I.!.!.4XwXhX].L.].6XtXNXkXKXtXtX2X4X].hX|.6X6X].tX}.}.LX6XqX6XjXmXgXLXKX",
"gXfX5XR.W.fXhXhXhX6XgXbXtX2XL.-.L F G | J.!.H.E.3XsXwX>XfXjXlXvXvXvX2XR.W.6XlXvXmXqXmXtXtXLXNXKXPXvXlXNXaX2XtXhXuXcXgXkX7X>XqXmX!.P.L.4X}.m.m.m.s.m.m.I.fXvXjX}.}.6XNXmXqXdXwXP.m.m.!.G.m.>XqXhXfX9XgXgXgXjXjXLXmXNXvX9X9X5XW.4XdX>XqXm.j.2.m.].[.{.].wX4X7X/.5XR.hXlXkXqXqXQ.R.LXjXH.-.;.l.l.M.P.W.>XfX4X2XjXhX9X5XkXlXtXeXtXE.m.l.J.J.J.].kXeXqX[.>X6X2XfX6X",
"DXlXDXW.!.5XfXDX7X6X9XcX9XfXdXG.P.{.m.L 6 L ) ) i.J.c.-.J.KXLXkXkXfX6XfXHXhXfXfXhXjXhXeX9XfXlXDXgXkXUXDX>X2X6XmXbXBXvXcXR.x.R.].L.!.x.V.x.! / P.MXwX{.4XtX8X9X3XI.A.E.eX5XwXMX>XdX!.{.m.G.6XfXfX9XvXvX5XjXNXvXBXmXjX0X9XkXKXaXdX>XQ.fXfXwX{.{.{.wX>X4XtXNXqXQ.qX4XqXW.2XfX6Xx.x.3XkX4X[.>XmX{.s.l.Y.].fXqXtXKXhXgXgXvXfXR.8X}./.P.l.qXqX}.iX5X2X2X4X6XQ.J.fXlX",
"DXlXdX>X!.Q.-X(.T.-X7X7XdXDXlX7XMXMXwX] 2 7 L R R ;.[ s.wXmXmXhXjXgXtX9XsX7X7XsXyXjXgX9XfXlXlXaX XjXtXP.s.;.m.{.5X6XMXhXJ.l.I.].W.].4X4XV.2.m..XkXsXKXyX3X|.yXyXiX2X[.5X}.lXI.5X7X6XhXW.>XUXlXhXsXsX6XfXNXNXNXLXPXxXU.L.P.qX3X8XwX!.qXhXjXJ.j.P.[.U.}.hXmX].tXhXDXkXhXkXjXhX6XJ.jXfXmX7XL.7XfX6X4XwX!.s.x.GXvXvXbXbXcXhXtX|.[.hXdXwXfXtXkX[.!.W.6XLXhXE.6X5XhX",
"mXkXhXqX6XhXfX(.}.(.2X>XR.7X4XJ.m.wX>Xl.6 # L l.{.wXwX].MXPXjX6XqXhX0XfX5XlX5XvXyXgXgXgXfXfXQ.x.-.j.m.I.{.s.R G | { l.].}.}.iXwXH.J.E.fXwXL.[.mX4XkX}.J./.gXtXkXmXjXfX5XE.fX6XkX7X].7X!.>XfXQ.!.5X2X5XkXLXNXjXKXnXPXiXx.[ V.5XKXmXfXqX[.}.2X4X4X5X[.}.jXNXeXjXfX7XdXlXUXUXjXtXqX2XfXfXL.m.4XLX6XeXqX[.l.) J.sXLXNXKXKXNXhXR.L.Q.mXqXgXqXqX>XqXdX6XLXlX>X6X5XhX",
"mXfXqXlXHXKXkX7XI.R.6X>Xm.P.I.j.j.m.} c.-.] l.[.wXiXmX2X}.9X2X6XR.gX9XkXqXdXfX6X9XgXkXlXkXfXW.V.-.l.J.qXmX[.s./ | / } P.].}.fXfX}.].5XmXkX7X!.L.}.iX(.m.j.}.fXfX6X7X}.7X}.4X4X5XhXqXtX5XqXfXI.H.Q.7XW.L.R.4XjXmXPXcXwX[.J.iXgXgXsX5X9X9X(.J.E.].I.I.I.tXkXkXfX[.x.Q.>X4XfXhXKXLX{.!.P.>XqXdXlX}.qXtXhX>XG | m.L.qXqX4XhXqX].[.!.uXhXLXjX7XQ.fXdXfXmXqX>XqXfXfX",
"lX].}.hXDXfXlXsXJ.J.>XdX>X7XgX6X7X7XJ.>X[.m.P.wXm.l.V.V.x.V.J.2X7XLX9X6XhXP.HX9X7X6XgXkXkXkXlXmXwXiXhXhXhXhX4X4X[.!.[.mXmXhXfXtXkXkXhX6XfX7Xx.[ m.H.I.P.[ [ x.Q.J.V.L.5X}.I.}.tXNXkXmXhXmXKX6X2XW.[.].I.x.-.l.7XcX{.}.wXtXkXgX5Xl.c.V.R.K.| } M.z.H.I.eXeXjX6XR.m.qX4XQ.!.P.W.qXHXm.] x.].W.fXsXkXqXmXmXm.!.!.m.4X[.m.L.].4XtX4XBXiX8XI.V.R.dX6XdXdX>XqX7XqXqX",
"yX2X2X6X7X7X6XlXdX6X%XG.D.P.Q.W.m.m.x.m.!.l.l.{.].m.Q.E.L.W.!.4XMXKXKXNXdXm.[.6X7X-X7XhXkXhXkXLXLXLXMX>XiXKXKXmXmXdX>XMXkXjXkXfXtXfX6XW.-X7XJ.} E.|.6XhXP.L R J.7XK.J.}.iX5X}.E.5XkXNXtXkXLXLXKXjX6X}.6X4Xx.| [ j.j.P.m.4XjXfXb.} } j.| l.-.[ s.z.E.5XNXqXjXvX9XfXmXhXmXwXc.l.Q.m.{.!.>X!.m.5XkXBXbXGXkXaX4XmXNXmX6XL.E.hXMXNXjXNXiXqX>XR.6XlX-XqX>XhXHX4XlXKX",
"6X9X9X%XW.7XfX7X%X%XD.L 6 L s.x.s.| j.l.4X7X5XMXLXMXUXKXmXUXmXqXqX}.kXkXP.G.} W.fX7X4XlXmXfX|.4XwX>X4XMXUXLXLXIXmXmXwX[.E.}.jXNXfXgXlXfX6XfX6X%XR.9XjXmXkX!.!.P.R.I.x.R.hXKX].V.J.].}.I.K.(.|.5XfXjX6X2XiXaXx.R L 2.mX].4X].2XL.m.J.J.-.j.} L R E.uXBXLXjXNXLXvXfX>X!.>XfXQ.J.P.[.>X>XqXwX>XfXfXyXvXbX7XQ.V.[.tXgXcXgXcXPXLXtXyX4X5XR.j.R } R.6XdX!.[.qXqXKXLX",
"sX3XE.L.Q.6XfX5X7X2XY.| G G -.m.I.[.5XiXmXmXLXUXKXLXUXKXKXUXUXMXHXwX X4Xs.s.] !.dX4X7XhXHXjX7XE.qXeXkXLXPXNXmXUXKXPXLXHXjX6XtXhXkXKXKXvXjXgXkXvX9XvXjX5X[.>X].R } x.I.I.R.2XH.}.(.9X2XW.E.(.2X5X3X5XhXvX>Xx.m.4X{.[.qXwXmXqX!.!.m.m.4X2XqX[.I.}.8XuXNXjXvXvXvXE.m.P.m.!.[.>X%XJ.>X>X7XfXqX[.].6XfXqXE.R.[.L.[.U.Q.eXKXvXHX].s.l.j.!.!.x.[ -.m.4XfXx.J.R.E.wXgX",
"gXF.c.m.Q.7XtXtX6XJ.L.>XP.P.wXMXtXBXhXIXLXLXPXKXLXUXNXLXPXLXPXLXmXKXhXmX{.-.| x.Q.>X4XqXfXvXkXfXmXLXLXBXLXUXKXKXLXvX4XhXkX7X2XW.6XfXfX4X9XkXvXtXcXLXW.2X6XwXI.l.H.[.I.H.x.L.} J.).7X(.(.3X2X-X6XyX8X9XjX2Xx.x.].>X}.!.].lXMXL.Q.wXU.}..X8X|.mX XeX5X9X8XvX9X(.j.R j.!.4X%XJ.>XqX6X6XfX6X>XL.!.fXhXfXR.R.J.!.wXMX3XkXUXjXMX{.K L ) l.m.!.P.4X].5XMXJ.].}.U.U.eX",
"F.} R x.lXvXgXGXtX|.5XfXlXkXsXGXvXgXjXNXLXLXKXvXLXLXUXPXlXkXUXKXKXLXUXNXjXfX9X5X9XjXhXmXNXLXLXkXNXLXLXLXUXUXNXNXKXhX!.Q.{.[.[.l.c.I.E.).fXkXcX9XgX9XgXR.4X4X5XV.R.aXR.R.} | L R c.c.c.i.c.J.J.V.F.K.P.tXKX4X].2XtX6XW.E.m.x.4XfXfX}.fXfX).6XgXQ.W.-X7X4X8X(.|.V.R.W.4XqXqX6X2X4XfXfXaX6X2X7XaXHX[.m.J.x.!.>X[.>XhXKXDXGXJ.m.x.P.{.].m.].qXqXqX{.fXR.Q.Q.7X[.5X",
"k.j.x.[.hXdX5XtXmXhXLXLXkXfXdXLXKXlXfXtXtXhXjXvXLXLXlXfXjXkXkXNXKXkXfXkXNXvXNXvXhXNXKXNXmXmXNXvXmXLXLXLXPXLXLXPXKXLXMXtXdXmXlXP.} V.H.j.l.m.m.2XgX(.R.j.l.j.V.V.J.m.x.V.j.V.;.G R R K c R { z.l.| L G m.LXLXjXhXfX9X6X5XR.W.qXtX2XlXNX6XR.(.5X} [ z.J.{.L.[.5X|.R.6XtXtXhXfX6X6X4X5X2XQ.W.6XhXfX!.P.[.].hXmXP.G.gXcXjXH.[ x. X XE.tXK.I.zXBXeX9XfXR.>X7X6XR.I.",
"E.}.[.!.P.{.4XMXUXhXfXfX9X7X!.R.kXjXsXqX9X9XsXjXvXKXR.x.Q.7X2XKXHXKXNX6X(.}.eXVXKXLXmXhXtXmXKXkXNXNXLXLXNXKXLXLXLXPXPXLXLXLXHXW.-.m.m.-.l.m.| l.L.V.x.j.V.l.m.P.} j.V.5X XuX{.2./ | ;.{ -.4.M.z.-.R R l.hXmXjXhXfX9XfXtXqXjXhX4XR.jXmXR.j.| x.R 4 2 -.{.-.m.4X[.l.Q.fXqX4X}.4XtXqX6X2XE.2XqX7X!.hXdX4X4X>XhX{.dXPXzXE.l.| A.BXbX.XwXz.R / s.l.{.vXeX9X7X4X}.}.",
"I.].{.m.m.L.[.>XLX>XQ.Q.2XW.x.j.m.L.W.4XtXgXcXvXfXgX!.l.x.x.J.2XaXLXLX7XH.L.}.tXNXhX4XQ.[.hXfXfX4X4XhXKXNXNXLXBXPXLXLXPXKXhXtXqX[.[.W.L.dXMXm.l.R.I.H.V.|.[.{.}.Q.I.5XiX.XrXzXoX{.+XMXiXMXiXqX[. X].{.{.4XhXvXNXgX9XjXtXtXNX6X2XH.].NX}.j.6 -.m.[ R l.A.;.;.m.>Xz.W.hXhX4XW.4XhXvXtX5X6XqX4X!.P.{.qXwX>X}.>X!.MXvX6XV.l.I.H./.bXMX.XM.K 6 ] l.dXyXjXjXtX}. XuX",
"I.2X6X9XlXNXhXfXhXqXqXfX6X4XL.L.L.R.4XtXgXgXjXcXfXtXqX7X>X4XdXhX%X6XfXtXeXhXjXjXjXtXqX2XqXmXhXfX9X2X9XkXfXgXgX9XbXkXvXNXNXfXfXkXkXlXqXtXMXmXjXqX9XkXjX|.fX5X].4XdXfXvXcXzX.X.X X XwXtX8XjXgXkX6X}.eXwX[.{.8XgXsXtX4XgXgXgXgX(.5XK.} j.z.L.l.-.l. XwXMXU.P.I.].MXwXqXtXtXfX4X2XqXcXjXyXtXtX4X].].qXVXKXhXmX[.x.J.R.R.J.!.P.) ! J.xXxXXXU.v.z.P.6XU.H.x.!.}.6XzX",
"9XfXgXgXfXeX8XfXaXfXmXKXmXlXfXkXDXkXlXjXfX9X0XtX6XW.>XqX4XhXhX[.l.l.J.2XfXwX}.}.4X6XHXhXqXhX4X5XkX6X5X5X3X2X2X}.9XfXgX6XfXlX6XqXjXjXNXBXfXqXNXgX5XNXvXcXNXNXfX4XfXKXgX^./.rXcXcXyXwX6X2XsXgXvXKXhX5XyXjXgXvXcXnX4X}.6XfXkX6X(.2XH.x.I.A.5XeX[. XiX XkX8XqXhXmXqXUXmX6X6XtX4X4XiXVXLXLXgX6XfXjXhXgXvXhXW.4XJ.J.I.l.m.W.4Xx.6 6 F $.C.A. X.Xs.L F c L R m.R.K.}.",
"W.qXlXkXvX9X7X9XgXsXlXkXKXKXvXKXkXgXfXfXfXtXgXkXPXsX9X6X2X2X].m.J.L.4XjXkX6X7X7XW.].qX!.m.m.x.b.7X).U.E.}.>X|.qX6XsXsXW.7XfX}.}.5X}.6XeXhXhXtXyXvXvX9X3X9XkXGXkXaXjXvX9X/.0XcXgXfX7X7X5XfX4XgXNXcX(.6XkXhXtX7X8X[.>X[.}.tX6X5X}.U.E.[.U.eXmX5XiXPXUX9X5XLXgXfXUXKXNXhXhXjXhXkXUXmXLXLXvXjXKXNXkXjXcXwXP.l.} [ } x.L..XiXP.} } R R ;.-.m.[.-.3 3 6 } m.>Xm.x.].",
"] s.L.7XlXlXlXlXGXlXkXgXkXvXjXNXLXNXKXKXNXkXjXgXgXfXgXfX7X7XW.K.>XMXKXhXtXlXkX6XfX>XW.l.| s.} j.).(.Q.R.W.R.P.[.kXaX7XW.9XhX}.qXP.x.l.s.m.4X].vXVXvXgX-XK.T.7XsXhX%XE.}.H.2XvXsX7X[.].4XqX].tXmX7XJ.Q.6XfXhX6XtX>X6XP.I.6XfXhX5X[. X[. XVXuX8XzXNXmX2XgX2XfXBXtXfXhXfXtXKXKXmXjXtXtXkXNXLXvXGXGXbXgX].>X!.J.c.l.A.VXrX.XOX X X].[.J.iX8XzX X-.| m.!.-.G 6 | L.",
"{.L.L ] s.m.J.W.7X7XdXlXlXkXKXDXfXW.5XHXmXfXfXlXkX9XgXvXkXeX9XtXgXLXhXhXfX6XKXsXuXgX6X2XQ.E.R.j.x.E.5XlXgX).}.E.I.J.J.}.4XgXtXtX5X{.L.L.E.tX4XK.eXVXjXL.l.x.P.qXkXb.I.jX].J.[.].fX].U.[.5XiXjXNX9X9XfXgXfXqX9X9XqX7X>XwXhXhXiXyXjXtXwXjXjXeXjXNXmX}.P.}.}.iXwXwXqX2X2XtXvXKXvX3XfXjXLXKXhXgXkXNXtX}.4XjXgXgXvX9XtXhXkXkXjXeXgXgXbXyX0X0XbX0X|.l.;.-.R R ;.4.z.",
"eXqXr.L G 2 G [ } [ | i.c.c.x.J.x.c.l.x.!.lXvX5X2X5X9X5X3X3X}.}.qXkX5X5X7X5XkXfX8XgXjXfX>X>XwXE.R.I.j.I.3X2XiXI.J.V.P.4XtX5X2X5XE. X5XjXNXgXL.} z.H. X}.W.E.R.2X7XfX6X2X5X].[.MXKXfX}.}.5X5X4X%XgX9X5X6XfXtX3X5X].2X].4XhXmXjXtXfXNXtX|.5XtXhXiXm.m.J.[.I.Q.R.E.2X}.4X4X3X5X9X5X%XtXhXqX].].eXKX4X5XiXqX(.qXvXtXgXsXtXtXyXtX5X}.(.R.I.8XyXE.I.V.] | / m.wX>XU.",
"(.fX>XG.G.l.-.m.D.i.R [ | [ | x.x.R.-Xx.j.J.2X2X).7X-XE.U.2X5X}.5XtX|.4X4X2XfX9X8X|.5XtX7X4XhX4Xc.R L k.3X-X3XH.R.].].E.6X5X5X9X|.}.6XfXjXlX5XJ.V.J.}.5X5X}.K.I.x.fXqXE.tXwX].hXNXkXtXeXtXhXqX5X3X|.5XfXvXgX9X0XtXeX>XU.].wX4X>XE.jX5XU.U.]. X|.J.!.wX XR.H.}.iXfX5X5X9XfXfX9X(.}.fX6XR.P.x.m.L.x.m.E.L.J.W.hXgXyX9X8X5X5X(.R.H.J.j.[ z.I.E.Q.[.[.{.l.;.M.>X8X",
"gXsX>Xx.G.P.P.}.9XE.x.j.j.%.j.I.K.K.V.x.x.(.9X3XE.5X8X(.(.6XrXtXqXtXtXkXjX5X4X%X8X3X4XfX4X].].H.x.R | c.Q.lX}.(.I.4X].V.E.3XtXjXjXjXvXkX6XtXfX6X>XE.5XqX9X4X(.}.x.J.U.R.I.E.].E.5XfXkXhXfXhXjXjXvXsX6XtX6X2X2X9XVXNXiX}.wXqX6X6XI.5X}.].}.].}.}.}.}.hX4XE.H.6XKXNX6X2X6XtXtX2XI.Y.].R.L.!.J.x.m.!.Q.].wX[.].eXkXgXgXgX5X(.I.H.J.7Xl.j L } m.M.m.I.].P.| -.wXjX",
"3X-X5Xx.J.x.l.P.6XgX/.J.K.H.H.R.I.-X}.I.b.J.Q.9XQ.2X9XsXtX9X8X9XeXhXkXBXNXtX5X(./.wXhXhXQ.J.m.j.2.} J.} 2.6X4XK.m.I.R.L.4X5XtXhXfXlXKXKXfX9XaX6XqX}.hXjXyXgXsXsX>XP.P.L.V.R.wX{.4XtXfXfX6X6X6X6XgXfXfXhXfXqX9XtXMXBXBXNXjX4XQ.E. XwX}.|.tXqX5X}.W.E.4X3X4XE.tXfXNXtX3X4X2X}.|.W.E.qX6X6XhXqX4XqXqXqXfXiX6X4XqXtXvXbXkXgX5XE.R.R.>Xm.R L [ m.m.V.H.U.W.x.J.tXbX",
"-X).3XW.6X6X4XNXvXvX9XQ.3XyX|.E.E.8X8X(./.).2X9X3X9X9X9X8X5X5X9X8XyXkXVXvXhX9X9X8X4X}.].!.!.R.b.| } | j R x.tXE.L R -.H.gXtXtXKXjX6X9X9XeXgXvXiXiX].6XtX6X9XgXgXMXqX}.R.(.yXjXwXtXqX5X7X6XfX6X4XtX5X2X4XqXfXfX9X}.wXyXkXiX].L.R.E.5X3X[.R.U.}.}.5XE.2X5XfXtXgXgX9X-X5XtXfXfXqXqX5XgXgX4X2XW.}.tXwXqX4XW.|.tXtXqXVXvXgXtX9X5X}.(.>X>X!.l.m.W.H.V.[.5XhX6X(.2X7X",
"E.I.I.3XqX6X}.tXvXgX5X3XtXvXvXjXqXhX9X}.2X).W.].gXsX9X5X2X|.5X9X5XyXvXgXtXgXgXgXNX}.H.R.4XfXkX5Xx.[ c j R { L. Xz.z.J.wXjXfX6XtXyX3X2XyXgXgXrX|.6Xb.J.R.E.2X5XfXqXjXtX5XcXNXcXiX6X5X7X6X9XfXfXhXNXfXQ.m.m.R.}.(.P.E.|.9XkXuXeXeXH.J.I.I.x.z.I.E.6XW.R.2X2X8X6X2XR.K.R.}.4X3X].E.2XsXkXgX9X5XsXvXjXmXjXqXtXkXjXtXjXfXfXeX9X5X8X5X5X(.qX7XhXNXhX5XtXhXtX}.R.R.2X",
"8X.X XtXqX5X2XlXGXlXvXLXvXfXyXvXjXhX9XtXgX3XW.tX3X9X9X9X8X6X}./.iXjXBXtX8XfXiXjX XH.J.>X6X6XfX|.H.} l.m.eX].E.5XR.R.J.E.E.fXtXtXW.R.(.9XgXtXiX3XgXb.z.K.Y.K.L.R.kXjXuXjXyXcXuXuX5X7X7X7X%XR.}.tX(.5X5XW.W.4X4X(.L.}.6X9XcXuX XL.H.2.2.J.V.l.H.I.W.R.L.(.R.(.T.I.).I.E.I.x.x.J.R.L.R.9XjXgXyX0X9XtXfXfXgXjXyX9XjXfXjXkXgX3X2X3XgXbX5XNXlXlX6XfXgXjXfXwXlX6XR.R.",
"I..XuXyX9XgXkXgXjXyX9XeXgXjXgXtXeX9X9XtXgXkXvXkXfXtXtXtXyX8X|.XX0XcXgXgXtXtXiXeXtXqXfX2X4XtXE.E.(.8X8X8X8XgXVX|.U.I.I.}.eXtXwXtX).2X3X|.9XuX9X XR.} [ -.l.x.L.z. XiX.XrXyX8XuXVXrX|.}.R.V.H.L.A.}.R.tX6XjXcX(.2X2X5X}.tX5XqXhXl.m.x.2.j.C.H.L.J.x.wXm.l.s.wXM.L.U.z.m.m.m.m.>X].|.4X|.2XqX}.].kXhXfXhXhXtXqX5XqXtX9XhXjX6X5XtX5X2XQ.4XjXfX4X6XfXlXqX4XqXR.m.H.",
".XiXkXcXyX9XsXgXgXgXfX9XtXgXgX9X5XeXeXgXkXgXlXgX6X6XtXeX8X.X|. XyXjXcXgXfXfXfXtXlXfX9X3X5XtX8XtX8X8X3X9XtX8X|.H.}.}.}.5X4X5X5X5XvX).R.|.8X|.|.|.x.l.} [ R } H.J.V..XyX8X8X0XjXeXuX5XH.j.} l.V.V.V.J.|.kXUXLXE.R.%XE.L.H.J.].iXm.;.} | z.W.5X}.P.m.}.}.L.N.qX(.tXjX-X2XH.m.!.qXE.].qX4XW.7X}.W.5X5XtXtXhXtXtXhXjXjX4X4XgXfXjXtXE.5X(.2XtX5X>X].7Xm.x.[.L.V.L.H.",
"mXrXyXkXfX2X}.tXtXjXjXtXtXyXgX9X8XtXgXvXkXgXgX9XW.].3X5X.X}. X8XyXyXfXtX9XfXtXiXtXtX4X6X5X4X5X5XW.tXuXwX}.4X}.x.}.5X6X5X5X5X5XeXW.x.k.H.].E.}.8XW.].L.x.k.x.H.k.;.L..XiXkXVXKXjXrX|.J.j.l.b.V.J.x.k.J.].KXvXI.I.J.L.W.L.x.P.tX5XV.L.J.V.H.I.}.|.|.0XLX3X/.9XeXgXgX9XeXqXfX4XqX(.l.R.].].qXjXfXqXtXkXNXhX6XqXtXtXfXtXtXgXfXtX9X}.fXtX6X6X2XK.m.J.J.H.R.2XW.E.|.",
"kXtX9XgXtX|.-X9X9XjXcXtXtXgXgX9X5XgXvXvXcXgXgX9XE.E.|.|.5X|.0XyXfXfXtXtXgXtXtXtXfXjXtXgXtX5XtX}.V.3XtX5X}.5XmXwXtXiXiXeX5X5X5X4XH.J.J.R.wXmXmXjXkX2XJ.H.].}.E.J.x.P.E.hXvXtXtXgX0X3XI.J.E.}.].|.U.V.x.I.fXfXW.sXW.I.].W.E.5XjXtXmXmX/.H.I.}.tX9XNXyXxXI./.tXtXeXgXgXfX4X6X}.}. Xx.R.4X].qXhX5X].qXjXNXhXhXkXNXNXkXvXvXjXtXtXtXtXyXkXgXgXhX6XW.2X7X|.I.3X6X(.9X",
"jXtXyXjXgXsX9XfX5XgXkXgXfXjXyX9X9XvXvXvXvXjXjXfX5X3X3X5X8XtXrXcXfXqX6XtXgXtXfXfXgXlX6XtX5X6XNX5XtXtXmXNXwXI.].qXjXkXkXiXiXjXeX3X2XqXqXtXjXKXNX6XqX}.J.I.|.E.}.|.}.E.H.}.tX7X6XvXgXgXE.L.}.fXfXfXqXE.I.5XhX9XE.6XfXL.J.(.6XtXeXgXeXhX5X}.wXeXtX|.8XwX4XU.}.qXm.l.R.7XL.2.-.I. X}.6XtXqX2X2X2XW.].fXmXNXNXmXLXLXNXNXNXjXgXjXNXkXjX9XcXvXvXLXmXfXlX6XW.tXtX9X(.V.",
"yXgXgXgXgXcXjXgX5XeXjXjXgXhXgXtXgXvXvXvXjXvXjXyX8X5X|.8X8X9XgXNXjX6X5XtXjXfXfXfXtX9X5X6X3X5XiXE.tX6XeXmXhXwXhXtX5XwXeXhXjXvXhXeXqXtX6X9X6X4X}.Q.Q.6X4XtX6X]./.E.}.}.I.}.tXjXvXvX0XvX5XK.U.fXgX(.tX}.3XhXtXE.I.E.m.j.l.R.6X9X9XcX5XtX5X}.4X|.5X8XI.].4X}.4X}.| R l.J.x.s.l.!.4XeXtXqXtXfX9X9XfXfXkXNXNXkXkXKXlXfXeXkXkXjXjXkXNXNXvXNXBXNXKXgX5X5X6XE.R.].4XE.x.",
"gXgXlXjXgXkXgXvX9XtXyXgXgXgXtXgXlXvXvXgXjXjXhX8X|.|.|.5X5XeXcXNXhXqX4XtXjXiXsXlXfXR.}.9X5XtX5X|.eXjXfXiXwXiXjX4X/.[.|.tXfXhXhXhX5X3X2X5X6X7X%X(.R.W.W.}.5X5XtX}.}.eX5XwXjXgXjX0XgXgXhX}.[.2X2XI.}.E.}.tXW.I.(.2Xx.j.} I.yX9XjX0XjXeXL.I.5XyXjXiX[.P.I.E.}.5Xm.M.V.K.E.tXwX].T.).(.(.6XjXkXvXkXgX5X6XaXfXfXlXfXlX}.gXkXtXtXfXjXLXBXNXKXNXNXNXNXfX7XL.| } V.L.|.",
"vXkXgXkXvXgXvXNXgXtX9XfXgXeX9XjXgXvXkXgXyXuXeX|.|.5XeXyX9X9XyXNXDX6X4XtXkXgXfXkX5Xx.J.E.W.4X5XjX9XeXtXyXqX5XjXiX5X5X5XtXiX5X5XeXtX6X5X9XfXfX5XQ.E.R.R.}.tXtXhX|.U. X|.5XtX0XcXbXvX6XtXMX}.R.R.R.H.x.V.R.V.J.2X7X!.Q.L.(.(.I.0XjXeXtX X5XtX9X0XyX].x.I.8XyXjX2XU.V.H.E.jX5X7XU.F.J.K.E.3X5XgXvXgXfXfXfXfXfX5X6XfX6XhX5X}.tXjXjXNXBXVXVXVXjXNXKXjX>XP.z.} x.Q.I.",
"gXgXjXgXyXgXjXvXNXgXQ.6XkXqXtXhXsXvXvX9XeX2X3X(.5X5X8XtX9X9XtXvXhXtXjXNXkXfXgXhXrX[.U.U.wX5X[.uXiX|.qXqXNXmX[.wXgX5XyXbX6X3XhXhXtX6X6XsXfX6X6X5XU.K.I.].9XgXcXcX|.).3X9XyXjXgXgX5XE.{..X|.E.E.3XE.H.s.-.J.J.b.E.(.yXiX|.!.z.m.qXE.[.|.tXiXjXkXjXmXhX9XfXgXlXgXsX6X6XE.I.4XK.j.V.x.j.x.}.).J.E.lXtXjXiXNXjX5XiXiXeXtXjXmXkX5X.XkXNXVXNXcXvXvXcXBXtXwX5X XwX.X/.",
"vXgXgXjXkXjXjXvXjXvXW.c.Q.mX9XtXvX2X(.K.(.|.3X2X3X5X5X9X9X9XyXjXtXjXKXNXtXtXfXtX5XwXE.}.iXNXjXjXmXL.U.qXNX[.l.I.4XkXKXjX(.E.}.hXtX5X2XaXfX9X5X}./.U.(.6XlXkXcXgXgX9XtXjXgXcXgXvXE.H.L.R.}.4X5X8X5XeXE.P.P.x.x.I.uXjX5X}.A.} { m.9X9XyXhXvXvXvXvXvXjXyXgXkXvXvXlXlXhXqXqXjX}.m.H.V.z.x.K.I.J.K.!.tXKXKXjXmXVXNXiXjXmXeX5XeXtXtXyXcXvXVXvXcXjXvXcXkX5X[.4XiXeXyX",
"KXcXgXvXvXvXjXcXjXNX5X} j.m.4XfX).x.x.V.|.9X8X|.3X5X8X6XeXhXjXjXtXjXNXjXjXNXjXE. XmXU.E.U. XMXuXNXE.I.I.wX}.m.P.E.6X5X}.5XR.x.x.4X4X4X5XE.I.I.E. X5X6XjXkXkXlXcXvXkXkXbXvXvXcXvXgXiXiXtXyXgX-XJ.l.P.4XtXtX}.}.hXgX9X4X4XR.l.j.I.uXhXjXcXjXcXjXjXuXgXhXjXgXvXvXkXmXjXkXNXKXfXR.E.H.E.9XeX|.(.4XtXE.fXmXjXVXLXkXhXqXmXjXeX8XtXyXjXvXvXVXNXvXcXvXvXyXJ.;.z.|.cXBX",
"jXgXjXgXgXjXgXjX8X8XlXhXG.L H.H.c.%.H.}.tXcX9X5X2X9XtX9XgXvXvXgXjXjXfXtXjXkX].k.m.eXqXhXR.}.4XqXtXtX}.V.U.qX X[.}.6XyXgX}.z.} x.E.|.7XQ.L.J.I.E.8XyXjXkXgXgXlXgXvXgXgXgXvXgXgXbXjXjXvXkXkXbX3XK.;.-.V.3XyXiXiXhX4XeXtXeXtXwXwXmXyXfXyXyXyXgXuXgXyXgXjXjXgXgXkXvXvXfXkXvXmXmXwX5XE.}.2X}.4XgXjXqX5XtXjXfXjXkXfXLXiXjXjXkXtX5X9XNXvXvXvXgX9X9X8X5X|.}.U.tXmXeXcX",
"tXgXjX9XyXNXjX9XbX|.tXlX!.6 } 2.%.x.5XfX9XtX5XyX|.9XtXtXgXvXvXgXhXfXkXjX6XW.V.j.{ m.|.wXJ.{.I.eXvXhXtX5X5XwX}.4XhX5XhXNX2XP.!.[.L.L.I.E.2X4X4X4XfXgXjXyXtX0XfXgXgXyXyX9XrXrX0XrXuX9X8XyXgXgXjX3X!.A.J.E. X0XuXtXtXgXiXgXjXjXhXjXtXyX9XgXyX0XtXgXgXgXcXgXgXgXcXvXcX9XvXvXjXkXfX6XjX2XE.I.E.wXiX5X4X6XqXtXhX5XR.W.mXiX4XtXjXhXyXjXjXgX9X|.R.K.H.K.U.wXrXjX5XE. X",
"gXgX9X5XgXKXjX|.K.U.2XJ.P.L 4 j / M.E.9X3X(.E.8X2X8X9X9XfXvXcXtXjXgXkXNXtX|.Q.I.V.I.wXeXL. X5XBXjXiXjXmXhXqXqXeXhX|.5X5X].7XwX{.x.C.R.7XfXkXgXyXyXyXzX0X.X8X8XyXyX0X0X0XXX).XXXXzXyXyXjXgXgXjXjXmXwX|.8X0XjXVXNXbXjXyXkXgX0X8XtX9XyXyXyX9X9X0XyXjXgXcXgXvXgXlXgXcXyXvXvXjXjX4XW.eX3X4X5X}.}.|.|.2X}.[.5XqX}.E.V.L.}.5X5XjXVXjXeX8X0X5X(.E.K.K.I.{. X|. X XeXtX",
"}.(.W.(.}.-XE.I.K.C.x.[ j.G # 4 R x.x.W.5X/.Q..X3X5XtXtXyXjXgXgXvXyXgX9XE.R.5XgXE./.yXuX X|.5X|.5XeXeX5X|.qXtX5X4XhXhX2XI.L.L.J.K. X0XgXyX9XgXgXtXjXiX.XXX|..XXXrX0X.X0XXX_.oXXX).XX0XcXyXyXyXyXcXyXiXiXtXeX9X0XbXsXuXcXgX0X0X0X9XyXgXyX9X0X9X9XxXgXcXcXvXcXcXgXyXgXbXjXfXhX2XW.(.K.L.].wXwXE.V.L.V.l.V.l.j.I.L.x.}.hXyXgXjXfXyXiXeXyXiX0X8X5X.XV.U.vXyX0X5XE.",
"V.x.b.J.V.z.l.b.).V.} | x.L 7 7 2.V.2.R.gX2X3XcX5X9X9XgXgXjXkXgXtXkXjXK.} } x.5X|.8X8X0X/. XcXyXcXjXtXtXtXeXwXE.qXtX/.E.2X5X[.].iXyXuXyXgXgXgX0XtXuXrXXX_.XX`.).).XXXXXXXXOX_.OX8XrXxXrX0XrXuXyX0XrXiXqXtXeX0XxXyXcXcXyX0XgXcX0XyXyXcXgXjXyXzXcXyXyXyXyXjXgXnXsXyXcXvXtXgXkX6X9X(.W.|.wX X X X XP.A.V.wXH.2.W.4XeXiXhXhXiXtX9XgXcXVXBXBXVXuXuXuX}.I.rXjXVXVXE.",
"x.j.j.j.l.K L } 2.! -.[ L 7 . 6 l.A.U.gX|./.(.tX5X8XiX|.8XNXgXkXjXjXgX(.{ 6 L 2.P.+XVX X.XgXfXvXNXiXjXU.cXjX}.L.5X9XL.x.L.}.|.fXjXlXjXtX8X5X|.8XjX8XoX~.`.`.oXoX^.oXOXOXoXXXXXXXyXyXgXxXyXyXyXgXrX8X8XrXrX8XrXbXcXzXyXgXyXyXxXyXyXyXxXxXzXrXyXrXXXxX0X0XbXgX8XrXuXyXyX9X0XjXjXyXjXU.].mX4XI.eXVX}.L.U.tXhXwXtXjXiXtXyXeX5X}.tXBXBXuXVXNXuXjXBXVXcX XeXuXNXcXyX",
"L d d 5 d c { E c ! $.K c % ; R l.V.V. X8X0X8X8XyX5X5X}.5XVXjXgXyXjX9X6XL.R > R A. XeXiXjXkXtXjXiXR./.U.rXeX|.I.].fXiX.XyXiX5XfXE.U.3XuX Xk.b..XyX.X_.oX~.oX_.~._.~.~._._.oXoX.X0X0X0XyXnXyX0XxXrXrX.X8X0X.X0XyXzXzXxXyXyX0XyXrX0X0X0X0X0X0X0X8X.XyXyX9XgX0X8XbXeX0X0X8X0XyXgX0XvX5X}.eXjX8XiXuXuX.X8XiXjXuXiXtXeX5X8XtX8X8XiXBXLXVXNXiXeXeXuXjXMXMXLXBXuXcXgX",
"5 4 6 s ; s <.^ c Y ~ $.3.5 L 3./ z.C.3X8XrX9XeX(.U. X X X3X5XtXvXVXvXyXA.c > K 2.4.V. XkXVXtXvXE.U. XK.V. X Xm.-.P.|.iXVXuXyXuX^./.rXzX.XK.^.0X8XXX^.~.^.oXoX_._.^.oX_.oXoXXXXXXX0X0X0X0X0XrXrX.X.X.X.X8X.X.X0X0X0X0X8X0X0X.X.X8X8X8X8X8X.X.X8X3X0X0X8XuXeX8X5X8X8X8X|.8X9X0X3XeXVX5X|.iXeX.XiXiXiXyXiXeXeXtX}.8X.X.XwX5X5XeXzXuXMXBXVXeXiXuXiXU.{.yXiXeXyXfX",
"%.5 5 s 5 s x k 2.! ~ 3.v.d K | R N. XrX8XyXeXiX/. XeXeX XE..XvXjX8XNXeX;.c R 2.A.U. X XyXVXeX5X}.I.U. Xz.{ { z.z.U.wXiXrX8X X.X)..X.X_.oXXXXXoXXX_.^._.XXOXXXoXXXXXXXXXoX).XXXXXX|.|.XX.X|..X8X.X0X.X0X.X.X8X8X8X.X8X3X.X0X8X0X8X0X8X.X8X8X8X8XsX0X0XrXrXeX8X8X8X8X.X8X9XyX9X8X XvXeX X X/. X.X X.X0X8X|.8X0X|.iXeXeXrX.X X XeX XuXBXBXcXVXcXrXA.V.U.5XtXtX9X",
"{ s j > k n x n E x x c ! c c L / U..XiXiXzXrXiX0X/.U.^././..XVXVXzXBXBX{.A.oXMXuXVXBXcXiXjX5X(.eXyXtXwXH.;.2.U..XMXcXuXyXrXXX).XXoX^.XX_.^.^.XXoX_.~.^.`.XXOX.XXX.XOXXX).XX.X.X0X.X.X.XXX.X.X.X.XrXrX0XrX0XyXrX8X8X8X0X8X0XyXrXxXrXyXrXxX0XyX0X8X8XrXiX.X.XrXiXyXyXiX0XuXcXjX9X8X0X.XeX.X X X/. X.XyXzXyX0XuXcXuXzXcXzXrX8XrXuXrXVXVXzXVXVXcXrX8X{.eXkXNXjXeX",
"j > > > x :.n n K ! E > ! / % 7 E Z.rXcXzXbXrXyXyXC.%.3.Z.oXzXuXzXBXVXVXBXjXiXMX X}.iXkXiXrXqXeXeXPXBX X/.A.U..XuXMXzXzXzXcXbXrXXX_.oXOXrXXXOXxXoXoX^.oXoXoX.XXX.X.XrXrX.X0XyXxXxXyXrXxXrXxXxXrXyXyXzXzXzXbXzXbXcXzXxXxXxXcXxXbXbXbXcXbXzXbXbXzXbXyXxXcXvXBXvXuXuXuXxXuXzXbXcXyX0XeX8XzXxXXX.XoXrXeXuXcXyXrXcXBXzXVXcXzXzXrXiXrX.XyXuXzXCXVXrXeXjXNXPXBXjXVXcX",
"7 x :.8.M.B.Z.MX.XiXoXB. XV.4 4 E oX+XcXgXbXyXzXyX^.k.V. XzXCXzXzXPXPXBXPXiX}..X X^.eXiX8XrXyXeXrX8X5X}.{.z.^.zXVXVXVXbXBXBXBXzXXXXXXXOXxXCXzXxXOXrXOXrXrXOXOX+XrXzXzXzXbXbXbXCXCXVXbXzXbXbXbXbXzXVXCXVXbXbXbXbXbXVXbXBXbXbXCXbXVXbXbXBXbXVXbXVXCXnX:X:X;X:XGXbXzXzXzXzXcXbXcXzXrXxXoX).rX.XxX+XiX8XiXcXrXiXVXVXzXrX.X.XrXrX.X.X X8XrXzXBXVXrXrXuXVXPXBXzXbXbX",
"5.+X+XCXMX+XCX+XzXCXCXCX+XH.L j M.MXwX5XgXLXjXuX9XyX.XzXzX.XzX.XzXzXCXPXLXeXE.E.U.{.eX|.}.iXkX.XjX8XiX}.H.2. X+XzXVXPXPXBXLXCXzXOXxX.XOXOXxXxXxXxXzXCXzXxXxXrXOXxXbXCXCXbXCXbXVXbXbXbXbXbXVXCXBXVXCXCXBXVXVXbXcXBXbXVXbXBXBXBXBXBXVXBXBXVXVXVXbX0X).T.i.D r.T.bXcXVXBXVXbXvXBXBXcXzXb.4.XXCXrX.XzXiXuXrXiXuXNXvXXX X^. X.XxXzX.XXXrXrX8XzXrX.XzXPXvXBXPXbXVXbX",
"+XOXbXbXbXBXCXCXCXnXCXxXxXoX4.4..XU.Z.U.8X{.z.;.C.OXxX.XCXOX~.+XxXbXBXBXBXiXoXoXeX[. X X[.N.A.+XiX+X.XeXeX{.{.MXVXcXVXPXBXbXVXzXzXzXxXxXOXrXOXxXxXxXCXCXbXCXxXxXxXCXCXPXbXVXVXzXCXxXzXCXCXzXCXPXBXPXCXCXPXPXBXbXLXLXBXBXPXLXLXLXLXLXVXPXNXLXIX:Xi.~.C.[ H D q.y.:XvXBXNXGXGXbX+XzX X:.R M.[.Z.A.+X.XCXuXeXVXyXzXiX.X.XuXVXzXuXVXVXBXrXrXxXrXuXVXuXBXBXVXbXBXBX",
"+XOXXXxXbXzXxXCXCXCXCXbXxX.XU.C..XU.b. X Xx.K j 4. X^.b.Z.MX+X+XxXyXcXBXNX.X X.XiX+XoX X XU.{.oXMXMXeX.XwXP.-.M.VXbXCXBXCXCXBXzXCXBXBXCXCXxXzXxXxXxXnXxXXXXXxXxXxXxXxXbXBXVXbXbXVXVXbXCXzXcXbXPXGXBXbXbXCXCXVXPXBXBXPXLXLXCXCXVXVXVXVXIXPXvXbX_.D i.3.D Z H D y.i.;XGXcXbXbXBXxXuXC./ ^ A.A.<.<.oX+XuXzXrXBXCXCXVXVXuXVXVXVXVXCXCXCXxX.XiXrXcXVXVXcX8XvXPXBXVX",
"oX+X+XiXCXxXoX.XxXCXzX8XXX|.8XI.+XBXzXxXU.^.2./ 3.6.1.~ 1.oX+XxXVXxXeXeXiX X XiXeX.X{.Z. X.XuXiXVXBXVXMXCX[.M.P.LXPXvXcXxXcXzXzXCXPXPXCXMXrX.XxXOXOXxXXXXXxXbXCXxXzXzXcXBXPXLXPXcXBXCXzXbXcXcXbXBXPXBXCXCXPXBXPXVXBXPXPXPXCXLXCXPXPXMXVXvXPXPXn.C 1 6 N Z C 3 Z Z y.a.GXCXMXMXCXPXrX XoXPXCX{.>.3.N.K.uXVXzXuXzXCXCXCXzXrXxXzXVXMXVXzXzXzXzXcXiXrXcXU.A.U. XNX",
"1.Z.Z.B.oXxX XoX.XiX.X.X8XuXeXz.;. X.XA.2.B.N.4.T l l s v >.8.{.iXxXeXeXyXiXiXrXiXiX XoX+XxXCXPXCXPXPXLXUX Xm.[.PXBXcXuXjX0XuXCXBXPXBXCXVXCXCXPXCXCXrXrXxXxXxXxXzXCXCXcXBXbXbXbXBXCXPXCXCXBXBXbXbXBXBXBXLXBXGXKXBXBXCXLXVXBXLXLXBXPXCXPXGXPXPXT.D 1 5 A V B 1 Z 3 Z D *XVX+XCXPXVXNXCXCXCXPXxX5.I { 2.eXCXVXrXrXzXCXzXrX.X.XzXVXzXCXCXzXVXVXbX|.U.+X4.! E { ^.",
"z.{.A.5.C.+XrXXXiXzXrXzXcXeXH.L c / ;./ / / I c c > k c c R :.:. XoX+XiXCXCXxXOXrXVXvXuXOX+XjXvXLXPXCXBXPX}.M.+XVXVXcXNXVX X XiX0XrXrXzXzXVXCXCXPXVXvXcXBXKXPXPXLXPXBXBXCXVXVXzXPXBXbXPXPXCXBXPXPXPXBXVXBXLXBXPXPXPXPXbXLXLXUXLXBXVXCXPXPXVXPXbX` Y %.n.F.n.` 6 L A , D D.0XPXBXPXxXCXCXxXCXCXZ.x K I K.VXzXxXzXCXCXCXrXxXVXCXCXCXCXMXzXxXMXVX.XA.A./ c 6 k { ",
"cXCXoXC.U.oX.XVXPXPXcXzXzXiXV.R R / ;.z.A.A.A.A.{.A.{.A.B.oX{.{.~.~.~.oXOXoX+XOX.XbXGX3X.X+XzXvXCXNXVXBXPX+XA.{././.oXrXrX XU.U.|. X^.U.C.A.U./.}.}.eXiXjXeXqXiX6X(.|..X.XrXxX0XxX8X8XxXzXrXyXvXMXBXNXuXBXBXVXVXbXvXGXPXPXPXPXLXPXPXBXBXmXPXBXn.L I &.p.n.n.#.) *.Y 3 < D n.bXMXxX^.oXxXnXCXzX~.I k c 2.iXzXrXzXzXCXzXzXzXCXCXCXzXzXCXCXxXzXVX X.XU./ k > k / ",
"bXxXeX.XrX.XiXCXVXVXcXyXVXPXuX X+XMXMX.XoXeXiXVXzXOX+X+XXXnXOXxXB.0.8.0.0.~.~.~.0X:X;X;X0XiXiXMXVXzXBXVXxX.XZ.N.6.6.C.^..X.X X XXX.XXXU.b.z.N.K.Z.V.C.K.C.z.2.{ 3.2.3.z.2.z.R.J.b.b.C.Z.B.v.z.N.z.m.z.x.V.U.Z.^.Z.^.oX.X).(././.{.iXiXuXMXLX/.d 1 = h A S P &._._.n.L 1 1 D k.^.B.B.~.OXxXCXxX^.<.c k / rXCXzXzXOXMXxXxXxXzXzXzX.XxXzXCX+X+XMXeXMXU.E j E >.N.",
"CXbXCXVXzXxXzXVXyXcXPXxXCXCXMXCXzXxXoX^.3.z.3.V.z.M.6.6.N.~.v.4.9.7.7.7.0.0.~.0.XX_.*X:XkXoXZ.A. XrXPXVXxXxX+X X~.Z.Z. XoX.X.XA.~. XrX.X XZ.U.^.^.B.3.3.v.4.<.O.O.^ <.2.E [ c.D.! %.3.3.$.~ E E L c 6 ; s ! O.1.>.4.B.N.4.$./ ~ / { } V. XeX0Xp.` ` U U p.`.OXnXnX`.a.S $ , L <.1.7.~.oXOXbXCXxXN.z > c U.rX+XzXiXxXxXzXzXzXxXOXxXxXxXOX XZ.NXPXLX2.j E A.^.B.",
"BXPXjXbXcX8XzXrXxXbXrX.X.X|.{.P. Xl.! K c d c c s 6 s k c c 5 5 5 K K k c E K c R R | D.z.:.k j K ;.2.8.+XCXrX-XsX9X|._.K.'.U.2.<.{ k.U.Z.4.$.<.3.3.1.<.1.3.4.4.v.2.| $.@.H h.1Xp.' [ } -.} | ) [ | ] L G R [ { $.O.$.7.1.W b b k % > 6 K { 2./ ` '.'.`.`.nX`.`.nX`.`.&.1 1 ; W m v n ,.8.C.oXzX4.> 4 6 m..X+X+XbXcXcXCXCXCXCXCX+XMXA.~.VXzXVXCXmX;.> E B.7.,.",
"bXxXOXbXCXxXxXrXOX^.4.{ R k > c L s ; ; 4 ; * * % % % $ $ % % O * . O O % % % > j c V L $.5.1.9.1.>.E I z.G.G.*XF.p.v.3.$.+.O.*.[ K R } j.2.} | r.%.r.k.x.c.c.n.3.2.} { { w.f.=Xi.| | } { [ ) ) [ ' r._ ( ( [ | %.} %.z.b.k.2.k.R 6 4 % 7 ; 4 6 #.F.`.`.`.nXnXOX`.OX`.'.` 3 > 9.7.+.m b b +.v.'.N.I ; 7 [ .XzXCXOXOXxXxXOXxXCXnXxXZ.N.~.xXCXCXCXMXE - m 8.0.7.",
"^.`.oXB.~.XXoXoXXXB.O.3.C.<.: ; : s p * % % . O @ @ # @ @ @ @ @ O o $ o O : n +.9.6.} } V.oX~.'.8.oX7.T G L ` a.D D [ x v E { 3.{ [ [ ` ) ` ' ` [ } } s.j.%.} &.{ c.s.2.r.e.g.=Xr.r.| { } } [ ) V ( ( F C G G G ) _ | r.j.| ) ) ) ) ( G V , % 5 A Y p.'.`.OXnX`.`.`.`.'.) 7 5 7.~.0.7.9.O.7.0.7.^.3.> . c /.OX~.`.`.OX~.~.8.~.oX~.>.~.CXCXCXxXCX+X+.b 9.0.0.~.",
"7.B.8.+.+.7.8.~.~.~.9.7.~.v.x s +.8.8.O.K ;   . X o O O X o @ X   . #   * O.8.9.*.'.F.D.c.z.n.B.'.B.b + 2 B A =.=.#.n.` | s.' e.| } | [ ) ) ' ( ! } } R ) ` | | ~ r.j.i.r.t.#Xg.z.k.` ) ) ) ] | L L F B G F C G ( F L L ( ) ) ( F F _ ( ( V * % p S #.n.a.`.OX`.`.'.'.7.1 % Q 7.7.,.+.*.*.+.*.7.~.B.E > > W 9.7.~.~.~.0.7.7.7.9.E k 8.OXoXOXOXOX0.+.m 9.9.*.9.",
"9.9.7.9.*.,.9.~.~.~.8.O.1.O.v E ,.8.6.O.v > % 7 % % % % % 7 7 % 7 % $ 7 k 1.8.*.;.! ) ( _ s.s.R ' ' G B G J A a.=.#.p.y.r.r.| r.c.c.i.s.r.} } | ` r.| G V L ] _ [ | } } r.t.#Xr.x.m.l.[ ) L R | | | | ( ) ] F F F L ( R R | } | ) G C H ( ] L + d o.'.`.'.'.`.`.'.'.'.'.K 5 +.9.7.+.+.+.+.O.9.8.9.7.E x c m 9.8.0.9.0.0.0.8.,.m n M m 7.7.0.~.8.8.n y m ,.m ..",
"B.n.~.C.B.~.~.~.^.oX~.B.~.B.3.3.7.8.9.1.<.{ ^ 2.<.$.:.;.<.5.1.<.{ ;.4.3.4.A.B.9.;.G G N 3 N G j B C F ( ' H q.i.i.i.D.y.q.y.s.c.c.c.z.x.l.l.l.M.T.m.i.' ) ] [ s.j.c.b.m.d.g.*XJ.V.I.!.!.J.x.c.l.x.x.m.x.l.l.l.l.x.J.L.E.{.I.J.V.c.| | } } G.s.] ` &.`.nXOX`.'.'.'.`.`.nX).i.%.B.8.6.6.B.B.B.B.B.B.3.^ O.N.N.~.~.~.~.~.~.~.~.~.B.^.B.B.~.+X+X~.~.~.>.M E ,.+.>.",
"K.^.C.B.C.^.oXZ._.^.^.^.K.v.4.V.^.^.^.^.^.^.K.Z.C.C.C.C.Z. X^.Z. X^.oX^.).8Xm.| ] R G 7 3 N N 7 3 J 6 p 0 h h h 5 D ) D _ y.i.' | r.j.c.c.D.Y.Y.].E.!.J.J.H.P.I.T.%XsX%Xd.<X;XiXgX8X.XwX9XfXfX6X2X5XiXeXqXtX6XtXfX6X8X5XwX8X8X5X>X].qXqX].dX<X@X-X).'.'.'.'.0.'.'.`.:XIXIXNX8XxXXX^._.^.oXoX_.^.C.C.C.K.+X XoXXX+XXXOXoXoX_.oX.XoXoX+X+XOX.XOXXX+XZ.N.N.B.~.~.",
"K.^.K.^.U.V.^.^./.^.K.K.K.b.z.N.C.K.(.).^.^.^.^.Z.^.K.C.Z. XXX|.|.oXXXOXXXJ.| ( G / K # 3 < 7 7 3 6 a .. . . .X... .u r e t g 0 A 1 B C A _ e._ _ r.r.s.Y.&X;X;XsXpX;X*Xg.1XZX.XcX8XeXeX.X8X9X7X6X3X6X2XwXtX5X3XaX9X5X9XgXgX0XsXwXqX5X5X4X,Xd.d.(.0X'.a.*.*.*.'.'.`.PXIXUXIXIXBXbX_.K.^.).).oX^.U.)././.|.8X3X8X+X.X.X.XoXXX.X.XrXrXzX.X X8X5X8X X X XXX~.+X+X",
"/.Q.^.T.U./././.E.)./.U.K.b.V.b.K.^././.E./. X|.^.^.U./.^.). X|..XeX5X9X|.n.! L c c j 7 7 3 J N N 6 d i u u u  ....... . . . . .r X.X.X.X.r e e = p h p A ` y.D e.f.g.S.=X=X*XaXaXaXqXqXtXiX8X.XqXwX5X3X6XsX-XT.F.p.i.p.n._.).sX+X7XdX}.-X*Xg.u.g.i.y.#.#.a.a.'.gXPXIXIXIXIXIXIXIXUXkX|.^.).|.Q.U.^.).|.|.8X.X|.|.8X8X|. X X|..XXX.X.X X|. X/.^.^.U./.).^./.).",
"/././././.)./.).(.}.|./.I.K.K.K.K.^./.).)././././.E.Q././.|.|..X|.5X5X8X3Xb.! K j A R 3 3 3 N N L f i i e e i u r  .r  .r r  .r X.X.X.X.X.r i u  . .u u u i u e q g S S D ) ) ) r.c.D.Y.%X,X,X&X>X>X6XsXsXT.i.i._ ) y._ ` Y p.T.7X;X&X2XFX1Xu.q.u.g.=Xa.#.a.'.`.GXUXIXIXIXIXIXIXIXIXUXgX)./.).(./.).|.|.|.|.8X8X8X8X|..X|.).).|. X|.oX|.)./.)././.U.U.Q.^.Q./.",
"}./.)./.(.(.|.|.|.|.(././.^.I.K./.Q./.(.(.|.).)././.^.).). X|.8X X5X3X5X3XK.{ K A d F N 3 3 J G S g X.r e 9 e e e r u r r u r r r r r r r r r r r r  .r  . . . . .X.r t i a g h p a A T ` | r.r.s.D.*X&X=Xy.H q.Z D.ZX;XF.i.' ` V.-X).sXJX=Xy.y.g.=X:X;X:XGXnXvXIXIXIXIXIXIXIXIXIXIXIXUX2XU.E./././.).(.). X|.|.8X|. X|.)././.|. X X.X X X^. X X/.U./.U.U.U.).",
"(.|.).|.}.|.).)./.(.)./.Q.T.^.I./.Q./.).|.(. X/././././.).(.|.|. X3X8X3X-X/.%.L L 6 G 3 7 3 j R g X... .u i t e e e e u u u u u e e e e r r r r t 9 t t t t  . . .X.X.r .... . .X. .u i t i t h 1 p A ) ( Z H q.H e.r.s.D.@Xp.r.@.'.:XPXFX=Xg.ZXd.=X&X:X:XsXGXIXUXUXIXIXIXIXIXIXIXIXIXGX}.K.U.R.U.^.^.Q.U.U.U./.|.(.|.}./.^./.|..X.X.X|. X/. X).).)././.)././.",
"). X(.|.|.|.|.|.(./.E././.T.U.K.Q.).).).(.).).3X).(.|.(.(.|.-X.X X5X8X2X3X(.3.z j 6 j N < 7 6 a r r X. .u t t t i u i r r X.r i u i e r r  .u  .r r e w e 9 r u e e e e r  . . . . ... ..... . ... .r e 9 y : 5 C D H F J H H q.q.t.=XZX1Xg.&XUX:X:X;X:XIXIXIXIXIXIXUXIXPXBXPXPXCXIXIXGX%XI.U.I.R./././.E.U.).).XX|.(.|. X/.).|. X.X|.XX).).^./.|.)././.^././.",
"(./.(.|.|.(.|.|.|./.).)./.U.^.U.Q./././.(.).2X0X8X|.3X|.|.|.XX3X X.X5X|.3X|.k.L j j 3 B 3 7 p t t e e e t r t i i u X.u X.r r r e e e r r u  . .r r e e e e e i u e r r r t u r e u u u u u  . . . . .u u ..X.i X.t q 0 y 6 B C q.q.q.t.t.t.=X:X:X:X=X:XIXIXIXGX:X:X:X`.`.`.`.`.OXnXPXFX-XR./.(.(.).|.(.|.).3X8X3X8X8X.X)./. X|. X|.8X|. X|.}./.(.(.R.U.E.U.^.",
")./.(./.|.|.3X).|.|.3X|./.^.T.U.).(.).(.).(.3X3X).2X).).(.2X3X3X5X|.5X3X3X|.n.K j j 3 G 3 7 s t t t e w 9 t e e t u X.X.X.r r r e 9 9 e e u r r X.u X.r e e 9 9 u u u r r r t u i i e e e u r e e i u u u r r e r  .X.r u u u u h = 1 C D q.y.t.g.a.y.=X:X:XGXbX_.`.`.`.`.`.`.`.`.`.XXsX-XE.(.|.3X3X3X8X3X0X8X0X0X8X8X|.|. X|.|.8X.X8X8X8X8X|.3X).(./.U.^./.^.",
"/./.|.|.|.|..X3X|.3X3X)./.T.U./.(.(.(.|.-X5X|.2X).}.).}.).|.3X8X.X3X8X5X3X8Xb.K j V G F B 3 6 0 q 9 e t t t e 9 e e u X. .r i i t t e e e r r r r  . . . . .r r e e r r  . . .X.r e e e e e e e u  .u  .r u u u 9 t t e e i i i e w h 0 9 h h T D y.y.g.y.y.y.=Xn._.OXOXOXOXnXOXOX'.'.).7X(./.|.3X).3X).3X3X2X).8X|.8X|.|.|.|.8X8X.X|..X(.|.|.|.3X}.)./.). X|.",
" X|.)./.).(.(.(.|.}.}././.U.E.U.(.(./.(.(.}.|..X|.}./.|.|.5X8X|.5X3XgX3X3X|.K.K G 6 6 j 6 2 4 * w w q t t 9 t 9 q t t i t i i i i r e r u u  .u r u u u u u u e r u u u r  . . .u e e e e 9 e e e i r r r r e i e e 9 e e u i i 8 8 8 8 9 w 9 8 h h a S @.r.i.i.t.i.t.i.p.F.'.'.'.a.#.:X).|.^. X6X}.}.}.|.}.}.}. XoX X X/.^.U.(.)./.}. X}. X XXX).(.(.).|.|.|.",
"U.U.U.K.U.K.U.K.U.U.E.U.U.E.E./.(.(.(.(.}.|.|.5X3X3X|.(.|.3X3X5X9X5X9X3X0X|.T.` G j L ( G 3 6 p q 0 w q q t q 9 9 9 q q t e t e t t e i u ......u u u r r r e 9 9 e e r e u r u u r r e e e e 9 e e e e e e e e i e e 9 e e e e 9 8 w 8 8 8 8 8 0 w & = h h A A #.&.a.D.D.y.y.q.q.y._ ;X;XaX3X-X).).).).|./.}.5X;X;X3X-X|.}. X}.(. X X{. X X X|.(.(.(.|.|.|.|.",
"|.).). X).(.).).).).(./.Q.^./.E.(.}.}.-X|.|..X3X8X3X|.}.|.3X8X3X3X5X9X5X3X3XE.{ d G ) r.e.B 6 5 0 q w q q 9 9 9 q w 9 w 8 w q 9 9 9 q e e i i ..u u r e e e e 9 9 9 9 e e e e u u u u u r e e 9 e e e e e e e e e t e 9 9 e e 9 8 8 8 8 8 8 w & h 0 w w w w 9 9 w q a f D ` r.i.y.y.q.y.y.y.D.D.L.T.%XsX0X0X).XX}.2X7X)./.^._._. X/.^.U.^.E./.E.U./././.).(./.",
"3X.X8X3X3X|.3X3X5X5X5X|.)./.Q./.(.(.(.|.}.2X|.|.|.}.(.|.|.5X3X5X3X3X8X3X3X)./.i.c 6 A | r.B 6 > w q q 9 q t w 9 q q 8 w q 8 0 q q 0 w 8 w 9 e 9 e e r e e e e 9 9 e 9 9 9 9 9 e u e u u e r e e 9 e e e e e 9 e e e 9 9 e e e 9 & 8 & 8 8 & w & w & 0 0 q 9 w w y 9 9 9 9 9 w t d D L y.y.e.q.H J q.e.s.Y.).).XX^.oXoXoX^.)./.XX^.^. X^.U./.U./.U.U.U.U.U././.",
"|.|.).|.-X|.|.).3X3X3X(.)./.(.(./.W.(.}.|.|.|..X|.}.|.|.3X3X|.|.|.|.5X}.5X).3Xb.c c 5 G r.3 6 j q q q 9 9 9 9 9 9 q t w 9 q 8 8 0 0 0 w 0 w 9 w w e i e 9 9 9 e u e e 9 9 9 e 9 e e e e r e 9 e e e e e 9 9 9 e e 9 9 9 9 e 9 9 8 8 8 8 8 0 & & & & 8 0 0 0 a a q q 9 y 8 & & & 9 9 y p s V ( ( e.q.H H e.r.D.=X8X).|.|.wX}.}.].oX X^.^.^.U.U.^././.^././.(. X",
"(.|.|.8X8X3X3X3X3X3X2X|.(.W.E.(.-X(.}.|.|.3X5X5X3X|.|.}.|.3X|.}.|.|..X|.8X).3XK.K ! 6 2 G 3 3 j q q q q 9 9 t t 9 q t q q 9 9 q 0 w w 0 0 q q 9 9 y t e 9 9 9 9 e 9 9 w 8 8 9 9 9 9 9 e t e e e e e e e e 9 9 w e 9 9 w 9 9 9 8 & & & & & 8 & w w 0 0 0 p a d P g g a a 0 0 0 h w w w w 8 8 8 & 1 B A ( ( H q.q.y.r.D.#XY.Y.(.3X5X.X5X.X X^.U. XoX)./././././.",
"(.|.(.).).3X3X).0X5X3X}.(./.(.W.(.(.}.(.}.|.|.3X(.)./.E./.(.}./. X}.}. X8X).3XT.) L 6 # 3 N 3 3 a 0 a f h q a q q q q q q 9 9 9 0 0 w w 8 q 9 e 8 9 9 9 9 9 9 w 9 9 8 8 8 8 8 8 9 8 q q 9 t e i e e e t e 9 e 9 t 9 9 q 9 9 9 8 & & & 8 0 & = = & & = 0 h h p a f S P P S S g h y 8 8 9 9 9 9 9 w 8 8 = * 1 A ( J _ e.t.e._ _ r.D.@XQ.%X/. X|.5X(.)./.U.^././.",
"|.).|.2X|.|.-X-X2X2X-X(.E.W.(.).(.(.(.E./.E././././.I.I.E./.|. X/. X X/.8X).-X).| 4 # # 3 B N J d h A @.A f f h 0 q q w 9 8 9 9 q w 0 w w 8 9 q 9 8 9 8 9 9 9 8 9 8 & & & & = = 8 8 w q q 9 e 9 r u r r t e 9 e e q w w w 9 w 8 & 0 0 0 h 0 0 0 h h h p y h a a K U Y Y Y o.W b a q 8 y w 8 & 0 9 w 9 9 9 w 9 9 p p V H q.q.q.w.Z _ r.i.F.K.E.|.|.|./.^./.^./.",
"N.N.B.B.B.A.B.A.V.V.B.Z.Z.Z.{. XE.W.Q.W.W.}.).). X/.E.R.E.U.U.{.A.M.A.A.Z.N.N.V.L @ + # < N N N V 6 A 1 $ V A ( A d p 0 0 9 9 w 9 w 8 w 8 9 9 9 9 9 9 9 9 q w w 8 8 8 8 8 w & & & & & & & w 8 & 8 9 9 e i t t t r t e 9 w 9 9 w & & h f U U U ` Y @.Y U S f a h 0 h h a d f f S f g g a 0 w w 8 8 9 y 8 8 8 9 y 9 y 9 8 > : 6 L w.J q.t.y.q.e.r.b.C.U. X^./. X",
"[ [ ] [ ] ] ] ] | -.s.s.s.s.s.s.z.z.x.x.N.m.V.V.V.A.P.P.V.m.m.m.z.s.x.z.z.5.k.j.V X O @ < N N N 3 1 1 $ @ @ @ , * * 5 p p a a q 0 & w & w 8 t i e e 9 w w q w 0 8 9 0 q 0 0 0 8 0 0 0 8 & & & 8 8 8 8 9 9 9 9 9 9 q 9 9 9 0 8 & 8 & = 0 d P ` @.@.@.@.@.U U S A f f f f f a a h h h a y a y q 8 9 0 8 8 8 8 8 8 8 9 y y y 8 y > 0 h p A H H J w.q.w.e.f.D.P.I.",
"] ] ] ] ] ] ] ] ] ' ' ] ] ] ] ] / { ;.{ { { ^ { { <.2.2.2.r.} | s.;.s.s.-.;.s.] , o X @ < N N < 3 , $ + O X @ @ # @ @ O + * 1 p p p p p 0 0 w w t t e 9 9 w w w 8 8 q q q 0 8 8 w 0 0 8 8 & 8 & - - & & & & & 8 8 8 w w & 8 & & & & = = p U @.` @.@.~ Y Y U U U U U Y @.o.Y Y @.f g h q q q 8 8 8 8 8 8 8 8 8 8 8 y y y e y 9 9 8 8 0 y p d d d H q._ _ _ e.e.",
"A.A.C.V.A.P.A.U.C.H.A.V.M.M.M.M.l.M.V.V.N.z.M.V.A.L.I.!.Q.Q.!.!.P.P.m.J.!.!.P.' @ o o # < N 3 < 3 3 @ @ O   O O X o @   X X @ @ * * 5 d d a a q t t 9 9 q q q w 9 q q t q q w 9 0 q 8 8 w & & & & & - & - & & & = & - - - & & & & 8 & 0 a T o.U @.` Y Y Y Y @.` @.U U S S P S U o.o.P f g a a q 0 8 8 8 9 y y 9 y 8 9 9 9 e e y a q y q q 9 y i 9 0 y 6 G F _ ",
"6.v.6.v.N.V.N.b.N.N.v.v.4.4.4.4.m.V.J.V.V.V.A.H.J.J.x.m.J.P.A.V.V.V.V.V.K.U.K.L @ @ @ < N N N < 3 B # X X           X o @ X     O o $ , 5 p d d a y 0 0 0 q q q q i i g t a t 9 q q q q q 0 0 0 & = = - & & & 0 = & & - - & & & 8 & & 0 d P U Y #.Y U ` Y U ` ` &.#.Y U S A S S S P U o.S f g f a a a 0 8 y q 9 8 9 y 9 9 y i y e i y y i y a a y y y 8 8 y a ",
"z.N.v.V.A.H.A.V.z.V.V.x.x.z.x.x.z.z.z.z.z.z.z.z.b.x.c.z.l.M.M.4.M.V.M.4.M.z.z.4 X @ @ < N N N < 3 C 2 @ @ X     O O       X o O o o . o @ @ $ $ 5 5 5 p p p 0 0 q a a t t q q q q q q q 0 0 0 = w = = = - & 0 8 & = 0 & w 0 & & & & 0 h f U @.@.#.` U U U U Y ` ` ` Y Y U T T P S S P P P P P P P P f g y y y 8 8 9 9 y y y y a y y M y a g P f g i y 8 y 8 y ",
"A.V.V.V.C.K.H.A.C.C.P.K.L.H.L.L.I.K.Z.Z.K.K.U.K.U.R.I.I.L.A.A.A.N.C.C.B.B.B.b.A X O @ N J J J N < 3 #   o o           X X           X X X X X X O @ $ 5 p p p p 0 h q a q 0 0 y 9 8 8 0 0 0 = w = = = - - = 0 8 w 8 = w = = = & & & = h A U Y Y &.&.#.Y U U @.@.` #.@.@.@.U T P U U Y Y P P P P Y o.U f f a a q 8 q e y y i a y y i u y a b b g i i g a y s y ",
"6.9.5.1.1.1.1.<.,.1.5.6.1.3.<.2.3.4.4.z.z.4.v.N.N.C.Z.K.V.V.V.V.P.H.V.H.Z.L.Y.V @ @ @ J w.J J N 3 3 ,   @ @ X % o o X X X X X X   X X X X X X X @ X X @ O $ $ $ = 0 0 0 0 0 0 0 8 8 8 8 0 0 0 0 & = = - - = 0 8 0 = w & & = = & & & & = h f Y @.#.#.#.` U U Y @.&.#.` @.Y U P P T P U Y U P f f T P P S f g g a y a q q y i t q y y y e y a i g l a g b g g y ",
">.O.>.^ <.5.<.<.1.5.4.4.5.1.<.<.6.4.4.2.>.<.4.8.v.N.z.4.M.z.z.H.U.A.J.!.P.%XA.K o . # H H t.q.N 3 N 3 , # @ # X X X X X X   X X   X   X   X X X X X X X X o o X # $ * 4 5 5 = = 0 0 0 0 = 0 & & w = & - - = 0 0 q 8 8 8 & & & & & & & & = a P U U ` ` U U U Y #.@.@.#.&.@.@.Y P T S U U U U Y T d f d S S a f a S h a h q h q t g q a g g s s a a b g g y g g ",
"<.<.>.<.<.<.2.2.4.4.4.4.2.<.:.{ 2.4.4.4.2.2.<.2.^ { ^ ^ { ;.-.j.s.s.] ] ( f.d.H @ # # ' H e.w.H 3 3 < < $ $ $ # @ X X X X X       X X   X     X   X     X X X X X X X @ $ $ * 1 * = = = = = = & = = = - & = 0 0 0 8 w & & & 8 = & & = & = p f S U o.U S U Y @.&.@.@.&.o.@.o.Y Y S P U Y U P U o.S f S a g A h a f S g g g g h h a a a a a f b a a P g b f g a ",
"Q W / ~ ^ { :.;.2.<.$.<.2.<.$.;./ { { / / / ^ ~ ;./ / R R / -.} s.s.' H H w.h.H , < , r.q.H q.H N < @ # % @ @ $ @ @ @ X X X X   X X   X     X       X       X   X         O O @ % $ * * = = h 0 = & & - = 0 w 0 w 0 0 0 0 0 = & & 8 0 & 0 0 f f f S T T Y o.o.@.@.@.#.#.@.@.o.Y U U P P U P f P =.S S f f h h S a S f g S h h h T d S A f S P t h S S U p.@.g ",
"^ ^ ^ ^ ^ ^ O.2.^ ^ / ! / { { ;.2.;.<.;.-.3.l.z.^ / / ! R -.G.G.R.L.D.s.s.d.d.d.D , < s.d._ Z J J < < @ # o o @ @ @ @ @ X X X X X O X   X   X   X               X X X X           X O @ $ * * 1 1 * = = 0 0 0 w 8 0 8 0 0 0 w 8 0 & 8 8 0 a g f a f S P Y Y U U o.#.&.#.&.o.o.U Y U P o.&.o.=.o.o.S S f S h S h g S S S S S S U Y T S U S @.@.S U U S #._.n.Y ",
"N.8.6.6.5.5.5.6.N.N.N.4.4.4.z.z.M.z.N.V.A.U.U.E.oXK.C.H.J.P.%X%XdXAX%X%X-X%X7XaXD.C < r.ZXr.H Z N 3 < < @ X X O @ o @ o X @ X X X X X         X X   X   X                             X X o @ % + * * 1 : p 0 p 0 8 8 8 & w w q 0 w 0 0 0 a f P f f d f U U U U o.o.*.*.&.#.o.P P P S S #.*.=.b P =.=.b g g g f S S S U U S S i.#.D ` #.r.i.i.i.p.i.` i.T.F.p.",
"6.4.4.4.5.<.<.3.4.6.M.8.4.2.2.3.3.4.z.M.V.V.C.H.).I.R.(.4XaXaXpX1X1XZXZXFXZXZXAXZXD.Z Z D.*Xr.H N N 3 @ X @ @ X o o X X X X X X   X   X           X   X     X X                 O X         X . @ @ $ $ % * 5 5 : 0 y y 0 8 0 0 0 = 0 8 8 q g f f f f P Y o.U o.o.o.o.#.o.o.o.o.S S g g o.o.=.g P g b ..g S g g S o.#.#.#.r.i.F.i.` p.p.i.i.i.F.%Xa.p.D.a.T.T.",
"Z.U.U.Z.A.C.A.A.A.Z.U.Z.U.Z.Z.Z.U.U.E. X).7X3X9X6X6X7XdXsXaX&X&X1X1X1XSXSX1X1X,XZX;Xp.H ' *X#Xt.J C N < @ X @ X o o X X X X X X X         X X         X X   X   + O                           X X X X X O O % $ * 5 5 p p : = = 0 0 0 & & 8 y h a f f P U U P P o.o.o.o.#.*.o.o.o.P =.P P g =.=.P g g b S g g g S &.p.p.a.T.:XFXp.p.=XF.=Xp.i.&X;X&X=XT.;X;XT.",
"|.5X.X|./. X/.U.E.U.U.K.P.Z.K.C.U.Q./.}.3X3X;X9X,XaX>X>XpXZX,XpX4XaXdXdX7X,XZX1X&XFXFX=X' D.@X#Xy.q.C 3 @ @ X X X X X X X X   X               X           X                 .         O         X X X X X X X   X o @ $ * 1 5 p h 0 0 0 & 0 0 0 g b b f f f f o.o.#.o.o.#.#.*.o.=.g =.o...g b b =.g g =.g =.g g #.p.F.p.F.*X;X;X1X*X;X;X;X:X=XFX*X;X;X=X;X;XT.",
"/.).).).^.^.^.^. X/.^.U.U.Z.U.U.K.^.(.-X7X&X>X>X,XaX,X,XaXZXpXZXSXZXAXSXSXZX1X1X,X<X,XSX1X#X#X$X#Xy.e.Z < @ + O       X X X X X X X     X                                                                               X O O O , 1 4 5 p d d d h a a a a g S o.P o.o.o.o.o.#.o.o.o.o.=.=.g b =.o.o.=.#.#.#.U U #.p.T.T.F.*X;XaX1XFXFX*XD.%XFX;XZX;XY.$X,XaXaX",
"C.K.Z.V.b.V.b.b.v.v.z.v.v.v.v.v.v.V.J.%X%X%X&X>XpXpXpXpXAXFXAXAXpXZXZXSXDXSXSXSXSX1X1XdXZX,X*X@X@Xs.e.H N @ X X         X X X X       X     X                                                                               O O     O + * 5 5 p d A d d S S P f P o.o.o.o.o.#.#.*.o.o...g =.=.b S o.i.T.T.T.F._.F.-X:XaX;X&XaX&X;XZX:XT.Y.aXFXFXJXFXpXZXDXDXDX",
"^.U.U.U.K.Z.C.K.A.H.H.I.U.U.U.U.I.R.%X7XdXdXSXSXAXAXAXdXSXFXFXDXSXSXSXHXJXDXDXSXSX1X,XdXSX1X$XS.S.S.d.e.H < X X           X X X   X       X                                               X               O                     . . X     X O $ @ , 1 5 6 d K P U U Y Y o.o.P o.o.o.o.g g S o.&.n.F.;XFXFX:X;XFX;XFXHXHXDXdX7XaXaXFXFXZXdXDXUXHXJXJXHXHXHXJXJX",
"N.v.v.b.v.b.V.b.b.b.C.K.I.R.E.R.Q.W.%X&X,X,X1X,XSXdXAXZXJXJXFXDXDXDXDXHXHXSXSXSX1X1X,X,X<X#Xg.u.w.d.d.y.q.Z < X X X X X X X X         X   X   X                                                   O                             X X X X X @ @ # @ # # # $ $ $ 4 5 A A T P P o.#.o.o.o.o.=.i.n.-XsX;XaXFXJXFXlXdXHXSXSXDXDXDXDXDXdXFXFXGXUXUXJXJXJXLXJXHXDXHXJX",
"V.v.N.V.C.V.C.C.K.I.U.R.R.Q.2X7XdXdXpXAXAXAXSXSXSXSXdXdXSXSXSXJXDXDXDXSXdXSXpXpXSXpX1X<X#Xf.u.u.w.w.u.t.e.H 3 @   X o X         X       X                                               X                               X   O O         X o @ # , , , @ @ @ # , # $ , 4 1 A T ` o.&.&.n._.;XsXGXlXaXsXAXHXHXlXdXDXsXdXFXKXJXJXJXDXHXmXHXHXHXHXUXUXHXUXHXdXDXUX",
"U.^.U./.(.).).|.E.W.(.-X-X%XaXaXdXpXdXAXSXSXDXSXSXSXSXSXSXJXSXSXDXDXSXSXSXSXSXZXdXpX1X#Xg.u.w.u.u.w.w.w.t.e.H , X X X X       X X   X   X   X                                               X                                   O   O   X     X o @ # # # # $ , , # @ X , B ) ' K./.-XaXDXDXFXJXGXDXkXDXHXkXlXdXDXbXsXFXDXDXDXSXDXlXHXHXHXdXDXDXHXDXDXlXpXAXHX",
"V.V.C.K.K.U.U.K.Q.E.Q.-X7XaXdXAXDXAXDXAXDXJXDXDXSXSXdXSXSXDXSXSXSXFXSXZXSXDXSXSX,X,X<X#Xd.t.w.w.w.u.u.w.u.f.y.H $ X   X X     X           X                                     X   X X X X                                             X   X O X O o @ o @ @ @ , # < < C r.D.@XaXDXDXFXdXaXdXGXDXDXkXlXlXAXDXHXdXlXlXlXaXdXpXaXlXpXDXHXSXSXDXdXpXdXpXAXDXDXAX",
"K.A.K.I.U.Q.Q.T.J.H.I.%XaXFXJXFXFXDXDXDXDXDXSXAX1XSX1X,XSX1XdX1XAXAXSXSXSXSXSXpX<X<X*X#Xt.f.t.t.h.f.f.h.h.t.t.t.4 @   X X         X   X       X                                               X O                       X       X               X X     o o o O O @ , 6 _ D.@X=X&X&XpXpXAXdXFXlXdXAXdXAXlXAXAX,XSXSXZXaX&X7XaXaXFXaXpXAX>XdXAXaX,XpXAXDXUXJXdX",
"K.C.K.K.Q.W.R.Y.%X%X,XdXAXDXHXJXDXDXAXDXDXJXJXSXHXSXSXSX,X1X1XdXpXpXdXSXSXpXZXpX1X<X*X#XS.f.t.t.g.g.g.g.f.h.u.t.w.N X @ O O O X X     X @ X                                                                         X X     X X   . . X   X X X @   X @ X @ X X < , 3 C ( r.D.D.Y.D.D.G.Y.*XaXAXaXaXdXaXpXdXaXAX>XpX&X7XpX<XAXaX;X&X&X1X&X1X*X;XaX&XAXFXUXUXsX",
"I.K.I.T.W.-X7X7XpXdXdXDXDXdXdXDXDXDXDXDXJXJXDXSXSXDXSXSXDXDXHXSXSXSXSX,X,X,X,XpX*X<X<X<X#Xg.d.g.f.g.#X#Xg.g.f.w.H H < X X O   X X   X       X O                                                                 X         X       X . . X X o . o o @ X @ @ < , , 3 V A C C ( r.s.s.d.D.D.G.%X%X,X%XaXpXaX,X%X%X&X;XaXAXaXaXDX%X,XG.G.&X*X1X;X&X&X&XZX;X%XJXUX",
"I.Q.W.%X%X-XpXFXAXDXDXJXDXSXDXDXDXHXJXHXDXJXDXSXDXSXHXJXJXJXHXSXdXSX1X,X,X1X1X1X1X=X#X#X<X#X#X#X#X#X#Xd.d.f.t.w.t.H C <   @ X       O                                                                                 X X X       . @ @ @ # # # o # @ @ # < , 6 G 6 2 B G C 6 3 F ( e.r.r.s.G.&X*XY.*X&X,X>X%X&X%X*XAXFX&XaXZX-X&X*X&X;XD.F.%X;X7XZX&XD.*XGXFX",
"K.W.-X7X7XaXpXFXZXSXJXDXDXFXDXJXHXHXJXDXDXDXDXDXDXHXHXHXJXJXDXSX,X,XpX,XZXSX,X<X<X*X#X#X#X#X#X@Xd.S.S.@Xd.f.t.d.t.q.H ( , X       O     X X                                                                           X @ o X   X @ @ # # # < 2 # # o # , 2 < < , 6 V B 3 , , , 3 B L ' d.S.*X=X&X@X@XY.*X&X$X$X%XF.&X;X-XaX*X*X;XF.F.p.i.p.T.p.F.i.Y.D.F.FXJX",
"Q.%XaXdXZXaXZXAXSXDXHXHXDXHXHXJXJXUXHXDXHXJXHXHXJXHXHXHXHXDXdX,X,XZX1X,X,X1X1X*X#X#X#X#X#X#XS.d.@X$X@Xr.s.d.d.d.d.#XS.@Xr.1 O @ O X X                                                                                 X % @ o   X X o @ @ @ # < @ # @ < , # # @ $ , # # < , 1 3 , L e.s.D.G.@XG.=XD.D.D.$X;X$XY.%XY.*X=XY.F.) ' i.| ) ) ) i.T.i.r.i.Y.*X*X*XF.",
"%X,XaXpXZXZXAXFXdXSXHXHXJXJXJXJXHXJXJXJXJXUXJXDXHXHXDXDXSXSXdX,XAXZXpX,XZXSX1XSX*X<X<X<X#X#X@XY.&X*XS.D.@XG.D.d.=X<X=X=X=X_ V + X X X         .                                                                       X @ @ o o X   X X X X X @ o O @ 2 , # 3 2 # . X o X @ B ' 3 B ( L F D ) c.r.r.r.y.c.@X*XG.D.&X;XF.i.r.( _ e.' ' _ F F r.' D ( D.D.i.*X1X",
"pXpXZXZXAXDXDXDXDXHXHXHXJXHXUXUXLXJXUXJXJXJXHXDXDXHXDXdXAXSXSXSXAXdXZXDXDXDXJXJXFX1X1X<X$X$X,XZXZX<XS.=X&X*X@X&X1X<X*X=X=X*X*Xy.N < X X .       O                                                                 X   X   X o X O O   X   X X O o X # V 2 # 6 2 @     o   X 1 _ B , X X @ @ @ 6 _ r.r.` y.r.i.D.r.D.F.*X*X=Xi.D.e.' ' H H G G H _ ' r.( H r.c.",
"ZXAXSXJXHXHXHXHXUXUXHXHXJXUXHXHXJXJXUXJXDXDXDXHXSXDXHXlXDXDXHXHXDXDXDXJXJXDXFXJXFXFX1X1X&X,XpXpX&XSX,X*X=X=XS.*X$X1X1XS.S.*X=X=Xi.D # X       O                                                                     X         X X     X X   X @ $ @ , C 4 @ , X o       X X @ @ 1 ) ( 6 $ $ @ @ , V r.r.` r.r.s.r._ ' @XZX*X' ( L ' ' F ) ' ( ' s.s.S._ B F _ ",
"DXAXHXHXHXJXUXUXUXHXJXUXHXHXHXUXHXHXHXHXDXJXFXDXDXSXDXDXDXHXSXHXDXHXHXJXHXSXSXSXAX;X1X&X*X1X,X1X<X&X$XS.f.h.s.d.g.d.d.e.' e.q.f.h.w.J N < # . .   . X O                                                                         .       . O . @ 4 , L 6 o # . o   . @ O o o   % # 3 s.r.X 4 < @ , G 6 2 V ( V ) L 6 3 ) Y.,Xc.' ( ' D.r.i.*Xr.r.| ( ( C B ' D.",
"HXDXJXJXJXJXJXJXUXJXJXUXUXJXHXHXJXJXJXDXSXSXSXSXZXZX1XSXpXdX,XdX,X1XSXSX1X<X<X<X,X<X*X#XS.S.d.S.d.d.d.t.e.e.e.e.w.] h.h.q.w.H H J q.w.H J 3 3 # o o           O                                                                 . .       .   # O @ , @ o # . $ @ o o @ # 7 o # 3 4 F L < 2 @ , 2 6 2 # , , , 2 2 2 2 2 D D.&X*XY.F.Y.r.r.r.D 6 6 ( ' F F s.,X",
"ZXSXDXDXJXSXZXZXHXJXJXJXHXHXJXHXFXDXSXSX1X,X1X1X,X1XdX1X<X$X$X<X@X$X#X$X#Xd.d.d.d.d.d.t.t.f.f.f.t.e.e.q.w.w.w.H H H w.H H H J J J J J J J H H J N 3 # @ o o . .                                                   . . . . .     . . o . o o . 7 @ 4 , # 6 2 . 7 X 7 3 # 2 B 6 . 6 2 7 7 7 2 $ 6 G F G 6 6 2 3 3 , 3 6 3 2 ' D.i.) L ' V ) ) V V F ) ] F _ r.D.",
"$X,X&X<X,X*X$X$X$X$X$X$X@X$X<X<X<X,X,X*X$X@X$X*X!.$X$X$XS.S.S.d.d.S.S.d.d.d.d.d.f.e.e.e.w.t.q.e.e.w.e.q.H H H H q.H H J J J H H H J J J J H H J N 3 < < < # @ o     O                       .     . . .   . . . . . . . . . . . . . # . o o . # 2 ] ( L ] G 3 3 6 ( ] F G ] G 2 < B G 3 6 2 3 j 3 F G L G B F G 6 4 3 6 B V F 6 B C L C ( B F ] s.d.s.s.D.S.G.",
"&X,X&X&X,X,X$X*X,X,X<X&X<X,X,X1X,X1X,X1X<X*X<X<X<X,X,X<X$X$X<X<XG.$X@X$X@XS.S.S.d.t.t.t.e.t.e.e.e.f.t.e.e.' h.;.e.e.H _ H J J J N H e._ J J J N H C N 3 2 2 7 # o # # @ X     . .   . . . O O . . . . . . . . . . . . . . . . . . . # . # 7 o 7 _ G.D.s.s.r.s.' L B G G 3 3 3 3 3 ] s.s.] 3 G G ] r.' ] ] ' s.] G 6 6 F ( ( F V 6 L ( F V 3 ( s.s.S.D.c.D.@X@X",
"-X%X%X,XpXZXZXSXpXZXSXSXSXSXdXSXFXFXJXSXSXSXSXSXSX1XSX1X1X1X1X1X,X,X1X1X,X&X&X&X#Xd.S.d.#Xg.d.d.S.G.#XS.d.d.d.S.S.d.d.=Xg.s.' ] ' D.D.d.s.] H ] e.( J 3 3 < # < # # 7 # . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . % # 7 2 7 2 _ D.S.r.' ] ' ) 6 2 3 B 3 6 3 3 B ( d.c.' B G F ' s.] H ( ' s.( 3 B 3 C ) ) L B F r.r.L 6 V G ] r.D.c.d.G.G.G.",
"Y.K.Q.%X>X,XdXdXZXAXDXJXDXFXSXSXZXAXSXFXSXSXSXdXDXSXSXpX1X,X1X1X1XdX1X,X1X1X1X1X1X#X#X<X$X#X#X#X$X$X#X#Xd.S.S.G.*X@X*XFXFX*X@X<XG.=X@XS.d.r.' e.e.H G 3 < < # # # # # # . . . .   . .   . . .   . . . . . . . . . . o . . . . . . . . . # o . 7 3 ( ( 6 B 3 , # # < j B 3 j 3 7 7 6 ( F 6 7 4 G H ] ] ( ( r.r.] L V 6 C ( ' ( C C ' e.A A ( L ( r.r.r.r.c.D.G.",
"E.E.7X7X%X>XdXdXAXDXDXDXAXdXpXdXaXdXAXDXSXSXdX,XSXSX1XpXSXSXdX,X1X,X,X,X,X1X<X<X&X#X<X$X$X$XG.<X$X#X#Xd.g.G.#Xg.Y.$X=XY.Y.D.@X@X@X@X@X*X*XS.s.d.s.' F N 3 < < # # # o X . . .   . . . .   . . . . . . . . . . . o o o o o o o o . . % o o o . 7 6 F G 3 G B $ 2 # < B 3 3 3 7 # # B G 3 2 2 4 6 G ' s.s.s.s.d.D.s.r.d.Y.@XG.G.c.e.r.c.) | | r.s.' d.i.' _ r.D.",
"Z.K.I.E.Q.-X;X7X-XaXaX;XpX;X1X;X;XZXZXAXFXFXDXdXDXAXSXSXSXAXSXSXSXSXSX1X,X,X,X,X<X$X$X#X@X#X#X#X#X@X#X#X#Xg.d.#X#Xd.S.d.D.c.D.D.D.d.s.r.r.r.( ( F G 3 # # o o o . X   . X .   X .   . . . .     O O . o . . . . . o . O . . . . o . o o o . % o # 2 6 3 < 2 2 , # 7 7 , # < 2 3 7 3 ) F 6 ) r.r.d.g.S.D.S.$X*XG.@XS.*X&X&X&X$X*XY.G.D.i.i.D.i.r.r.r.r._ ) s.G.",
"6.5.4.4.N.V.K.H.R.R.R.%X*XT.*X%X%X*X&XpXpXZX1X1X,X,X<X,XpX1XSXSXSX1X1X,X,X,XZX1X,X,X<X$X#Xg.g.d.d.f.d.f.t.e.t.t.s.t.t.r.r.e.e._ _ H ( ( _ C 3 < 3 3 , @ .   .     . X X X X . X . . . . . . . .     X X   X . . . .       . .   o o o . . o o . # , 2 2 # $ # # o # 7 # # 2 4 6 6 B _ ( F ' r.s.p.p.i.D.D.F.D.F.c.c.c.F.G.Y.T.Y.G.Y.*XG.D.G.D.i.D.i.D.r.r.G.*X",
"9.6.N.N.A.A.U.U.R.T.Q.R.R.Q.%X(.aXaXdXAXDXDXDXDXpXpXpXZXSXSXSXSX,X,X<X>X,X,X1XpX1X1X<X*X#X#Xd.d.d.S.d.f.e.f.s.d.d.d.r.y.y.F F F F N C ( ) ( C B # # o X . . X . .   .   . .   X . . X . O   . . . X . o o o o o   X . . o o o o o . o . o . # o @ $ , $ 7 , , $ @ % $ 4 2 6 V ( ' ' i.s.r.G.$XpX;XT.T.F.T.F.i.D.D.n.D.D.F.Y.%X*X*X&XaX&X;X;X;X&X&X&X*XD.i.S.Y.",
"B.V.K.E.(.%X-X%XQ.%X-X%X-X%X%X7X,X;XaXaXpXpX,XpXSXSXSXSXSXSXZXpXSXSXpXSXSXAXSXdX1X1X<X<X*X#X#X#X$X#X#X#Xg.d.d.f.d.S.S.=XD.r.r.e._ G N B 3 < 2 < < # # o o . o o . X X .   X . .   .   X . X .   o o o o o o o o o o o X o o o o X o X o o # # # # 2 4 2 4 6 4 1 4 ; 5 6 V G ( r.s.s.D.r.r.D.Y.%XY.*XY.*X&X&X&X;X;X;X;X;X&XpXpX,XT.*XY.D.D.=XF.F.i.c.D.i.c.Y.*X",
"K._.%X-XaX6X;X;X7X7X6XdXaXaXaXsXFXFXFXDXDXDXAXFXHXDXSXSXSXpX,X,XaX,X&X&XaXaX,X<X*X*XY.@X#XS.S.#Xg.g.d.d.y.e.e.e.q._ _ ) ' F H ( ( B B B 3 3 3 < < < # . . . . o X X X   . X . X   . O   . . . X .   . X     .         . .   . . o X o . o O @ # $ 4 4 4 6 6 5 1 5 5 4 V V V ( ' r.r.i.r.c.D.F.Y.Y.Y.S.D.*X,X,X,X*X%X;X*X%X&X>X%X;X*X*XF.G.*XY.Y.*X%X7X;X%XaXaX",
"V.C.C.H.A.L.I.U.I.R.-XaXdXAXlXFXAXAXsXAXDXAXAXaXDXSXSXDXHXSXAXdXAXpXpXpXpXZXdX1X1X<X@X=XS.S.S.#X@XG.g.d.f.d.d.d.S.s.e.e.F C 3 3 3 B B G F L B 2 , # o .       o .   . X . X   X X . . O O O o O . o o . . . . . O O O . o o O o O O O O O O O O * 7 4 4 * 4 1 1 * 1 1 1 1 6 A A L ) ) i.c.D.D.*X%X%XF.D.F.Y.Y.F.&X%X%X&X%XaXZX,X;X;XZX7X%X;XaXFXAXaXDXFXAXJXFX",
"4.l.3.2.3.4.4.4.x.b.K.R.%X7X7XsXZXdXaXaXaXaXaX7X7X,X,XaXaXaXaX7X7XaXaXpXpX,XpXdX<X@XS.S.S.d.d.d.S.S.g.d.d.f.e.e.e.s.r.S.r.' ( ( ( F G 3 G 3 2 # # # o .   . X   X   . .   X . X X . O . O . O O . + O + O % O + % O % O O O O O % % % + O % % % $ * $ 4 7 4 2 1 5 1 5 5 5 A L ) ` i.r.c.F.F.F.%XY.F.G.F.%X;X%X%XT.*X%X&X%X,XaXaXFXAXDXlXAXAXAXDXFXaXaX&X&XdXAX",
"K.K.I.L.K.K.C.C.A.U.E.W.(.%X7XaXaXaXpXaXaXaX%X$X%XQ.%XQ.W.%X%X%X%X,X,XZXZXSXSX1X1X1X*X@X@X#X@X#XG.d.f.s.e.e.' e.e.r.e.r._ B 3 3 6 3 , 2 3 2 @ # X o . O X . X   . X X   . X   .   . O   . O O . . . . O + % % % % + + + + + O + + % % % * % * $ * * 4 4 4 4 5 4 6 5 6 6 6 A ) ` i.i.i.c.Y.Y.%X%X&X&X*X&XaX$XG.Y.Y.T.%XaX;X%X*X%X%X$X%X%X-XdXsXAXaX%X%X*X%X,XaX",
"2.j.k.v.V.C.U.Z.E.U.U.I.L.U.U.U.W.}.2X7X7X7X7X7X%X%X>X>X>X>X7XpXdXpX1XZXSX1XdX,X&X&X@X$X$X#XG.d.d.h._ H H F H F _ ( ( ( V 6 V ( L A 6 B B 3 # @ @ @ @ O       O . O % + O + % * * % + + O + O . O O o . o O + % + + - - * - - - 7 - % * ; ; 5 1 p 1 5 1 = p d d A p 5 A Y i.D.F.F.p.r.r.i.F.T.-X-XF.F.p.i.i.i.i.c.c.n.F.F.*X*XT.Y.%X*XY.F.%X(.-X%X%X%X%X&XpXpX",
"$.<.<.1.5.4.v.4.v.v.C.N.V.N.b.v.N.v.z.2.%.} { | { | { { } 2.j.l.j.3.j.j.l.k.l.k.c.r.r.r.r.s.f.s.' ] G 3 B 6 4 6 4 2 4 6 5 6 j L L p 4 6 4 1 $ - @ + O + O + + + * 4 5 5 : 5 p s 1 4 * * ; $ - - % ; - ; ; ; - > > ; > 5 5 > 5 > > ; ; 4 : 5 5 s 5 A U T T &.@.A p d d d T i.T.:X*X=XF.F.F.c.c.c.F.p.i.c.c.c.c.c.F.F.*X%X;X;XaXaX7X;XsXaXaX-X7XaXaX-X%X%XaXaXaX",
"1.,.,.1.*.9.1.6.6.6.4.4.6.v.Z._.U.^.C.J.V.b.x.z.j.k.2.2.%.%.} } <.%.%.2.k.k.k.k.r.r.r.e.e.e.' h.e.H H J J C C B V 6 6 1 * - + % % + O % $ + + + + - - - - $ * - * 4 : : ; : 5 : : ; = * ; * ; ; > ; > > ; > > > > ; ; : > > 5 5 6 ; > ; ; ; > 4 6 5 d p d S A p U ` U f d A ` i.i.i.n.D.p.c.k.c.c.i.i.x.F.T.T.%X%X-X-X;X;X%X%XQ.Y.J.Y.%XY.Y.J.Y.R.T.Y.Y.L.T.Q.",
"8.7.8.7.6.v.B.B.N.N.B.B.N.b.b.N.m.D.F.F.Y.Y.T.Y.>X>X,X>X>X<X>X!.!.%X%X%X>X,X,X,X$X$X@XG.S.d.f.f.t.f.r.e._ ( Z C 1 1 1 1 1 1 1 * ; ; * $ $ % % - + + + + - - + + + + + + + + + + + + O + + + - - - * * - * - % * % - % + $ * ; - ; ; ; ; ; > 5 5 d s d ` &.i.p.&.i.i.i.k.&.D U i.F.T.T.F.i.} &.&.%.&.| i.n.D.x.n.x.F.F.T.J.F.m.F.K.T.K.T.Y.Y.Y.Y.!.T.T.!.T.!.T.",
"B.B.B.B.Z.C.C.A.N.V.C.Z.K.C.K.Z.Q.[.%X2X7X7X7X7X%X>X>X,XdXpXpXpX1XpXSX1X1X1X1X&X$XD.r.e.e._ H H ) ) L A A 5 1 = * ; ; - - - - - - - - = = = & 8 y p s y 5 : : : & * - - - ; > > * ; - > > y s p k s s s > s > k 5 s s p p p : : 1 1 5 5 5 5 6 d c A T T @.*.p.i.` ` &.F.F.i.&.&.p.%XT.F.i.&.Y K T T K T { %.k.&.2.k.k.b.z.x.V.V.b.J.J.F.m.J.Y.Y.Y.Q.Q.%XQ.T.Q.",
"5.2.4.3.3.2.<.{ ^ ~ ! ! { $.z.V.M.N.N.V.V.N.N.N.C.B.v.k.k.z.N.V.I.R.U.R.Q.Q.!.G.D.s.r.e.e.' ' H F V B 4 , $ $ - % - - + + + - + + - - ; : : : : - - - - & ; > - = y s s s 5 5 : - ; : : p p : : : = * - - - - > y 0 : : : : ; - - - + * $ * * * * * = = d U &.&.U S A L ` i.c.n.F.F.F.p.x.K.k.$.$.O.@.~ $.3.v.3.2.<.%.2.%.<.2.z.b.b.V.v.b.J.F.b.x.D.b.F.J.I.K.",
";.;.<.2.$.$.^ ~ T K x v v x I / 5.4.6.4.5.4.5.4.3.3.3.%.2.k.v.V.V.H.H.K.L.R.R.L.G.D.d.S.g.d.s.t.f.t.e._ F C C B 1 1 1 , $ % % % % % % O + O + . - + - - - > - - - > > > s y : ; ; ; : p 5 : : - * * * * - - - * : : : : : y : y * ; ; p d A A A 6 5 d d T U ` ` ` r.p.D.F.F.T.T.F.F.F.i.i.&.&.~ $.$.~ ~ ~ ~ T b l k c K K K T [ ~ [ / [ ! [ ~ [ | { { { { 2.2.",
"B.C.Z.Z.U.Z.A.C.B.v.4.4.3.5.7.8.N.B.B.N.v.6.6.N.H.L.R.Q.W.W.Q.!.Q.W.Q.Q.>X>X&X$X@X@X@X@X#X#Xd.d.r.e.e.) ( A V 6 6 4 $ ; ; ; * * * * ; * - ; ; ; ; ; : : : 5 s > s s k y k s d s s d z c z z k s l z x b z l k s s s s s s k k s k k k c K T L T A A d L U %.n.n.n.T.:X:X;XT.T.:X;X-X).F.i.~ ~ $.%.&.3.3.2.2.$.$.~ O.%.k.z.z.x.z.z.2.2.3.4.k.k.b.m.z.z.3.4.z.N.",
"I.U.U.U.K.~.U.B.V.A.C.V.V.V.C.v.N.N.6.4.4.M.m.V.j.z.z.z.v.M.V.N.v.N.N.z.z.M.z.4.j.s.r.r.' ' ) _ L ` A d d p 1 1 * ; 5 5 p p 5 5 5 : : : = : 5 s s > > k l s k l z l l c z c p p A d L z z z z b T z s l l z z M x b x x M k k M k k k l d c K L j L L f Y U Y &.p.n.F.n.n.F.T.).F.F.p.%.~ ~ %.n.v.v.v.b.n.k.%.$.2.2.k.n.z.k.j.2.{ ~ ~ Q E W ^ ^ ^ / ~ / / ^ { ",
"3.4.z.3.3.k.3.2.4.N.V.V.C.U.U.U.U.U.U.U.V.V.V.V.H.J.V.H.H.H.H.K.T.Q.T.Y.J.F.c.i.[ ] ] R ) R [ ! ) ) ( A V 6 4 4 * * * 5 5 5 s k c s 5 5 s c k 5 > : s p & - + - - > 5 s p 5 p d d 5 : : > : > y : y p y s k l l k k k M k l x x l x E I I K K K K K T ~ i.&.n.'.:X;X_.T.F.F.T.%XF.i.| ~ ~ ~ $.%.%.%.$.$.1.%.<.3.6.6.4.2.<.{ { ^ ^ ^ Q Q >.O.Q Q E n x x M x x ",
"6.v.v.v.N.B.V.C.C.Z.^.^./.). X XI.^. X/.E.E.].].|.-X2X}.2X2X3X|.aXaXaX7X7X7XW.Y.D.s.r.r.' ] ] ] ) ! K R L A L L K d z d s s k c x M M x x K K x z l d y : - & : y p s s s 5 : : z z l z z b b z v I x x l k k l v I n W ~ ~ I b I W W ~ ! ! ! R K T [ &.&.&.*.p._.).:X;X-X%X;XlX_.F.%.&.~ $.%.3.3.%.&.{ %.v.6.k.n.b.V.b.n.k.k.4.C.V.v.z.v.v.v.k.2.%.{ { / / ~ ",
"N.B.B.B.C.C.Z.C.N.C.K.C.K.N.v.z.b.V.z.3.2.} 2.2.j.j.z.b.V.V.b.b.x.M.V.N.V.C.V.M.{ L L R L L R R I I v I b I @.~ T T T b l k k k k M k M l z v b z z l l d s d d l l z b b z c d s d z v W W I v E E E v x z v m I b x z z l z b I I I I b T K T ! &.&.k.n.n.'.n.F.F.F.F.T.-X-XT.-X).K.n.%.$.*.$.3.n.%.$.%.7.3.6.k.k.n.b.b.v.z.M.z.z.3.3.z.v.b.v.x.V.b.z.z.k.z.",
"N.N.N.4.4.4.3.4.3.3.4.z.3.3.3.3.2.3.$.^ ! K K I ~ { 2.4.z.z.v.z.M.N.M.N.N.N.4.4.5.:./ / ] R L R E I x K z z T P a s s y l M k M s k y y y y a s y y k l z l d s d z T b d s d c s l l l l b z l s s y s l l b b b z l d l l b m W W I I b d L A A z T ` %.n.F.n.i.n.F.a.F.T.:XsX;X-XR.b.v.3.3.$.%.n.3.%.$.$.$.1.1.1.O.O.Q Q m m n m m :.+.:.>.Q ^ ^ Q Q n n E ",
"oX~.~.~.B.C.B.N.N.C.Z.U.Z.U.Z.Z.B.Z.^.Z.N.v.v.v.N.B.B.Z.A.B.Z.Z.U.U.K.C.V.N.M.2.:.R R | } ' ] _ L L L L L L L 6 s s y l b b m m m b l l b l M s s l b z l l z l W +.~ W z l s s d l l s k y s y l b b b b m I m l d s l l s s b f z K v K d 5 d f T U T Y &.&.p.-X_._.n.F.;X-XF.).K.n.%.~ +.~ ~ $.1.$.$.O.+.O.3.1.1.$.O.>.^ Q Q Q :.:.Q Q Q Q Q O.^ :.Q :.Q / ",
"6.v.6.6.6.6.4.9.4.4.4.6.v.6.v.N.B.C.C.C.V.B.v.v.B.N.6.4.4.4.4.5.{ { { { { ! R K x c j c L c c c L R K L K K K L I b b b m n m E W b k M M s l k b I m b l l z v W W v I I I T K I I I E m b b z b v W m m +.O.O.W b l s s s s s z v I ! W T T T T $.@.~ &.@.i.k.F._.T.T.K._.T.T.K.K.K.b.%.Y E ^ W ^ ^ ~ O.O.$.1.k.z.k.b.v.z.z.4.4.4.5.5.<.;.;.3.3.2.<.;.<.<.2.",
"6.B.6.6.9.6.9.4.5.6.4.4.4.4.4.8.v.v.v.v.B.b.C.~.N.4.3.3.4.4.%.{ ^ Q E E ! W ! E / R R R R j K K b W n v v b b +.~ W m b l l y y : & - - - & y k d b v b M s p y > s k p y s d z l l l l l l s d l b f k d v Q ^ +.T I W v b l k d l I I K K A K T Y ! &.b.b.x.F.:X:XT.F.F.C.b.x.K.K.K.b.k.$.O.1.O.O.O.1.v.v.z.v.6.z.6.4.4.4.4.4.5.5.4.8.N.4.4.N.4.4.1.<.<.4.3.",
"K.C.~.C.C.C.Z.C.C.B.B.N.C.Z.K.U.R.R.E.(.W.E.I.L.V.V.V.V.V.z.b.x.z.z.V.V.L.W.Q.Q.G.s.} s.s.s.e.' [ ) R ! T K K z A d s 5 p s s l s s > y s k l l x v v l s > > y > - * - * ; ; 5 s s s b W +.W I v v x v W +.m v n W W Q W n x b x x I v K z z L T K K ` &.p.p._.sXFXFX:X;X-XT.F.).).K.b.3.1.O.+.+.+.O.$.5.9.9.9.5.5.$.$.^ W Q O.>.>.,.,.5.5.,.,.:.m :.m Q / E ",
"_.^.K.C.C.C.Z.~.U.U. X^.^. X X.X8X3X3X3X3X}.}.W.}. XU.P.P.U.U.E.Z.U.U.E.}.4X>XQ.H.z.j.k.c.r.) L L L A K b T I K z d d z v n Q +.W I n E v x M l x M M l l k M s l k k s s 5 s 5 y p y s s l z z x b b W ^ ,.O.+.x x v x x v v v W W W W E ! I T T W Y Y %.3.p.n.T.F.F.T.T.).).).T.).T.b.k.3.3.7.%.1.3.7.3.3.1.,.1.<.O.O.<.>.+.O.:.>.>.5.5.5.5.5.>.>.:.>.:.Q Q ",
"v.C.C.b.B.C.C.C.A.U.U. XU.U.U.U.K.U.U.{./.}.2X3X/.E.U.C.Z.U.U.^.U.U. X}.}.(.Q.L.D.c.r.s.s.r.] _ L L A z K T I I T I I v v m Q +.+.W E W v z s y y s k l l v v v m n n v W v x l f l b d b f l z z z k s l l z s l s l d l z I I E v I n I I K K ! ! T ! O.&.%.%.n.i.n.F.;X0X-X).).-X;XT.n.k.3.3.1.$.%.3.4.3.1.O.+.+.+.O.<.>.Q Q Q :.O.^ :.:.>.5.,.>.>.,.,.,.>.",
"v.v.B.b.B.B.B.C.A.Z.U.K.U.K.A.U.C.Z.U.U.K.V.b.b.b.v.z.z.4.v.M.v.A.U.U. X4X9X5X7X$XG.D.D.D.d.s.d.i.| [ ` ! T I ! I x z s k M v b v b s s s > > : > > > s M x M M v v m W W W W W +.I m b m b b d s s y : y s d z b b b v I E W W W W W ~ ^ { { | { &.$.$.*.6.n.'._._._.T._.-X).K.x.F.F.K.v.3.$.$.$.$.1.3.6.6.6.9.>.,.>.1.5.1.<.>.,.,.>.>.>.>.5.5.8.5.9.6.5.,.1.",
"B.C.~.~.Z.C.B.B.U.A.U.I.U.Z.K.Z.C.C.N.N.z.k.2.j.} { $.<.5.z.v.N.v.V.A.C.K.L.J.b.b.b.z.x.z.3.2.-.c.r.| [ T R K K K I c d l x I b W b b l l l l l s s s l l M M s k l v n E W W +.Q +.Q +.+.W v z d d z b z z b I z v v W W ~ o.~ W W Y ^ $.2.j.i.%.%.%.%.3.n.n.n.;XsXsX:X-X7XaX-XK.x.k.k.3.$.$.%.9.$.1.1.4.9.1.,.1.7.6.6.4.4.4.z.4.4.4.5.6.v.C.Z.Z.C.N.A.U.Z.Z.",
"C.C.Z.Z.C.B.C.C./.^./.^.^. XU.Z.Z.K.K.C.C.K.U.U.(.)./.U.U.^.^.U./. X/.E.U.I.H.J.A.m.v.z.z.j.2.-.%.} ) T L L K K ! I K z l l l d l b b b W m m m Q m W W W m v x l x n n I W ~ O.+.Q +.+.+.+.Q W W +.~ W I l d z l b b v I W Q O.~ W ~ ~ ~ ^ { { 3.%.%.v.v.n.v.C.).-XsXFXsX7X-X9X3X).K.b.3.1.1.1.9.9.6.6.9.1.1.,.6.v.v.v.8.8.M.N.b.v.v.N.V.C.K.).I.H.H.U. X{.U.",
"B.B.B.N.v.v.6.v.v.v.N.N.v.v.v.4.3.3.$.{ { $.%.2.%.2.4.z.v.b.V.U.A.U.U./. X X|.}.!.!.D.l.s.-.} r.{ [ ! ! T T K ! $.Y T +.+.~ W ~ T W +.+.*.+.+.+.W +.m +.m n n n n n n n n E W W W W v m b m W W Q +.W W v b I I E E W W W O.$.1.1.*.O.O.O.O.$.$.O.$.+.O.$.%.k.b.)./.K.T.K.n.v.F.K./.K.n.1.5.1.4.3.v.N.b.v.6.4.7.v.C.B.7.8.8.8.8.b.z.4.M.6.N.N.N.C.N.N.N.6.4.5.",
"B.B.B.B.6.1.1.$.2.k.v.B.C.B.N.N.H.b.n.z.z.v.z.k.k.v.V.C.A.C.V.A.C.K.K.U.K.K.H.V.z.4.3.2.2.{ $.{ W W W T T I I I v x I +.O.+.+.+.O.O.+.m +.m m b m Q m m v v v n n x x x n n n E / I M z v n v v b b v v m I W +.W W W W +.+.O.$.,.,.,.,.+.+.+.+.~ O.~ I ~ $.6.v.n.n.C.n.n.v.n.6.c.T.T.k.$.1.6.4.%.n.B.n.n.k.3.6.4.6.6.6.5.,.>.>.1.<.>.>.,.,.>.,.O.>.1.5.6.5.5.",
"A.Z.A.8.8.8.N.N.B.N.Z.U.^.U. X X-X}.}.}.}.}. X|.|.|.}. X4X5X>X].}.R.H.V.m.m.A.P.m.m.M.z.l.j.} } ~ ! T T K z c l s d z b W o.+.+.+.+.+.m +.m m m m m m +.Q Q +.+.W Q Q E n n W :.Q Q ^ >.1.O.+.+.m Q Q W W W ~ O.+.~ W W I T E ~ +.~ W W ~ ~ ! ! Y ~ %.&.%.n.F.F.b.n.k.b.F.K.V.b.b.K.F.3.%.6.5.2.9.9.5.5.9.9.5.5.5.5.8.5.6.5.,.,.>.>.,.5.5.5.,.5.,.,.5.5.,.,.,.",
"N.8.8.6.4.8.8.M.v.6.N.N.B.Z.A.Z.Z.K.U.~.Z.U.U.Z.K.V.V.z.z.z.2.5.2.<.2.<.2.5.5.5.z.2.2.2.2.<.{ { ~ ! ! ! T K K c K x b v m W m m m m m m m m m m Q m >.m +.+.W m Q Q >.:.Q m n W W Q ^ O.O.+.+.Q Q Q Q E v W W o.O.O.O.W W I I I b I I E ~ Y Y ~ ~ $.%.3.b.K._.)._.K.K.).-X-X^.T.J.H.C.2.{ O.^ / ~ O.>.>.<.<.1.1.,.5.,.5.,.>.>.Q Q ^ <.5.5.4.5.,.,.>.>.>.>.Q :.",
"8.8.6.4.8.N.N.N.N.N.N.N.N.N.C.B.B.B.Z.Z.B.B.B.B.N.v.4.1.<.<.<.<.5.1.<.1.5.<.>.O.Q ^ ^ ^ ^ ^ E R z c z c z K x x I I E m v m m W m W m +.+.Q +.+.+.m m m b x M M k k M l x v v v Q +.>.O.O.,.>.>.>.Q n v x x v I W W W W v v I b Y W ~ @.$.$.<.1.&.$.%.3.N.'.U._.K._.T.).).K.b.x.k.k.<./ I n n n v n n n n E n E n n n Q m n Q Q >.:.>.>.<.>.<.<.,.>.Q :.:.:.:.",
"8.8.8.8.8.8.B.B.C.B.6.v.N.6.N.N.B.Z.~.B.Z.~.Z.Z.~.^.^.Z.B.N.B.Z.N.B.6.4.9.9.1.O.1.>.^ ^ / E K x x c k c x K K x I I I I m n E W m m m W +.+.+.m m m v v v b v b x n v n W Q Q ^ Q O.,.1.,.,.>.+.Q E x x x x x n n v v v I v v I z x T ! W ~ O.$.$.$.O.~ $.%.k.k.k.b.K.-X).T.K.K.V.x.3.$.^ Q n n Q Q n n x x x M x x x E Q Q :.>.>.:.Q E x n E E m n n n x n M ",
"B.8.8.8.8.8.N.N.v.4.5.1.5.1.1.4.6.6.v.8.6.N.N.N.C.K.C.C.N.N.N.B.C.C.B.v.B.B.B.6.6.1.O./ { { $.{ Q Q Q / ^ W E n l v v I W n m E W v m m m W m m m m n n b x v v m m W +.O.>.+.Q W Q +.^ +.Q m n M v x n n n / Q n m v v v n n v E I Y ~ ~ ~ $.O.O.~ ~ O.O.%.k.v.F.K.).5X-X).T./.^.b.6.6.5.1.,.1.9.6.1.O.^ Q E ! W E E / ^ Q :.>.>.>.>.Q ^ / E E n n n n n n n ",
"6.6.4.6.5.4.8.8.N.N.N.N.N.B.B.C.B.B.B.A.B.V.C.C.Z.U.U.K.H.V.A.A.U.I.U.U.Z.C.N.4.<.<.{ -.2.j.2.%.>.<.<.O.^ Q E K x I W +.+.W W v W b b b n n m m n n v v b M M v M M M b v m W W I W v W W m n x M x x n n E E Q W I E v v v E n E E ~ ~ ~ ~ ~ @.^ O.$.3.6.n.C.K.K.Q.-X).Q.K.b.V.n.3.3.7.9.9.9.6.6.6.6.3.5.2.3.1.{ <.<.<.<.5.1.1.4.9.6.6.4.N.N.z.5.5.6.5.5.5.8.",
"^ ^ ^ O.>.>.5.5.4.5.1.4.z.4.4.4.6.4.6.4.4.4.4.z.N.V.V.A.H.H.H.L.L.E.{.U.V.N.4.<.<.2.j.l.j.} / R ^ O.O.+.Q W n n v W +.+.+.+.W I m b l l b b v v b M M b v m Q Q +.m b l b n W +.W W I W n v v x n n n x x v n W Q +.Q Q Q Q +.O.^ ^ ~ { $.$.$.$.O.@.$.%.3.v.b.K.K.K.Q.).I.K.K.C.V.v.4.4.4.1.1.4.v.N.C.N.v.N.N.N.z.z.v.v.M.N.N.v.6.N.6.z.N.K.U.K.4.N.N.N.A.A.Z."
};
