/* XPM */
static xpm_row_t const btn_sp_hover[] = {
/* columns rows colors chars-per-pixel */
"260 72 37 1 ",
"  c #CC0505",
". c #CF1515",
"X c #D22424",
"o c #D63434",
"O c #D94444",
"+ c #DC5353",
"@ c #DF6363",
"# c #E27272",
"$ c #00FF66",
"% c #10FF6F",
"& c #20FF79",
"* c #4FFE95",
"= c #5FFE9E",
"- c #6EFEA8",
"; c #7EFEB1",
": c #E48181",
"> c #E68282",
", c #E79090",
"< c #E99292",
"1 c #ECA1A1",
"2 c #EFB1B1",
"3 c #F0BEBE",
"4 c #8EFDBA",
"5 c #9EFDC4",
"6 c #ADFDCD",
"7 c #BDFDD7",
"8 c #F2C1C1",
"9 c #F5D0D0",
"0 c #F6DDDD",
"q c #CDFDE0",
"w c #DDFCE9",
"e c #F9E0E0",
"r c #F9EDED",
"t c #FCEFEF",
"y c #ECFCF3",
"u c #FCFCFC",
"i c #FFFFFF",
/* pixels */
"$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
"$$$$$&477quuuuuuuy77777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777775-&$$$$",
"$$$$4uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu4$$$",
"$$$-uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu4$$",
"$$%yuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu&$",
"$$=uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu;$",
"$$6uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu6$",
"$$quuuuur3333,:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::,ruuuuu7$",
"$$uuuuuu3                                                                                                                                                                                                                                                   3uuuuu7$",
"$$uuuuuu3                                                                                                                                                                                                                                                   3uuuuu7$",
"$$uuuuuu3                                                                                                                                                                                                                                                   3uuuuu7$",
"$$uuuuuu3                                                                                                                                                                                                                                                   3uuuuuy$",
"$$uuuuuu3                                                                                                                                                                                                                                                   3uuuuuu$",
"$$uuuuuu3                                                                                                                                                                                                                                                   3uuuuuu$",
"$$uuuuuu3                                                                                                                                                                                                                                                   3uuuuuu$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuuu$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuuu$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuuu$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuuu$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuuu$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuuu$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuuu$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuuu$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuuu$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuuu$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuuu$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuuu$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuuu$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuuu$",
"$$7uuuuu3                          o+>>+o      .OOOo   .X        XOOOX        O+>>#o       o.            XOOOX XOOX.OX            . oOX           o.                           oOOo       .X oX   OOOO  OOO oO   oOOOXOOo                                   3uuuuuu$",
"$$7uuuuu3                        @eiiiiiie>.   >iiit   iiiio     8iiii      >tiiiiiie+    OiiiiO         8iiiiiiiiiii>           >iiiiiiiiie>    OiiiiO               8iiii#   8iiii@     8iiii> Oiiiiiiiiiiii   iiiiiiiiii1o                               3uuuuuw$",
"$$7uuuuu3                       <iiiiiiiiii1   >iiii   iiiito    2iiii    .9iiiiiiiiii1   OiiiiO         8iiiiiiiiiii>           >iiiiiiiiiii1   OiiiiO              Xiiiiie   oiiiit.   @iiii9  Oiiiiiiiiiiii   iiiiiiiiiiii@                              3uuuuu7$",
"$$7uuuuu3                      Xiiiiiiiiiiio   >iiii   iiiii9.   1iiie   .9iiiiiiiiiii2   OiiiiO         8iiiiiiiiiii>           >iiiiiiiiiiii<  OiiiiO              <iiiiii@   >iiii<  .eiiiio  Oiiiiiiiiiiii   iiiiiiiiiiiitX                             3uuuuu7$",
"$$7uuuuu3                      >iiii>OO@1i#    >iiii   iiiiii2   8iii8   1iiiie@OO#ei2.   OiiiiO         8iiit<888888+           >iiii8889iiiiiX OiiiiO             .tiiiiii9   .eiiiio <iiii#   Oiiii22888882   iiii8>O>1iiii1                             3uuuuu7$",
"$$7uuuuu3                      >iii9     .     >iiii   iiiiiii#  2iii8  Xiiii9.     @     OiiiiO         8iii>                   >iiii    #iiii@ OiiiiO             >iiiiiiiiO   Oiiii9oiiii8    Oiiii           iiii>    2iiit                             3uuuuu7$",
"$$7uuuuu3                      >iiii2>OX       >iiii   iiiiiiiio <iii8  @iiiiO            OiiiiO         8iii<     X.            >iiii     iiii> OiiiiO            .tiii+<iii1    <iiiitiiiio    Oiiii.     o    iiii>    >iiii                             3uuuuu7$",
"$$7uuuuu3                      oiiiiiiii9>.    >iiii   iiiiiiiie.8iii8  1iiit   tiiiiii9  OiiiiO         8iiiiiiiiiii.           >iiii    Xiiii> OiiiiO            @iiie oiiii.   .tiiiiiii>     Oiiiiiiiiiii<   iiii>    9iii9                             3uuuuu7$",
"$$7uuuuu3                       1iiiiiiiiit@   >iiii   iiiieiiii2>iii8  8iii8   iiiiiiie  OiiiiO         8iiiiiiiiiiiO           >iiii+OO@eiiii+ OiiiiO            eiii>  eiii>    +iiiiii9      Oiiiiiiiiiii8   iiiit888tiiii>                             3uuuuu7$",
"$$7uuuuu3                        O8iiiiiiiiiO  >iiii   iiii><iiiiiiiii  8iii8   iiiiiii8  OiiiiO         8iiiiiiiiiiiO           >iiiiiiiiiiiie  OiiiiO           @iiiiX  <iiit     2iiiitX      Oiiiiiiiiiii8   iiiiiiiiiiii9                              3uuuuu7$",
"$$7uuuuu3                          X@><9iiii2  >iiii   iiii> 8iiiiiiii  >iiii.  #>>>iii8  OiiiiO         8iiie>>>>>>1.           >iiiiiiiiiiito  OiiiiO           8iiii8819iiii@    Xiiii>       Oiiii1>>>>><@   iiiiiiiiiit>.                              3uuuuu7$",
"$$7uuuuu3                        o      2iiit  >iiii   iiii> .eiiiiiii  @iiii#      iii8  OiiiiO         8iii<                   >iiiiiiiiii1X   OiiiiO          oiiiiiiiiiiiii8     iiii>       Oiiii.          iiii8>tiiit.                               3uuuuu7$",
"$$7uuuuu3                       <i>.    8iii9  >iiii   iiii>  Oiiiiiii  .tiiitO    Xiii8  OiiiiO     .X  8iii<                   >iiii>>>>+X     OiiiiO     .X   1iiiiiiiiiiiiiiO    iiii>       Oiiii.          iiii> Oiiii2                               3uuuuu7$",
"$$7uuuuu3                      @iiii888eiiii1  >iiii   iiii>   >iiiiie   >iiiii9><9iiii8  Oiiiiiiiiiii8  8iiiiiiiiiiit           >iiii           Oiiiiiiiiiii8  Xiiiiiiiiiiiiiii9    iiii>       Oiiiiiiiiiiii#  iiii>  <iiii#                              3uuuuu7$",
"$$7uuuuu3                      9iiiiiiiiiiiiX  >iiii   iiii>    2iiii8    8iiiiiiiiiiii>  Oiiiiiiiiiii8  8iiiiiiiiiiii           >iiii           Oiiiiiiiiiii8  >iiiio    OO>iiiiO   iiii>       Oiiiiiiiiiiii>  iiii>  .9iiiio                             3uuuuu7$",
"$$7uuuuu3                      .8iiiiiiiiit@   >iiii   iiii>    .eiii8     1iiiiiiiiii<   Oiiiiiiiiiiii  8iiiiiiiiiiit           >iiii           Oiiiiiiiiiiii  tiii2       .iiii1   iiii>       Oiiiiiiiiiiii#  iiii>   oiiiie.                            3uuuuu7$",
"$$7uuuuu3                        @9iiiii9<X    @888<   8888@     +888>      O1eiiii9<o    o888888888882  <88888888888<           +8881           o888888888882 X8888+        >8882   8888@       o888888888888o  8888@    @8888#                            3uuuuu7$",
"$$7uuuuu3                           Oo                                         XOo                                                                                                                                                                          3uuuuu7$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuu7$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuu7$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuu7$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuu7$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuu7$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuu7$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuu7$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuu7$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuu7$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuu7$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuu7$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuu7$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuu7$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuu7$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuu7$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuu7$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuu7$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuu7$",
"$$7uuuuu3                                                                                                                                                                                                                                                   3uuuuu7$",
"$$7uuuuuuuu0333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333ruuuuu7$",
"$$7uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu5$",
"$$4uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu;$",
"$$*uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu&$",
"$$$7uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu5$$",
"$$$%7uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu5%$$"
};
