/* XPM */
static xpm_row_t const btn_mp_hover[] = {
/* columns rows colors chars-per-pixel */
"260 72 37 1 ",
"  c #6D6D6D",
". c #767676",
"X c #7F7F7F",
"o c #00FF66",
"O c #10FF6F",
"+ c #20FF79",
"@ c #4FFE95",
"# c #5FFE9E",
"$ c #6EFEA8",
"% c #7EFEB1",
"& c #888888",
"* c #929292",
"= c #9B9B9B",
"- c #A4A4A4",
"; c #ADADAD",
": c #B5B5B5",
"> c #B6B6B6",
", c #BDBDBD",
"< c #BFBFBF",
"1 c #8EFDBA",
"2 c #9EFDC4",
"3 c #ADFDCD",
"4 c #BDFDD7",
"5 c #C8C8C8",
"6 c #D1D1D1",
"7 c #D8D8D8",
"8 c #DBDBDB",
"9 c #CDFDE0",
"0 c #DDFCE9",
"q c #E4E4E4",
"w c #EAEAEA",
"e c #EDEDED",
"r c #ECFCF3",
"t c #F3F3F3",
"y c #F6F6F6",
"u c #FCFCFC",
"i c #FFFFFF",
/* pixels */
"oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
"ooooo+1449uuuuuuur44444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444442$+oooo",
"oooo1uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu1ooo",
"ooo$uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu1oo",
"ooOruuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu+o",
"oo#uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu%o",
"oo3uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu3o",
"oo9uuuuut7777,:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::,tuuuuu4o",
"oouuuuuu7                                                                                                                                                                                                                                                   7uuuuu4o",
"oouuuuuu7                                                                                                                                                                                                                                                   7uuuuu4o",
"oouuuuuu7                                                                                                                                                                                                                                                   7uuuuu4o",
"oouuuuuu7                                                                                                                                                                                                                                                   7uuuuuro",
"oouuuuuu7                                                                                                                                                                                                                                                   7uuuuuuo",
"oouuuuuu7                                                                                                                                                                                                                                                   7uuuuuuo",
"oouuuuuu7                                                                                                                                                                                                                                                   7uuuuuuo",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuuuo",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuuuo",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuuuo",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuuuo",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuuuo",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuuuo",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuuuo",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuuuo",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuuuo",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuuuo",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuuuo",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuuuo",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuuuo",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuuuo",
"oo4uuuuu7                                   XX *&        .       ***&      ..      &.           &   X .***.  X***X   . X*&           .&                           .***.       & .*   &***. &**.X*.  .***&&**.                                               7uuuuuuo",
"oo4uuuuu7                                   8iiii-      &yiiii  *iiii*     8iii8  *iiii*     iiiiiiiiiiiiiq  8iii6  *iiiiiiiiiy5.    8iii8               *iiiiy   *iiiie     *iiiiy. iiiiiiiiiiii*  >iiiiiiiiie;                                            7uuuuu0o",
"oo4uuuuu7                                   8iiiii&    .eiiiiy  *iiii*     8iii8  *iiii*     iiiiiiiiiiiii8  8iii8  *iiiiiiiiiiiq.   8iii8               5iiiii-   6iiii>    eiiii=  iiiiiiiiiiii*  >iiiiiiiiiiiq.                                          7uuuuu4o",
"oo4uuuuu7                                   8iiiiiq.   qiiiiiy  *iiii*     8iii8  *iiii*     iiiiiiiiiiiii8  8iii8  *iiiiiiiiiiiiq   8iii8              .iiiiiie   .yiiiyX  ;iiii6   iiiiiiiiiiii*  >iiiiiiiiiiii<                                          7uuuuu4o",
"oo4uuuuu7                                   8iiiiii8  5iiiiiii  *iiii*     8iii8  *iiii*     <<568iiiiq866>  8iii8  *iiiiq888iiiii-  8iii8              >iiiiiii=   ;iiii6 Xyiiie.   iiiiq5888888X  >iiii>-->eiiiiX                                         7uuuuu4o",
"oo4uuuuu7                                   8iiiiiii<-iiiiiiii  *iiii*     8iii8  *iiii*         =iiii*      8iii8  *iiii*   &iiii5  8iii8             .yiiiiiii8    8iiii=6iiii*    iiii*          >iiii    &iiii;                                         7uuuuu4o",
"oo4uuuuu7                                   8iiiiiiiiiiiiiiiii  *iiii*     8iii8  *iiii*         *iiii.      8iii8  *iiii*    8iii8  8iii8             >iiiq.iiiiX   Xyiiiyiiii6     iiii=     &    >iiii     iiii>                                         7uuuuu4o",
"oo4uuuuu7                                   8iiiyiiiiiiiieiiii  *iiii*     8iii8  *iiii*         *iiii*      8iii8  *iiii*    eiii8  8iii8             eiii- 6iii<    >iiiiiiiy.     iiiiiiiiiiiq   >iiii    =iiii=                                         7uuuuu4o",
"oo4uuuuu7                                   8iii6-iiiiii<>iiii  *iiii*     8iii8  *iiii*         *iiii*      8iii8  *iiii>**=8iiii<  8iii8            -iiiy. -iiiy.    qiiiiii=      iiiiiiiiiiii   >iiiiq88qiiiiy.                                         7uuuuu4o",
"oo4uuuuu7                                   8iii> >iiii5 >iiii  *iiii*     8iii8  *iiii*         *iiii.      8iii8  *iiiiiiiiiiiiiX  8iii8            eiii5  .iiii;    &iiiii<       iiiiiiiiiiii   >iiiiiiiiiiii=                                          7uuuuu4o",
"oo4uuuuu7                                   8iii6  8iiq. >iiii  *iiii*     qiii8  *iiii*         *iiii       8iii8  *iiiiiiiiiiii-   8iii8           *iiiie88<iiiie     5iiii        iiii8>>>>>><   >iiiiiiiiii8*                                           7uuuuu4o",
"oo4uuuuu7                                   8iii8  .qy.  >iiii  &iiii>    Xiiii>  *iiii*         *iiii       8iii8  *iiiiiiiiii8*    8iii8           6iiiiiiiiiiiii*    >iiii        iiii=          >iiii>6iiii>                                            7uuuuu4o",
"oo4uuuuu7                                   8iii8    X   >iiii   yiiiy.  .6iiii=  *iiii*     .X  *iiii       8iii8  *iiii5>>>-&      8iii8      &   Xiiiiiiiiiiiiii8    >iiii        iiii=          >iiii  8iiii&                                           7uuuuu4o",
"oo4uuuuu7                                   8iii8        >iiiy   >iiiiy88yiiiiy   *iiiiiiiiiii8  *iiii       8iii8  *iiii*           8iiiiiiiiiii*  5iiiiiiiiiiiiiii=   >iiii        iiiiiiiiiiii6  >iiii  Xyiiie.                                          7uuuuu4o",
"oo4uuuuu7                                   8iii8        >iii8   .eiiiiiiiiiii;   *iiiiiiiiiii8  *iiii       8iii8  *iiii*           8iiiiiiiiiii* .yiii6    X**eiii8   >iiii        iiiiiiiiiiii8  >iiii   -iiii6                                          7uuuuu4o",
"oo4uuuuu7                                   8iii8        >iiiy    &eiiiiiiiii>    *iiiiiiiiiiii  *iiiiX      8iii8  *iiii*           8iiiiiiiiiii> ;iiii&       <iiiiX  >iiii        iiiiiiiiiiii6  >iiii    6iiii;                                         7uuuuu4o",
"oo4uuuuu7                                   <888>        -88q8     .>eiiiiy5X     &888888888886  &8888&      <888-  X8888.           <88888888888= >8886        X8888=  -8888        888888888888-  -8888    .68888.                                        7uuuuu4o",
"oo4uuuuu7                                                              .*.                                                                                                                                                                                  7uuuuu4o",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuu4o",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuu4o",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuu4o",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuu4o",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuu4o",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuu4o",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuu4o",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuu4o",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuu4o",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuu4o",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuu4o",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuu4o",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuu4o",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuu4o",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuu4o",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuu4o",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuu4o",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuu4o",
"oo4uuuuu7                                                                                                                                                                                                                                                   7uuuuu4o",
"oo4uuuuuuuuw777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777tuuuuu4o",
"oo4uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu2o",
"oo1uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu%o",
"oo@uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu+o",
"ooo4uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu2oo",
"oooO4uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu2Ooo"
};
