/* XPM */
static xpm_row_t const btn_sp[] = {
/* columns rows colors chars-per-pixel */
"260 72 37 1 ",
"  c #AD0000",
". c #B21010",
"X c #B72020",
"o c #BC3030",
"O c #C24040",
"+ c #C75050",
"@ c #CC6060",
"# c #D17070",
"$ c #D57E7E",
"% c #00FF66",
"& c #10FF6F",
"* c #20FF79",
"= c #4FFE95",
"- c #5FFE9E",
"; c #6EFEA8",
": c #7EFEB1",
"> c #D68080",
", c #D98E8E",
"< c #DB8F8F",
"1 c #E09F9F",
"2 c #E5AFAF",
"3 c #E8BDBD",
"4 c #EBBFBF",
"5 c #8EFDBA",
"6 c #9EFDC4",
"7 c #ADFDCD",
"8 c #BDFDD7",
"9 c #F0CFCF",
"0 c #F2DDDD",
"q c #F5DFDF",
"w c #CDFDE0",
"e c #DDFCE9",
"r c #F7ECEC",
"t c #FAEFEF",
"y c #ECFCF3",
"u c #FCFCFC",
"i c #FFFFFF",
/* pixels */
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%",
"%%%%%*588wuuuuuuuy88888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888886;*%%%%",
"%%%%5uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu5%%%",
"%%%;uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu5%%",
"%%&yuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu*%",
"%%-uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu:%",
"%%7uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu7%",
"%%wuuuuur3333,$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$,ruuuuu8%",
"%%uuuuuu3                                                                                                                                                                                                                                                   3uuuuu8%",
"%%uuuuuu3                                                                                                                                                                                                                                                   3uuuuu8%",
"%%uuuuuu3                                                                                                                                                                                                                                                   3uuuuu8%",
"%%uuuuuu3                                                                                                                                                                                                                                                   3uuuuuy%",
"%%uuuuuu3                                                                                                                                                                                                                                                   3uuuuuu%",
"%%uuuuuu3                                                                                                                                                                                                                                                   3uuuuuu%",
"%%uuuuuu3                                                                                                                                                                                                                                                   3uuuuuu%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuuu%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuuu%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuuu%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuuu%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuuu%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuuu%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuuu%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuuu%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuuu%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuuu%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuuu%",
"%%8uuuuu3                             o+>>+o      XOOOX   X.        oOOO.        O+>>#o       O             oOOO. oOO.XO.            . OO.           O                            oOOo       .X oX  .OOOo .OOo Oo   oOOOXOOo                                3uuuuuu%",
"%%8uuuuu3                           @qiiiiiiq>.   4iii2  Oiiiq.     iiii4      >tiiiiiiq+    >iiii          iiiiiiiiiiiiO           4iiiiiiiii9+    >iiii                4iiii#   4iiii@     4iiii> >iiiiiiiiiii4   iiiiiiiiii1o                            3uuuuuu%",
"%%8uuuuu3                          <iiiiiiiiii1   4iii4  Oiiii9.    tiii4    .9iiiiiiiiii1   >iiii          iiiiiiiiiiiiO           4iiiiiiiiiii@   >iiii               Xiiiiiq   oiiiit.   @iiii9  >iiiiiiiiiii4   iiiiiiiiiiii@                           3uuuuuu%",
"%%8uuuuu3                         Xiiiiiiiiiiio   4iii4  Oiiiii1    qiii1   .9iiiiiiiiiii2   >iiii          iiiiiiiiiiiiO           4iiiiiiiiiiii+  >iiii               <iiiiii@   >iiii<  .qiiiio  >iiiiiiiiiii4   iiiiiiiiiiiitX                          3uuuuuu%",
"%%8uuuuu3                         >iiii>OO@1i#    4iii4  Oiiiiii#   iiii>   1iiiiq@OO#qi2.   >iiii          iiii91444444X           4iiit444qiiiiq  >iiii              .tiiiiii9   .qiiiio <iiii#   >iiii<444444>   iiii4>O>1iiii1                          3uuuuue%",
"%%8uuuuu3                         >iii9     .     4iii4  Oiiiiiiio  tiii>  Xiiii9.     @     >iiii          iiiiO                   4iii4    2iiiiX >iiii              >iiiiiiiiO   Oiiii9oiiii4    >iii4           iiii>    2iiit                          3uuuuu8%",
"%%8uuuuu3                         >iiii2>OX       4iii4  Oiiiiiiiq. 9iii>  @iiiiO            >iiii          iiii+     o             4iii4    OiiiiO >iiii             .tiii+<iii1    <iiiitiiiio    >iii9     .X    iiii>    >iiii                          3uuuuu8%",
"%%8uuuuu3                         oiiiiiiii9>.    4iii4  Oiiiiiiii2 iiii>  1iiit   tiiiiii9  >iiii          iiiiiiiiiii9            4iii4    @iiiiO >iiii             @iiiq oiiii.   .tiiiiiii>     >iiiiiiiiiii+   iiii>    9iii9                          3uuuuu8%",
"%%8uuuuu3                          1iiiiiiiiit@   4iii4  Oiiiiqiiii#4iii>  4iii4   iiiiiiiq  >iiii          iiiiiiiiiiii            4iiiqOOO>tiiii. >iiii             qiii>  qiii>    +iiiiii9      >iiiiiiiiiii>   iiiit444tiiii>                          3uuuuu8%",
"%%8uuuuu3                           O4iiiiiiiiiO  4iii4  OiiiiO9iiiiiiii4  4iii4   iiiiiii4  >iiii          iiiiiiiiiiii            4iiiiiiiiiiii1  >iiii            @iiiiX  <iiit     2iiiitX      >iiiiiiiiiii>   iiiiiiiiiiii9                           3uuuuu8%",
"%%8uuuuu3                             X@><9iiii2  4iii4  OiiiiO.tiiiiiii4  >iiii.  #>>>iii4  >iiii          iiii4>>>>>><            4iiiiiiiiiii9.  >iiii            4iiii4419iiii@    Xiiii>       >iiii>>>>>>1o   iiiiiiiiiit>.                           3uuuuu8%",
"%%8uuuuu3                           o      2iiit  4iii4  OiiiiO oiiiiiii4  @iiii#      iii4  >iiii          iiii+                   4iiiiiiiiit>.   >iiii           oiiiiiiiiiiiii4     iiii>       >iii9           iiii4>tiiit.                            3uuuuu8%",
"%%8uuuuu3                          <i>.    4iii9  4iii4  OiiiiO  >iiiiii4  .tiiitO    Xiii4  >iiii      X.  iiii+                   4iiiq>>>>O.     >iiii      X.   1iiiiiiiiiiiiiiO    iiii>       >iii9           iiii> Oiiii2                            3uuuuu8%",
"%%8uuuuu3                         @iiii444qiiii1  4iii4  OiiiiO   4iiiii1   >iiiii9><9iiii4  >iiiiiiiiiii>  iiiiiiiiiiii2           4iii4           >iiiiiiiiiii>  Xiiiiiiiiiiiiiii9    iiii>       >iiiiiiiiiiiio  iiii>  <iiii#                           3uuuuu8%",
"%%8uuuuu3                         9iiiiiiiiiiiiX  4iii4  OiiiiO   .qiiii>    4iiiiiiiiiiii>  >iiiiiiiiiii>  iiiiiiiiiiii4           4iii4           >iiiiiiiiiii>  >iiiio    OO>iiiiO   iiii>       >iiiiiiiiiiiiO  iiii>  .9iiiio                          3uuuuu8%",
"%%8uuuuu3                         .4iiiiiiiiit@   4iii4  OiiiiO    oiiii>     1iiiiiiiiii<   >iiiiiiiiiii4  iiiiiiiiiiii2           4iii4           >iiiiiiiiiii4  tiii2       .iiii1   iiii>       >iiiiiiiiiiiio  iiii>   oiiiiq.                         3uuuuu8%",
"%%8uuuuu3                           @9iiiii9<X    <444@  o4444o     >444+      O1qiiii9<o    @44444444444>  444444444444@           >444#           @44444444444> X4444+        >4442   4444@       @444444444444   4444@    @4444#                         3uuuuu8%",
"%%8uuuuu3                              Oo                                         XOo                                                                                                                                                                       3uuuuu8%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuu8%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuu8%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuu8%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuu8%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuu8%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuu8%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuu8%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuu8%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuu8%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuu8%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuu8%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuu8%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuu8%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuu8%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuu8%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuu8%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuu8%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuu8%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuu8%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuu8%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuu8%",
"%%8uuuuu3                                                                                                                                                                                                                                                   3uuuuu8%",
"%%8uuuuuuuu0333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333ruuuuu8%",
"%%8uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu6%",
"%%5uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu:%",
"%%=uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu*%",
"%%%8uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu6%%",
"%%%&8uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu6&%%"
};
