/* XPM */
static xpm_row_t const btn_done_hover[] = {
/* columns rows colors chars-per-pixel */
"222 49 49 1 ",
"  c #6AD10F",
". c #73D41E",
"X c #7DD72D",
"o c #00FF66",
"O c #10FF6F",
"+ c #20FF79",
"@ c #86DA3C",
"# c #8FDC4A",
"$ c #8FDD4B",
"% c #98DE59",
"& c #99DF5A",
"* c #A2E269",
"= c #AAE477",
"- c #ABE578",
"; c #3FFE8C",
": c #40FF8C",
"> c #4FFE95",
", c #5FFE9E",
"< c #5FFF9F",
"1 c #6EFEA8",
"2 c #6FFEA9",
"3 c #7EFEB1",
"4 c #7FFEB2",
"5 c #7FFFB2",
"6 c #B3E786",
"7 c #B5E887",
"8 c #BCE994",
"9 c #BEEB96",
"0 c #8EFDBA",
"q c #C5ECA3",
"w c #C7EEA5",
"e c #CEEFB2",
"r c #D0F1B4",
"t c #9EFDC4",
"y c #9FFFC5",
"u c #ADFDCD",
"i c #BDFDD7",
"p c #D8F1C1",
"a c #DAF4C3",
"s c #E3F6D2",
"d c #EAF7DE",
"f c #CDFDE0",
"g c #DDFCE9",
"h c #ECF9E1",
"j c #F3F9ED",
"k c #ECFCF3",
"l c #F6FCF0",
"z c #FCFCFC",
"x c #FFFFFF",
/* pixels */
"5ooo+155tiiiiiiiiiziiiiiiiiiiiii044444333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333555553333333333333333333333333333333333333333333333333333333333333333333333333333333333333>Ooo",
"5oOuzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzk,o",
"5ouzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz;",
"5;zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzu",
"5tzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
"5fzzzz8#=6666666666666666666666666666677666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666777666666666666666666666666666666666666666666666666666666666666666666666666666666666dzzzz",
"5zzzzz#                                                                                                                                                                                                                  6zzzz",
"5zzzzz                                                                                                                                                                                                                   6zzzz",
"5zzzzz                                                                                                                                                                                                                   #zzzz",
"5zzzzz                                                                                                                                                                                                                   #zzzz",
"5zzzzz                                                                                                                                                                                                                   %zzzz",
"5zzzzz                                                                                                                                                                                                                   6zzzz",
"5zzzzz                                                                                                                                                                                                                   6zzzz",
"5zzzzz                                                                                                                                                                                                                   6zzzz",
"5izzzz                                                                                                                                                                                                                   ezzzz",
"5izzzz                                                                                                                                                                                                                   azzzz",
"5izzzz                                                                   Xeaaaaaaaw7@           @9azzzzsw$      XaaarX     Xraaa7   raaaaaaaaaaaaX                                                                       rzzzz",
"5izzzz                                                                   $zzzzzzzzzzzh$       XrzzzzzzzzzzrX    #zzzzs.    #zzzza   zzzzzzzzzzzzz#                                                                       pzzzz",
"5izzzz                                                                   $zzzzzzzzzzzzz7     @jzzzzzzzzzzzzsX   $zzzzzw    .zzzza   zzzzzzzzzzzzz$                                                                       pzzzz",
"5izzzz                                                                   $zzzzzzzzzzzzzz6   .jzzzzzzzzzzzzzzr   $zzzzzz*   @zzzza   zzzzzzzzzzzzz$                                                                       pzzzz",
"5izzzz                                                                   $zzzzr$$$=dzzzzlX  7zzzzzw@  @ezzzzz&  @zzzzzzz@  #zzzza   zzzzh$$77&*7-X                                                                       pzzzz",
"5izzzz                                                                   $zzzz7    Xszzzz*  hzzzz*      wzzzzh  $zzzzzzzd. Xzzzza   zzzza                                                                                pzzzz",
"5izzzz                                                                   $zzzz7     $zzzzw @zzzza       Xlzzzz. $zzzzzzzzr Xzzzza   zzzzs@$$$$$$X                                                                        pzzzz",
"5izzzz                                                                   $zzzz7      zzzza 7zzzz-        rzzzz#  zzzzzzzzz-@zzzza   zzzzzzzzzzzzr                                                                        pzzzz",
"5izzzz                                                                   #zzzz7      zzzzs 7zzzz$        7zzzz# Xzzzzhlzzzz$zzzza   zzzzzzzzzzzza                                                                        pzzzz",
"5izzzz                                                                   #zzzz7      zzzzl 7zzzz&        wzzzz# #zzzz7*zzzzzzzzza   zzzzzzzzzzzza                                                                        pzzzz",
"5izzzz                                                                   $zzzz7     @zzzzr &zzzz9        szzzz@ #zzzz7 wzzzzzzzza   zzzzl7raar9a7                                                                        pzzzz",
"5izzzz                                                                   $zzzz7     rzzzz= @zzzzl@      $zzzzz  $zzzz7  azzzzzzza   zzzza                                                                                pzzzz",
"5izzzz                                                                   $zzzz7   @qzzzzz@  szzzzs@    @lzzzze  $zzzz7  @lzzzzzza   zzzza                                                                                pzzzz",
"5izzzz                                                                   $zzzzlahzzzzzzzq   *zzzzzzr66wzzzzzz@  $zzzz7   *zzzzzza   zzzzlaaaaaaaa*                                                                       pzzzz",
"5izzzz                                                                   $zzzzzzzzzzzzzs.    wzzzzzzzzzzzzzz7   $zzzz7    9zzzzza   zzzzzzzzzzzzz7                                                                       pzzzz",
"5izzzz                                                                   $zzzzzzzzzzzzaX      wzzzzzzzzzzzz9    $zzzz8     azzzza   zzzzzzzzzzzzz7                                                                       pzzzz",
"5izzzz                                                                   $zzzzzzzzzzr*         #azzzzzzzzs$     $zzzza     Xzzzzw   zzzzzzzzzzzzz7                                                                       pzzzz",
"5izzzz                                                                    $$$$$#$$X              @=qaar-X       .$$$#@      X$$$.   $$$$$$$$$$$$#X                                                                       pzzzz",
"5izzzz                                                                                                                                                                                                                   pzzzz",
"5izzzz                                                                                                                                                                                                                   pzzzz",
"5izzzz                                                                                                                                                                                                                   pzzzz",
"5gzzzz                                                                                                                                                                                                                   pzzzz",
"5zzzzz                                                                                                                                                                                                                   pzzzz",
"5zzzzz                                                                                                                                                                                                                   pzzzz",
"5zzzzz                                                                                                                                                                                                                   azzzz",
"5zzzzz                                                                                                                                                                                                                   rzzzz",
"5zzzzz                                                                                                                                                                                                                   pzzzz",
"5izzzzqppppppppppppppppppppppparppppppppppppppppppppppppppppppppaaapppppppppppppaaappppppppppppppaaappppppppppppppppppppaaapppppppppppppppppppppaaarpppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppjzzzz",
"5uzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzk",
"5,zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzt",
"5oizzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzk+",
"5oo5gzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzu+o",
"t:::::1031;;;;;;;;;;;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::1;;;;"
};
