/* XPM */
static xpm_row_t const btn_ex[] = {
/* columns rows colors chars-per-pixel */
"260 72 37 1 ",
"  c #111111",
". c #202020",
"X c #2F2F2F",
"o c #3E3E3E",
"O c #4D4D4D",
"+ c #5B5B5B",
"@ c #6A6A6A",
"# c #797979",
"$ c #00FF66",
"% c #10FF6F",
"& c #20FF79",
"* c #4FFE95",
"= c #5FFE9E",
"- c #6EFEA8",
"; c #7EFEB1",
": c #878787",
"> c #888888",
", c #959595",
"< c #979797",
"1 c #A6A6A6",
"2 c #B5B5B5",
"3 c #8EFDBA",
"4 c #9EFDC4",
"5 c #ADFDCD",
"6 c #BDFDD7",
"7 c #C1C1C1",
"8 c #C4C4C4",
"9 c #D2D2D2",
"0 c #DFDFDF",
"q c #CDFDE0",
"w c #DDFCE9",
"e c #E1E1E1",
"r c #EDEDED",
"t c #ECFCF3",
"y c #F0F0F0",
"u c #FCFCFC",
"i c #FFFFFF",
/* pixels */
"$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
"$$$$$&366quuuuuuut66666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666664-&$$$$",
"$$$$3uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu3$$$",
"$$$-uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu3$$",
"$$%tuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu&$",
"$$=uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu;$",
"$$5uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu5$",
"$$quuuuur7777,:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::,ruuuuu6$",
"$$uuuuuu7                                                                                                                                                                                                                                                   7uuuuu6$",
"$$uuuuuu7                                                                                                                                                                                                                                                   7uuuuu6$",
"$$uuuuuu7                                                                                                                                                                                                                                                   7uuuuu6$",
"$$uuuuuu7                                                                                                                                                                                                                                                   7uuuuut$",
"$$uuuuuu7                                                                                                                                                                                                                                                   7uuuuuu$",
"$$uuuuuu7                                                                                                                                                                                                                                                   7uuuuuu$",
"$$uuuuuu7                                                                                                                                                                                                                                                   7uuuuuu$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu$",
"$$6uuuuu7                                                                                            OOOO  OOO oO      o      .       OOOO     X.  X  OOOX                                                                                                  7uuuuuu$",
"$$6uuuuu7                                                                                           Oiiiiiiiiiiii  +iiii2    Xyiiie  Oiiiio 8iiiiiiiiiiiii.                                                                                                 7uuuuuw$",
"$$6uuuuu7                                                                                           Oiiiiiiiiiiii   <iiiiO   2iiiiO  OiiiiO 8iiiiiiiiiiiii                                                                                                  7uuuuu6$",
"$$6uuuuu7                                                                                           Oiiiiiiiiiiii   .yiiie  +iiii>   OiiiiO 8iiiiiiiiiiiii                                                                                                  7uuuuu6$",
"$$6uuuuu7                                                                                           Oiiii22888882    +iiii@ 8iii9    OiiiiO @1<81iiiie8812                                                                                                  7uuuuu6$",
"$$6uuuuu7                                                                                           Oiiii             1iiie>iiiiO    OiiiiO     .iiii>                                                                                                      7uuuuu6$",
"$$6uuuuu7                                                                                           Oiiii.     o      .yiiiiiii<     OiiiiO      iiii+                                                                                                      7uuuuu6$",
"$$6uuuuu7                                                                                           Oiiiiiiiiiii<      @iiiiiie.     OiiiiO      iiii>                                                                                                      7uuuuu6$",
"$$6uuuuu7                                                                                           Oiiiiiiiiiii8       2iiiii+      OiiiiO      iiii>                                                                                                      7uuuuu6$",
"$$6uuuuu7                                                                                           Oiiiiiiiiiii8      .eiiiii<      OiiiiO      iiii+                                                                                                      7uuuuu6$",
"$$6uuuuu7                                                                                           Oiiii1>>>>><@      <iiiiiiiO     OiiiiO      iiiiO                                                                                                      7uuuuu6$",
"$$6uuuuu7                                                                                           Oiiii.            Oiiiiyiiie.    OiiiiO      iiiiO                                                                                                      7uuuuu6$",
"$$6uuuuu7                                                                                           Oiiii.           .yiii8Oiiii<    OiiiiO      iiiiO                                                                                                      7uuuuu6$",
"$$6uuuuu7                                                                                           Oiiiiiiiiiiii#   2iiiiX <iiiiO   OiiiiO      iiiiO                                                                                                      7uuuuu6$",
"$$6uuuuu7                                                                                           Oiiiiiiiiiiii>  +iiii1  .yiiie.  OiiiiO      iiiiO                                                                                                      7uuuuu6$",
"$$6uuuuu7                                                                                           Oiiiiiiiiiiii# .yiiie.   @iiii2  OiiiiO      iiii@                                                                                                      7uuuuu6$",
"$$6uuuuu7                                                                                           o888888888888o >8888O     <8888X o8888       8888@                                                                                                      7uuuuu6$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6$",
"$$6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6$",
"$$6uuuuuuuu0777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777ruuuuu6$",
"$$6uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu4$",
"$$3uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu;$",
"$$*uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu&$",
"$$$6uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu4$$",
"$$$%6uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu4%$$"
};
