/* XPM */
static xpm_row_t const btn_done[] = {
/* columns rows colors chars-per-pixel */
"222 49 49 1 ",
"  c #52B208",
". c #5DB717",
"X c #68BC27",
"o c #72C036",
"O c #00FF66",
"+ c #10FF6F",
"@ c #20FF79",
"# c #7DC545",
"$ c #7DC546",
"% c #87C954",
"& c #88CA55",
"* c #93CF65",
"= c #9CD273",
"- c #9ED474",
"; c #3FFE8C",
": c #40FF8C",
"> c #4FFE95",
", c #5FFE9E",
"< c #5FFF9F",
"1 c #6EFEA8",
"2 c #6FFEA9",
"3 c #7EFEB1",
"4 c #7FFEB2",
"5 c #7FFFB2",
"6 c #A7D782",
"7 c #A9D984",
"8 c #B2DC91",
"9 c #B3DD93",
"0 c #8EFDBA",
"q c #BCE0A1",
"w c #BEE2A2",
"e c #C7E5B0",
"r c #C9E7B2",
"t c #D2EABF",
"y c #9EFDC4",
"u c #9FFFC5",
"i c #ADFDCD",
"p c #BDFDD7",
"a c #D4ECC1",
"s c #DFF1D1",
"d c #E7F3DE",
"f c #CDFDE0",
"g c #DDFCE9",
"h c #E9F5E0",
"j c #F1F7ED",
"k c #ECFCF3",
"l c #F4FAF0",
"z c #FCFCFC",
"x c #FFFFFF",
/* pixels */
"5OOO@155ypppppppppzppppppppppppp055553333333333333333333333333333333333333333333533333333333333333333333333333333333333333333333555333333333333333333333333333333333333333333333333333333333333333333333333333333333333333>+OO",
"5O+izzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzk,O",
"5Oizzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz;",
"5;zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzi",
"5yzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
"5fzzzz8#=666666666666666666666666666677-666666666666666666666666666666666666666666666777666666666666666666666666666666666666666666666777666666666666666666666666666666666666666666666666666666666666666666666666666666666dzzzz",
"5zzzzz#                                                                                                                                                                                                                  6zzzz",
"5zzzzz                                                                                                                                                                                                                   6zzzz",
"5zzzzz                                                                                                                                                                                                                   #zzzz",
"5zzzzz                                                                                                                                                                                                                   #zzzz",
"5zzzzz                                                                                                                                                                                                                   %zzzz",
"5zzzzz                                                                                                                                                                                                                   6zzzz",
"5zzzzz                                                                                                                                                                                                                   6zzzz",
"5zzzzz                                                                                                                                                                                                                   6zzzz",
"5pzzzz                                                                                                                                                                                                                   ezzzz",
"5pzzzz                                                                                                                                                                                                                   tzzzz",
"5pzzzz                                                                   .eaaaaaaae6o           o9azzzzdw#      Xaaar.     Xtaaa7   raaaaaaaaaaaaX                                                                       tzzzz",
"5pzzzz                                                                   #zzzzzzzzzzzd#       .rzzzzzzzzzzt.    #zzzzd.    #zzzza   zzzzzzzzzzzzz#                                                                       tzzzz",
"5pzzzz                                                                   #zzzzzzzzzzzzz7     olzzzzzzzzzzzzd.   %zzzzze    .zzzza   zzzzzzzzzzzzz$                                                                       tzzzz",
"5pzzzz                                                                   %zzzzzzzzzzzzzz7   .lzzzzzzzzzzzzzza   #zzzzzz*   ozzzza   zzzzzzzzzzzzz$                                                                       tzzzz",
"5pzzzz                                                                   #zzzze%##-dzzzzl.  7zzzzzeo  orzzzzz&  ozzzzzzzo  %zzzza   zzzzh%#67%*--.                                                                       tzzzz",
"5pzzzz                                                                   #zzzz7    .dzzzz*  hzzzz*      ezzzzh  #zzzzzzzd. Xzzzza   zzzzt                                                                                tzzzz",
"5pzzzz                                                                   #zzzz7     %zzzze ozzzzt       .lzzzz. #zzzzzzzzr .zzzza   zzzzso#%###%X                                                                        tzzzz",
"5pzzzz                                                                   %zzzz7      zzzza 7zzzz-        rzzzz#  zzzzzzzzz-ozzzza   zzzzzzzzzzzza                                                                        tzzzz",
"5pzzzz                                                                   #zzzz7      zzzzd 7zzzz#        7zzzz# .zzzzdlzzzz%zzzza   zzzzzzzzzzzza                                                                        tzzzz",
"5pzzzz                                                                   #zzzz7      zzzzl 7zzzz%        qzzzz% %zzzz7*zzzzzzzzza   zzzzzzzzzzzza                                                                        tzzzz",
"5pzzzz                                                                   #zzzz7     Xzzzzt %zzzz9        szzzzX #zzzz7 ezzzzzzzza   zzzzl7raar9a7                                                                        tzzzz",
"5pzzzz                                                                   %zzzz7     rzzzz- XzzzzlX      %zzzzz  #zzzz7  azzzzzzza   zzzza                                                                                tzzzz",
"5pzzzz                                                                   #zzzz7   XezzzzzX  szzzzdo    olzzzze  #zzzz7  Xlzzzzzza   zzzza                                                                                tzzzz",
"5pzzzz                                                                   #zzzzladzzzzzzze   *zzzzzzr77wzzzzzzX  #zzzz7   *zzzzzza   zzzzlaaaaaaaa*                                                                       tzzzz",
"5pzzzz                                                                   #zzzzzzzzzzzzzd.    wzzzzzzzzzzzzzz7   %zzzz7    9zzzzza   zzzzzzzzzzzzz7                                                                       tzzzz",
"5pzzzz                                                                   #zzzzzzzzzzzza.      ezzzzzzzzzzzz9    #zzzz9     azzzza   zzzzzzzzzzzzz7                                                                       tzzzz",
"5pzzzz                                                                   #zzzzzzzzzzr*         #azzzzzzzzd#     #zzzza     Xzzzzw   zzzzzzzzzzzzz7                                                                       tzzzz",
"5pzzzz                                                                    ##%$$##%X              X-eaar-X       .###$X      X%##.   $$$$%###$$%##.                                                                       tzzzz",
"5pzzzz                                                                                                                                                                                                                   tzzzz",
"5pzzzz                                                                                                                                                                                                                   tzzzz",
"5pzzzz                                                                                                                                                                                                                   tzzzz",
"5gzzzz                                                                                                                                                                                                                   tzzzz",
"5zzzzz                                                                                                                                                                                                                   tzzzz",
"5zzzzz                                                                                                                                                                                                                   tzzzz",
"5zzzzz                                                                                                                                                                                                                   tzzzz",
"5zzzzz                                                                                                                                                                                                                   tzzzz",
"5zzzzz                                                                                                                                                                                                                   tzzzz",
"5pzzzzqttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttaaattttttttttttttttttttattttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttjzzzz",
"5izzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzk",
"5,zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzy",
"5Opzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzk@",
"5OO5gzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzi@O",
"y:::::1031;;;;;;;;;;;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::,::::"
};
