/* XPM */
static xpm_row_t const btn_ex_hover[] = {
/* columns rows colors chars-per-pixel */
"260 72 37 1 ",
"  c #2D2D2D",
". c #3A3A3A",
"X c #474747",
"o c #545454",
"O c #626262",
"+ c #6F6F6F",
"@ c #7C7C7C",
"# c #00FF66",
"$ c #10FF6F",
"% c #20FF79",
"& c #4FFE95",
"* c #5FFE9E",
"= c #6EFEA8",
"- c #7EFEB1",
"; c #898989",
": c #959595",
"> c #969696",
", c #A1A1A1",
"< c #A3A3A3",
"1 c #B0B0B0",
"2 c #BDBDBD",
"3 c #8EFDBA",
"4 c #9EFDC4",
"5 c #ADFDCD",
"6 c #BDFDD7",
"7 c #C8C8C8",
"8 c #CBCBCB",
"9 c #D8D8D8",
"0 c #CDFDE0",
"q c #DDFCE9",
"w c #E2E2E2",
"e c #E5E5E5",
"r c #EFEFEF",
"t c #ECFCF3",
"y c #F2F2F2",
"u c #FCFCFC",
"i c #FFFFFF",
/* pixels */
"####################################################################################################################################################################################################################################################################",
"#####%3660uuuuuuut66666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666664=%####",
"####3uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu3###",
"###=uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu3##",
"##$tuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu%#",
"##*uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu-#",
"##5uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu5#",
"##0uuuuur7777,:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::,ruuuuu6#",
"##uuuuuu7                                                                                                                                                                                                                                                   7uuuuu6#",
"##uuuuuu7                                                                                                                                                                                                                                                   7uuuuu6#",
"##uuuuuu7                                                                                                                                                                                                                                                   7uuuuu6#",
"##uuuuuu7                                                                                                                                                                                                                                                   7uuuuut#",
"##uuuuuu7                                                                                                                                                                                                                                                   7uuuuuu#",
"##uuuuuu7                                                                                                                                                                                                                                                   7uuuuuu#",
"##uuuuuu7                                                                                                                                                                                                                                                   7uuuuuu#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuuu#",
"##6uuuuu7                                                                                            OOOO  OOO oO      o      .       OOOO     X.  X  OOOX                                                                                                  7uuuuuu#",
"##6uuuuu7                                                                                           Oiiiiiiiiiiii  +iiii2    Xyiiie  Oiiiio 8iiiiiiiiiiiii.                                                                                                 7uuuuuq#",
"##6uuuuu7                                                                                           Oiiiiiiiiiiii   <iiiiO   2iiiiO  OiiiiO 8iiiiiiiiiiiii                                                                                                  7uuuuu6#",
"##6uuuuu7                                                                                           Oiiiiiiiiiiii   .yiiie  +iiii>   OiiiiO 8iiiiiiiiiiiii                                                                                                  7uuuuu6#",
"##6uuuuu7                                                                                           Oiiii22888882    +iiii@ 8iii9    OiiiiO @1<81iiiie8812                                                                                                  7uuuuu6#",
"##6uuuuu7                                                                                           Oiiii             1iiie>iiiiO    OiiiiO     .iiii>                                                                                                      7uuuuu6#",
"##6uuuuu7                                                                                           Oiiii.     o      .yiiiiiii<     OiiiiO      iiii+                                                                                                      7uuuuu6#",
"##6uuuuu7                                                                                           Oiiiiiiiiiii<      @iiiiiie.     OiiiiO      iiii>                                                                                                      7uuuuu6#",
"##6uuuuu7                                                                                           Oiiiiiiiiiii8       2iiiii+      OiiiiO      iiii>                                                                                                      7uuuuu6#",
"##6uuuuu7                                                                                           Oiiiiiiiiiii8      .eiiiii<      OiiiiO      iiii+                                                                                                      7uuuuu6#",
"##6uuuuu7                                                                                           Oiiii1>>>>><@      <iiiiiiiO     OiiiiO      iiiiO                                                                                                      7uuuuu6#",
"##6uuuuu7                                                                                           Oiiii.            Oiiiiyiiie.    OiiiiO      iiiiO                                                                                                      7uuuuu6#",
"##6uuuuu7                                                                                           Oiiii.           .yiii8Oiiii<    OiiiiO      iiiiO                                                                                                      7uuuuu6#",
"##6uuuuu7                                                                                           Oiiiiiiiiiiii;   2iiiiX <iiiiO   OiiiiO      iiiiO                                                                                                      7uuuuu6#",
"##6uuuuu7                                                                                           Oiiiiiiiiiiii>  +iiii1  .yiiie.  OiiiiO      iiiiO                                                                                                      7uuuuu6#",
"##6uuuuu7                                                                                           Oiiiiiiiiiiii; .yiiie.   @iiii2  OiiiiO      iiii@                                                                                                      7uuuuu6#",
"##6uuuuu7                                                                                           o888888888888o >8888O     <8888X o8888       8888@                                                                                                      7uuuuu6#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6#",
"##6uuuuu7                                                                                                                                                                                                                                                   7uuuuu6#",
"##6uuuuuuuuw777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777ruuuuu6#",
"##6uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu4#",
"##3uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu-#",
"##&uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu%#",
"###6uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu4##",
"###$6uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu4$##"
};
