/* XPM */
static xpm_row_t const rtc_0[] = {
/* columns rows colors chars-per-pixel */
"20 30 55 1 ",
"  c #00FF66",
". c #05FF69",
"X c #08FF6B",
"o c #0BFF6D",
"O c #0CFF6D",
"+ c #10FF70",
"@ c #18FF74",
"# c #1DFF77",
"$ c #26FF7D",
"% c #2FFF82",
"& c #36FF86",
"* c #43FF8E",
"= c #46FF90",
"- c #48FF91",
"; c #4FFF95",
": c #50FF96",
"> c #52FF97",
", c #57FF9A",
"< c #5EFF9E",
"1 c #60FFA0",
"2 c #67FFA4",
"3 c #69FFA5",
"4 c #6AFFA6",
"5 c #70FFA9",
"6 c #7BFFB0",
"7 c #7CFFB0",
"8 c #84FFB5",
"9 c #8EFFBB",
"0 c #8FFFBC",
"q c #A5FFC9",
"w c #A8FFCB",
"e c #ACFFCD",
"r c #ADFFCE",
"t c #B3FFD1",
"y c #B5FFD3",
"u c #BAFFD6",
"i c #BCFFD7",
"p c #BFFFD9",
"a c #C0FFD9",
"s c #C4FFDC",
"d c #C5FFDC",
"f c #CEFFE2",
"g c #D2FFE4",
"h c #DBFFE9",
"j c #DEFFEB",
"k c #E3FFEE",
"l c #E6FFF0",
"z c #E8FFF1",
"x c #EFFFF5",
"c c #F2FFF7",
"v c #F4FFF8",
"b c #F7FFFA",
"n c #F9FFFB",
"m c #FAFFFC",
"M c #FFFFFF",
/* pixels */
"      O4aknkp4+     ",
"     *lMMMMMMMl-    ",
"    <MMMMMMMMMMM,   ",
"   &bMMMz050zMMMb&  ",
"   fMMMu+   +uMMMs  ",
"  >MMMhO     OjMMM- ",
"  iMMM,       1MMMy ",
" +nMMx.       .cMMnO",
" ,MMMq         rMMM;",
" 8MMM5         6MMM6",
" rMMM-         >MMMr",
" gMMM&         &MMMf",
" kMMM$         #MMMk",
" xMMM@         +MMMz",
" nMMMo         .MMMn",
" nMMMo         .MMMn",
" xMMM@         +MMMz",
" kMMM$         #MMMk",
" gMMM&         &MMMf",
" eMMM*         ;MMMw",
" 8MMM5         6MMM8",
" ,MMMq         rMMM;",
" OnMMv.       XcMMbO",
"  uMMM,       1MMMt ",
"  >MMMho     ojMMM- ",
"   fMMMtO   OyMMMs  ",
"   &bMMMk950lMMMb%  ",
"    <MMMMMMMMMMn,   ",
"     *lMMMMMMMz=    ",
"      O4pknkp2O     "
};
