/* XPM */
static xpm_row_t const rtc_8[] = {
/* columns rows colors chars-per-pixel */
"20 30 128 2 ",
"   c #00FF66",
".  c #01FF67",
"X  c #02FF67",
"o  c #03FF68",
"O  c #04FF68",
"+  c #05FF69",
"@  c #07FF6A",
"#  c #08FF6B",
"$  c #0AFF6C",
"%  c #0BFF6D",
"&  c #0CFF6D",
"*  c #0DFF6E",
"=  c #0FFF6F",
"-  c #10FF70",
";  c #12FF71",
":  c #13FF71",
">  c #14FF72",
",  c #15FF73",
"<  c #18FF74",
"1  c #19FF75",
"2  c #1BFF76",
"3  c #1CFF77",
"4  c #1DFF77",
"5  c #1EFF78",
"6  c #25FF7C",
"7  c #27FF7D",
"8  c #2BFF80",
"9  c #2DFF81",
"0  c #2EFF82",
"q  c #2FFF82",
"w  c #30FF83",
"e  c #33FF85",
"r  c #38FF88",
"t  c #3AFF89",
"y  c #3DFF8B",
"u  c #3EFF8B",
"i  c #40FF8C",
"p  c #42FF8E",
"a  c #46FF90",
"s  c #47FF91",
"d  c #48FF91",
"f  c #4EFF95",
"g  c #4FFF95",
"h  c #50FF96",
"j  c #52FF97",
"k  c #53FF98",
"l  c #54FF98",
"z  c #5AFF9C",
"x  c #5CFF9D",
"c  c #5DFF9E",
"v  c #5EFF9E",
"b  c #5FFF9F",
"n  c #64FFA2",
"m  c #65FFA3",
"M  c #6AFFA6",
"N  c #6CFFA7",
"B  c #6DFFA7",
"V  c #6FFFA9",
"C  c #71FFAA",
"Z  c #72FFAA",
"A  c #79FFAF",
"S  c #7AFFAF",
"D  c #7BFFB0",
"F  c #7CFFB0",
"G  c #7FFFB2",
"H  c #87FFB7",
"J  c #88FFB8",
"K  c #89FFB8",
"L  c #8BFFB9",
"P  c #8CFFBA",
"I  c #8EFFBB",
"U  c #96FFC0",
"Y  c #97FFC1",
"T  c #9BFFC3",
"R  c #9DFFC4",
"E  c #A0FFC6",
"W  c #A3FFC8",
"Q  c #A5FFC9",
"!  c #A7FFCA",
"~  c #A8FFCB",
"^  c #AAFFCC",
"/  c #ABFFCD",
"(  c #ACFFCD",
")  c #ADFFCE",
"_  c #B2FFD1",
"`  c #B4FFD2",
"'  c #B5FFD3",
"]  c #B6FFD3",
"[  c #B8FFD4",
"{  c #B9FFD5",
"}  c #BAFFD6",
"|  c #BFFFD9",
" . c #C0FFD9",
".. c #C1FFDA",
"X. c #C2FFDA",
"o. c #C3FFDB",
"O. c #C4FFDC",
"+. c #C5FFDC",
"@. c #C9FFDF",
"#. c #CCFFE0",
"$. c #CEFFE2",
"%. c #D0FFE3",
"&. c #D1FFE3",
"*. c #D3FFE5",
"=. c #D6FFE6",
"-. c #D7FFE7",
";. c #D8FFE8",
":. c #D9FFE8",
">. c #DBFFE9",
",. c #DEFFEB",
"<. c #E0FFEC",
"1. c #E1FFED",
"2. c #E4FFEF",
"3. c #E7FFF1",
"4. c #E8FFF1",
"5. c #EFFFF5",
"6. c #F0FFF6",
"7. c #F1FFF7",
"8. c #F3FFF8",
"9. c #F5FFF9",
"0. c #F6FFFA",
"q. c #F8FFFB",
"w. c #F9FFFB",
"e. c #FAFFFC",
"r. c #FBFFFD",
"t. c #FCFFFD",
"y. c #FEFFFE",
"u. c #FFFFFF",
/* pixels */
"          o j W >.8.9.1.{ C ,           ",
"        p :.u.u.u.u.u.u.u.u.7.Z .       ",
"      m t.u.u.u.u.u.u.u.u.u.u.u.T .     ",
"    u r.u.u.u. .v r r b o.u.u.u.u.Z     ",
"  . $.u.u.u.G             S u.u.u.6.=   ",
"  r u.u.u.[                 _ u.u.u.c   ",
"  F u.u.u.v                 l u.u.u.U   ",
"  Y u.u.u.t                 9 u.u.u.^   ",
"  P u.u.u.h                 s u.u.u.U   ",
"  B u.u.u.R                 Z u.u.u.c   ",
"  6 y.u.u.w.w             + -.u.u.6.&   ",
"    ] u.u.u.2.0         . T u.u.u.V     ",
"    3 4.u.u.u.q.H <   % E u.u.u.Q .     ",
"      e <.u.u.u.u.r...:.u.u.u.! #       ",
"        ; 1.u.u.u.u.u.u.u.u.@.@         ",
"      > ' u.u.u.6.u.u.u.u.u.u.-.u       ",
"    = &.u.u.r.G O 8 A %.u.u.u.u.e.k     ",
"  . } u.u.y.z           d ,.u.u.u.9.7   ",
"  g u.u.u.P               : $.u.u.u./   ",
"  #.u.u.w.1                 6 w.u.u.e.- ",
"4 u.u.u.+.                    ` u.u.u.p ",
"i u.u.u.Q                     J u.u.u.x ",
"y u.u.u.~                     H u.u.u.h ",
"2 u.u.u.;.                    X.u.u.u.q ",
"  =.u.u.u.z                 a u.u.u.3.. ",
"  M u.u.u.0.n X           l 5.u.u.u.D   ",
"  O X.u.u.u.u.-.L B N K *.u.u.u.u.*.$   ",
"    > O.u.u.u.u.u.u.u.u.u.u.u.u.-.5     ",
"      @ S 7.u.u.u.u.u.u.u.u.5.J $       ",
"          * g I ( | | ) L f &           "
};
