/* XPM */
static xpm_row_t const rtc_9[] = {
/* columns rows colors chars-per-pixel */
"20 30 111 2 ",
"   c #00FF66",
".  c #01FF67",
"X  c #02FF67",
"o  c #03FF68",
"O  c #04FF68",
"+  c #05FF69",
"@  c #06FF6A",
"#  c #08FF6B",
"$  c #09FF6B",
"%  c #0CFF6D",
"&  c #0DFF6E",
"*  c #0FFF6F",
"=  c #10FF70",
"-  c #17FF74",
";  c #19FF75",
":  c #1AFF76",
">  c #1CFF77",
",  c #1DFF77",
"<  c #1EFF78",
"1  c #23FF7B",
"2  c #25FF7C",
"3  c #28FF7E",
"4  c #29FF7F",
"5  c #2BFF80",
"6  c #2CFF80",
"7  c #2EFF82",
"8  c #32FF84",
"9  c #33FF85",
"0  c #3AFF89",
"q  c #3DFF8B",
"w  c #3EFF8B",
"e  c #3FFF8C",
"r  c #40FF8C",
"t  c #41FF8D",
"y  c #42FF8E",
"u  c #44FF8F",
"i  c #45FF8F",
"p  c #49FF92",
"a  c #4AFF92",
"s  c #4FFF95",
"d  c #50FF96",
"f  c #52FF97",
"g  c #55FF99",
"h  c #57FF9A",
"j  c #58FF9B",
"k  c #5AFF9C",
"l  c #5DFF9E",
"z  c #5FFF9F",
"x  c #62FFA1",
"c  c #64FFA2",
"v  c #67FFA4",
"b  c #6AFFA6",
"n  c #6BFFA6",
"m  c #6DFFA7",
"M  c #7CFFB0",
"N  c #7DFFB1",
"B  c #7EFFB2",
"V  c #80FFB3",
"C  c #81FFB3",
"Z  c #85FFB6",
"A  c #87FFB7",
"S  c #88FFB8",
"D  c #8BFFB9",
"F  c #8CFFBA",
"G  c #8DFFBB",
"H  c #90FFBC",
"J  c #92FFBE",
"K  c #94FFBF",
"L  c #98FFC1",
"P  c #9AFFC2",
"I  c #9CFFC4",
"U  c #9DFFC4",
"Y  c #9EFFC5",
"T  c #A5FFC9",
"R  c #A7FFCA",
"E  c #A8FFCB",
"W  c #AEFFCE",
"Q  c #B0FFD0",
"!  c #B3FFD1",
"~  c #B5FFD3",
"^  c #B6FFD3",
"/  c #BBFFD6",
"(  c #BFFFD9",
")  c #C0FFD9",
"_  c #C1FFDA",
"`  c #C3FFDB",
"'  c #CBFFE0",
"]  c #CEFFE2",
"[  c #CFFFE2",
"{  c #D1FFE3",
"}  c #D2FFE4",
"|  c #D4FFE5",
" . c #D9FFE8",
".. c #E0FFEC",
"X. c #E4FFEF",
"o. c #E7FFF1",
"O. c #E8FFF1",
"+. c #E9FFF2",
"@. c #EAFFF2",
"#. c #EBFFF3",
"$. c #EDFFF4",
"%. c #F0FFF6",
"&. c #F2FFF7",
"*. c #F3FFF8",
"=. c #F4FFF8",
"-. c #F5FFF9",
";. c #F7FFFA",
":. c #FBFFFD",
">. c #FDFFFE",
",. c #FEFFFE",
"<. c #FFFFFF",
/* pixels */
"            , m H R P C i O             ",
"        < Q >.<.<.<.<.<.<.#.b o         ",
"      r &.<.<.<.<.<.<.<.<.<.<./ $       ",
"    8 -.<.<.<.=.R Z K [ <.<.<.<.~ .     ",
"  + { <.<.<.) -         g -.<.<.<.x     ",
"  h <.<.<. .&             g <.<.<.+.@   ",
"  / <.<.<.s                 ) <.<.<.d   ",
"# ;.<.<.%.O                 k <.<.<.T   ",
"6 <.<.<.]                   : <.<.<. .  ",
"w <.<.<.~                     *.<.<.>.% ",
"9 <.<.<.)                     ..<.<.<.1 ",
"; <.<.<.@.                    ] <.<.<.8 ",
"  X.<.<.<.w                   ( <.<.<.0 ",
"  G <.<.<.' #                 _ <.<.<.5 ",
"  < *.<.<.<.' t o       @ p Y -.<.<.<.: ",
"    z ,.<.<.<.<.%.| | @.<.<.<.<.<.<.<.$ ",
"      l -.<.<.<.<.<.<.<.<.<.<.<.<.<.%.  ",
"        > L O.<.<.<.<.<.;.W F <.<.<.`   ",
"            . 4 e f q 2 #   C <.<.<.D   ",
"                            ] <.<.<.u   ",
"                          y <.<.<.o.+   ",
"                        X ` <.<.<.V     ",
"                        M <.<.<.$.=     ",
"                      c :.<.<.<.l       ",
"                  ; I <.<.<.<.I         ",
"            & a U =.<.<.<.<.E +         ",
"    v ! ( ..<.<.<.<.<.<.:.N X           ",
"    J <.<.<.<.<.<.<.,.^ 7               ",
"    S <.<.<.<.,.} A 3                   ",
"    i B n j q *                         "
};
