/* XPM */
static xpm_row_t const rtc_2[] = {
/* columns rows colors chars-per-pixel */
"20 30 57 1 ",
"  c #00FF66",
". c #03FF68",
"X c #04FF68",
"o c #06FF6A",
"O c #09FF6B",
"+ c #0BFF6D",
"@ c #0DFF6E",
"# c #11FF70",
"$ c #12FF71",
"% c #16FF73",
"& c #1DFF77",
"* c #1FFF79",
"= c #20FF79",
"- c #25FF7C",
"; c #2FFF82",
": c #35FF86",
"> c #3EFF8B",
", c #44FF8F",
"< c #48FF91",
"1 c #4DFF94",
"2 c #53FF98",
"3 c #55FF99",
"4 c #5CFF9D",
"5 c #69FFA5",
"6 c #73FFAB",
"7 c #77FFAD",
"8 c #79FFAF",
"9 c #81FFB3",
"0 c #83FFB5",
"q c #84FFB5",
"w c #88FFB8",
"e c #90FFBC",
"r c #95FFBF",
"t c #9CFFC4",
"y c #A7FFCA",
"u c #A9FFCB",
"i c #ABFFCD",
"p c #AFFFCF",
"a c #BBFFD6",
"s c #BFFFD9",
"d c #C3FFDB",
"f c #C5FFDC",
"g c #CFFFE2",
"h c #D1FFE3",
"j c #D3FFE5",
"k c #DAFFE9",
"l c #DDFFEB",
"z c #E3FFEE",
"x c #E7FFF1",
"c c #EAFFF2",
"v c #EEFFF5",
"b c #F1FFF7",
"n c #F3FFF8",
"m c #F5FFF9",
"M c #FAFFFC",
"N c #FBFFFD",
"B c #FFFFFF",
/* pixels */
"     @4epptq1@      ",
"   *tnBBBBBBBbwO    ",
"  5nBBBBBBBBBBBg#   ",
" 0BBBBBxsalBBBBBd   ",
" ,BBBp>    ;dBBBB1  ",
"  ec1       OhBBBp  ",
"  O=         2BBBc  ",
"             $BBBBo ",
"             oBBBB@ ",
"             =BBBv  ",
"             6BBBu  ",
"            +zBBB,  ",
"            rBBBs   ",
"           5BBBm-   ",
"          1NBBB3    ",
"         <mBBB8     ",
"        <MBBBt      ",
"       ,mBBBuo      ",
"      ,mBBBy        ",
"     :bBBBiX        ",
"    &cBBBio         ",
"    fBBBdO          ",
"   6BBBk$           ",
"  #bBBN:            ",
"  8BBB9             ",
"  jBBB@             ",
" %BBBNhffggfgffggfgo",
" :BBBBBBBBBBBBBBBBBO",
" ,BBBBBBBBBBBBBBBBBo",
" =77777777777777778 "
};
