/* XPM */
static xpm_row_t const rtc_dots[] = {
/* columns rows colors chars-per-pixel */
"20 30 40 1 ",
"  c #00FF66",
". c #01FF67",
"X c #04FF68",
"o c #05FF69",
"O c #0DFF6E",
"+ c #0FFF6F",
"@ c #12FF71",
"# c #15FF73",
"$ c #21FF7A",
"% c #22FF7A",
"& c #2FFF82",
"* c #32FF84",
"= c #33FF85",
"- c #34FF85",
"; c #35FF86",
": c #3AFF89",
"> c #58FF9B",
", c #5EFF9E",
"< c #67FFA4",
"1 c #6BFFA6",
"2 c #82FFB4",
"3 c #87FFB7",
"4 c #88FFB8",
"5 c #89FFB8",
"6 c #8AFFB9",
"7 c #8DFFBB",
"8 c #A1FFC7",
"9 c #A7FFCA",
"0 c #ACFFCD",
"q c #B2FFD1",
"w c #B9FFD5",
"e c #BEFFD8",
"r c #C2FFDA",
"t c #C9FFDF",
"y c #CBFFE0",
"u c #CCFFE0",
"i c #D0FFE3",
"p c #F8FFFB",
"a c #FAFFFC",
"s c #FFFFFF",
/* pixels */
"                    ",
"                    ",
"                    ",
"                    ",
"        &56*        ",
"       ;pssa:       ",
"       8ssss9       ",
"       0ssssq       ",
"       >ssss,       ",
"        <ty1.       ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"        .$%.        ",
"       Oessr+       ",
"       2ssss3       ",
"       qssssw       ",
"       4ssss7       ",
"       @ussi#       ",
"        X=-o        ",
"                    ",
"                    ",
"                    "
};
